### PR TITLE
Mitigate rounding errors in GetMap width/height calculation

### PR DESCRIPTION
**Pull request by giohappy**
This patch wants to mitigate widht/height rounding errors that affect GetMap requests as described in issue #6343

### CODE REVIEW

**Comment by giohappy** [comment]
Right @ahocevar I've pushed a new patch where Math.ceil is still used and the BBOX is calculated on the base of the round sizes

**Comment by ahocevar** [comment]
Looks like you'll need to update some tests to reflect the bbox changes that this modification results in.

**Comment by giohappy** [comment]
Yes I see...

**Comment by ahocevar** [comment]
Hm. Unfortunately there was a reason for this test. See #4334. The changes suggested here break this indeed.

I'm tempted to accept the first commit of this pull request (the one that uses `Math.round`). It's a pragmatic solution with only a minor flaw. Can you please update your pull request to remove the 2nd commit? I want to play around with it and see if the 1 pixel gap with `ratio: 1` is a problem at all.

**Comment by giohappy** [comment]
@ahocevar honestly I don't like very much the first solution because it works fine for small roundings but in the worst case, e.g., 100.5 being rounded to 101, a relevant distortion happens even with Math.round if the WMS server doesn't accomodate the different BBOX and H/W ratios (and it shouldn't do it according to WMS 1.3 spec).
Probably we should find a solution that fits both issues...

**Comment by giohappy** [comment]
this new commit accomodate both needs. Maybe it could be more elegant but it does the work.

**Comment by bjornharrtell** [comment]
Thanks for this @giohappy, I think I've seen issues that was caused by this before but did not connect the dots as to what was going on.

**Comment by giohappy** [comment]
@ahocevar squash done

**Pull request merged**
