### PR TITLE
Shadow root

### LINKED ISSUE #10162: stopEvent not working in shadow-root
**Describe the bug**
With an OpenLayers map inside shadow-root (WebComponent) Overlay with `stopEvent = true` does not stop events from propagating.

Problem is possibly in: https://github.com/openlayers/openlayers/blob/a3c137cff15ae8027d0cdb04a162ebb2fa977451/src/ol/PluggableMap.js#L937-L943

For click events originating from an Overlay div events have their first `mapBrowserEvent.target` to be `shadow-root` and therefore `if (target.parentElement === this.overlayContainerStopEvent_) {` never evaluates to `true`.

Is this expected behavior in v6.x or does it exists a workaround that works inside shadow-root?

**To Reproduce**
1. Create a minimal HTML-page with a WebComponent and minimal OL map.
```
<html>

<head>
    <script src="https://cdn.jsdelivr.net/gh/openlayers/openlayers.github.io@master/en/v6.0.1/build/ol.js"></script>
</head>

<body>
    <ol-map></ol-map>

    <script>
        class OLComponent extends HTMLElement {
            connectedCallback() {
                this.shadow = this.attachShadow({ mode: 'open' });
                this.render();
            }

            displayMap(div, overlayDiv) {
                const layer = new ol.layer.Tile({
                    source: new ol.source.OSM()
                });

                const map = new ol.Map({
                    layers: [layer],
                    target: div,
                    view: new ol.View({
                        center: [0, 0],
                        zoom: 2
                    })
                });

                const overlay = new ol.Overlay({
                    stopEvent: true,
                    insertFirst: true,
                    element: overlayDiv
                });

                map.addOverlay(overlay);

                map.on('singleclick', function (e) {
                    overlay.setPosition(e.coordinate);
                    overlay.element.innerHTML = '<div style="padding: 10px; background: #fff;">Testing</div>';
                });
            }

            render() {
                const div = document.createElement('div');
                div.classList.add('map');
                div.style.width = '600px';
                div.style.height = '300px';
                this.shadow.appendChild(div);

                const link = document.createElement('link');
                link.rel = 'stylesheet';
                link.type = 'text/css';
                link.href = 'https://cdn.rawgit.com/openlayers/openlayers.github.io/master/en/v5.3.0/css/ol.css';
                this.shadow.appendChild(link);

                const overlay = document.createElement('div');
                this.shadow.appendChild(overlay);

                this.displayMap(div, overlay);
            }
        }

        customElements.define('ol-map', OLComponent);

    </script>
</body>

</html>
```
2. Singleclicks on the map will display Overlay at correct positions. **But if clicking the overlay div, events are propagated to the map despite being told not to.** This happens not in v5.3.0.

**Expected behavior**
Should work like in v5.3.0.

### PR DESCRIPTION
**Pull request by ahocevar**
Fixes #10162.

In addition to making events work when the map's root node is a ShadowRoot, this pull request adds an example that shows how to create a custom element with a map.

### CODE REVIEW

**Comment by matuisti** [comment]
I tested this and it seems to work right.

**Comment by DeleteElf** [comment]
i`m use 6.1.1 and update to openlayers-master, singleclick can`t work in iphone by this change

**Comment by DeleteElf** [comment]
i am use 6.1.1 and update to openlayers-master, singleclick can not work in iphone by this change

**Comment by ahocevar** [comment]
@DeleteElf Please use `npm install ol@dev` to get a version that includes this change.

**Pull request merged**
