### PR TITLE
Fix JSTS usage with OL classes injected

### PR DESCRIPTION
**Pull request by bjornharrtell**
This makes the JSTS example run again and also updates ref to JSTS to the latest stable version.

ref https://github.com/openlayers/openlayers/issues/8192.

- [x] This pull request addresses an issue that has been marked with the 'Pull request accepted' label & I have added the link to that issue.
- [x] It contains one or more small, incremental, logically separate commits, with no merge commits.
- [x] I have used clear commit messages.
- [x] Existing tests pass for me locally & I have added or updated tests for new or changed functionality.

### CODE REVIEW

**Comment by bjornharrtell** [comment]
No I agree that would be nice @ahocevar, but I was hesitant if example deps is ok to add to devDependencies which I guess is what is needed?

**Comment by bjornharrtell** [comment]
Oh.. and actually I'm not sure to handle it on JSTS side - OpenLayers is a runtime dependency.

**Comment by ahocevar** [comment]
I think it‘s ok to add example dependencies as devDependencies. We‘re doing it for proj4 already.

**Comment by ahocevar** [comment]
> OpenLayers is a runtime dependency.

So the inject call is necessary regardless?

**Comment by bjornharrtell** [comment]
@ahocevar, afraid so I think.. until dynamic import() "just works" I guess. :( Injection could probably done in a nicer way though.

**Comment by ahocevar** [comment]
So should we call it good and merge as-is, or do you want to play with it a bit more?

**Comment by bjornharrtell** [comment]
Good and merge as is is my vote.

**Pull request merged**
