### PR TITLE
Only draw visible worlds

### PR DESCRIPTION
**Pull request by MoonE**
With a multi-world source and projection currently every world until world zero or from world zero is rendered depending on if the current world(s) are left or right of world zero. So if worlds -100 and -99 are in the current view all worlds between are also rendered. It should be enough to only render the visible two worlds.

This PR changes the order of world rendering, but I don't think it matters, does it?
Before: 
- world zero (always), 
- negative worlds increasing order (if to the left)
-  positive worlds decreasing order (if to the right)

Now:
- always increasing from left to right

### CODE REVIEW

**Review by ahocevar — APPROVED** [review]
This is a nice simplification, and the order does not matter indeed. Thanks, @MoonE!

**Review by ahocevar — APPROVED** [review]

**Comment by ahocevar** [comment]
I'm going to check the failing rendering test to see if there aren't any unexpected changes.

**Comment by MoonE** [comment]
It rendered one world too many. I think the failed render test was related to #11523.

**Comment by MoonE** [comment]
I did not account for the offset of the projection which does not start at zero.

**Review by ahocevar — APPROVED** [review]
Thanks, @MoonE!

**Comment by MoonE** [comment]
I think I messed up with the last change I made 
https://github.com/openlayers/openlayers/compare/6e01f2139965f0d32ff62a27c3b85fab199a0a37..85499d7daf9ac5871d2ef3849be1fc1a0859ee86
It now only works correctly if the projection extents' x-midpoint is at zero.

**Pull request merged**
