### PR TITLE
Add Arrow style for vector features

### PR DESCRIPTION
**Pull request by tananaev**
All or most applications related to navigation or tracking require to indicate direction of objects on a map. Arrow style provides default customizable and stylable implementation of the arrow shape for vector features.

Please consider including this style into the main openlayers code base.

### CODE REVIEW

**Comment by ahocevar** [comment]
I wonder if we shouldn't do something more generic than just adding fixed shapes. If an image style could be configured with an `ol.geom.Geometry` with pixel coordinates, users could use arbitrary shapes as image style.

**Comment by tananaev** [comment]
I agree that it would be nice to have a more generic solution. I can try to implement it using `ol.geom.SimpleGeometry` class.

Any other comments?

**Comment by tananaev** [comment]
To draw geometry objects I guess I need to use `ol.render.canvas.Immediate`. Any ideas on how to properly re-use methods from there in my style object?

**Comment by tschaub** [comment]
If the remaining work can be completed before the upcoming 4.6 release, please reopen this pull request.  After 4.6, we will be transforming the sources to ES modules, and if we want to pick up this effort, it may be easier to create the changes from scratch.

**Pull request closed without merging**
