### PR TITLE
Check if the layer renderer exists before calling dispose

### PR DESCRIPTION
**Pull request by fredj**
see #9354

### CODE REVIEW

**Comment by tschaub** [comment]
Is something else calling dispose on the render in this case?

**Comment by ahocevar** [comment]
> Is something else calling dispose on the render in this case?

I suspect that the reason is simply a `removeLayer()` call before the layer added with `addLayer()` was rendered. The renderer won't be created before `Layer#render()` is called for the first time.

**Comment by fredj** [comment]
I cannot reproduce the issue from #9354 using the minimal example: https://codesandbox.io/s/9z91jo8j5y

I propose to close this pull request

**Comment by ahocevar** [comment]
Ok sounds good. I ran into a similar issue that I'm investigating right now. I can create a new pull request if it turns out that it's not an application issue.

**Comment by ahocevar** [comment]
My issue is also fixed with master.

**Pull request closed without merging**
