### PR TITLE
Add ol.source.Cluster#getDistance function

### LINKED ISSUE #6703: No getDistance in cluster
It looks so simple to have "getDistance" but is there some reason why it only has "setDistance" but "getDistance"? I think, when you want to set new cluster distance, it would help to compare with current distance. 

Thanks,

### PR DESCRIPTION
**Pull request by fredj**
fixes #6703

### CODE REVIEW

**Comment by fredj** [comment]
Thanks for the review

**Comment by lourencogui** [comment]
Hello guys, 

I ran across this same issue in ol3 in v3.11.0. I noticed that the pull request was accepted, but I can't find this fix tag in the open layer release list web page(https://github.com/openlayers/openlayers/releases).

Dumb question, do you guys know if this fix is already in any release?

Because I can't find, and I need it asap.

Thanks in advance.

**Comment by cs09g** [comment]
@lourencogui it's with [v4.1.0](https://github.com/openlayers/openlayers/releases/tag/v4.1.0)

**Comment by lourencogui** [comment]
@cs09g I found it. I've looking for fixes tag #6703, that was the mistake.

Thanks for your attention.

**Pull request merged**
