### PR TITLE
Remove the '3' from OpenLayers

### PR DESCRIPTION
**Pull request by ahocevar**
This pull request removes the "3" from OpenLayers, so we can transition to semantic versioning if we want to.

### CODE REVIEW

**Comment by marcjansen** [comment]
+1 for semver.

**Comment by probins** [comment]
which also means anyone with a clone needs to update their remote

**Comment by ahocevar** [comment]
> which also means anyone with a clone needs to update their remote

GitHub has a redirect, so `ol3` will continue to work.

**Comment by tschaub** [comment]
Looks good please merge.

**Pull request merged**
