### PR TITLE
Add ol.format.WMSCapabilities format

### PR DESCRIPTION
**Pull request by fredj**
work in progress

### CODE REVIEW

**Comment by bartvde** [comment]
@fredj can you clarify if this parser is supposed to work for version 1.1.1? Or only 1.3.0?

**Comment by bartvde** [comment]
Looking at the output of the parser it seems a larger part of a WMS 1.1.1 doc is parsed, but this is probably only due to the common aspects / elements between 1.1.1 and 1.3.0? So my guess is this code is not intended to be used on 1.1.1, and adding 1.1.1 would mean splitting the parser up into a base and versioned classes similar to what has been done for GML.

**Comment by fredj** [comment]
If I remember correctly it has only be tested for 1.3.0

**Comment by bartvde** [comment]
thanks for clarifying @fredj

**Pull request merged**
