### PR TITLE
Fix getMap width/height calculation regression

### PR DESCRIPTION
**Pull request by giohappy**
HEIGHT / WIDTH were not correctly rounded to integer values

### CODE REVIEW

**Comment by ahocevar** [comment]
Can you please describe what the problem is, and point to the change that caused the "regression"?

**Comment by giohappy** [comment]
The extent and the image sizes where coherent but [this product](https://github.com/openlayers/openlayers/blob/master/src/ol/source/imagewms.js#L236) introduces decimals in width/height values

**Comment by giohappy** [comment]
@ahocevar The ''returns same image for consecutive calls with same args'' test fails because [this](https://github.com/giohappy/ol3/blob/9eeedd96d595592ff9c0872ed17330b62659ee89/src/ol/source/imagewms.js#L213) introduces a spurious rounding error (10.01 -> 10.010000000000002) so the consecutive calls don't return exactly the same image.
How should it be solved?

**Comment by giohappy** [comment]
@ahocevar I think we need to circumnvent the rounding error, arising with the test, but the patch needs to be applied otherwise  WMS servers will (correctly) complain for not integer WIDTH/HEIGHT values

**Comment by bartvde** [comment]
@giohappy I think you  can use roughlyEqual for that e.g.:

```
 expect(destinationExtent[3]).to.roughlyEqual(8399737.889818361, 1e-8);
```

I agree that we need to enforce WIDTH and HEIGHT to be integers

**Comment by giohappy** [comment]
@bartvde I also was thinking to change the test and use roughlyEqual. If it's ok for you I will proceed fixing the test.

**Comment by ahocevar** [comment]
I'd like to know which commit introduced this regression. Because I seem to remember a change around here in the code, which was made for a reason.

**Comment by giohappy** [comment]
@ahocevar I made the previous patch to fix the problem of having WIDTH/HEIGHT not coherent with extent requested by getMap. This caused problems because WMS 1.3 requires them to have the same ratio otherwise distortion in the image output is applied.
We had to also if susequent calls were already included in the (buffered) image to avoid making new, unuseful requests.
Both the requirements were met by the previous patch but I overlooked the fact that [this lines](https://github.com/openlayers/openlayers/blob/master/src/ol/source/imagewms.js#L236) were introducing decimal values if ratio is not integer.
The new commit fix this while keeping the previous requirements, but [this test](https://github.com/openlayers/openlayers/blob/master/test/spec/ol/source/imagewms.test.js#L161) fails becasue of a Javascript rounding error, explained above.

@bartvde your solution doesn't solve the specific test, because the test should return the same image if we hadn't rounding errors. In case the roughlyEqual should be used in code but I'm not sure it's the right approach...

**Comment by giohappy** [comment]
@ahocevar commit #0bf94a35 was the previous one.

**Comment by ahocevar** [comment]
The test does not fail because of a JavaScript rounding error, but because you changed the logic. I created #6427 with a different approach that does not break tests.

**Comment by ahocevar** [comment]
@giohappy Can you please add tests for #6427 that ensure width and height are integers, so we don't get regressions here again? Thanks.

**Comment by giohappy** [comment]
Are you sure? I tested it carefully and the problem (at elat here) is the following:
The first image is requested with extent [10.01, 20, 30.01, 40]. 
The rounding makes the final image extent [10.010000000000002, 20, 30.01, 40];
When the second image is requested (with the same original extent) the test against the already available image (this._image) fails becasue [10.01, 20, 30.01, 40] is not inside [10.010000000000002, 20, 30.01, 40]. So another image is created and consequently expect(image1).to.equal(image2) will fail.

It's not a logic problem. I've double tested the new logic against Geoserver, Mapserver and QGIS Server (WMS 1.1.1 and 1.3) and it works correctly.

**Comment by ahocevar** [comment]
I did not mean the logic of calculating the request extent - that is perfectly fine. What I meant is that before this patch, the extent was adjusted for pixel resolution before the `containsExtent` check. Now it is not any more. And this inconsistency between pixel width/height and view extent causes the test to fail.

**Comment by fredj** [comment]
@giohappy can we close this pull request ?

**Comment by giohappy** [comment]
Fixed with PR https://github.com/openlayers/openlayers/pull/6427

**Pull request closed without merging**
