### PR TITLE
NM symbol unit

### PR DESCRIPTION
**Pull request by jipexu**
https://github.com/openlayers/openlayers/issues/13497

please check if it is enough ...

### CODE REVIEW

**Review by ahocevar — DISMISSED** [review]
Thanks, @jipexu. There is also a test case that needs to be updated:
```
Chrome Headless 100.0.4889.0 (Linux x86_64) ol.control.ScaleLine #setUnits triggers rerendering FAILED
[78](https://github.com/openlayers/openlayers/runs/5962041699?check_suite_focus=true#step:5:78)
	Error: expected '10000 NM' to equal '10000 nm'
[79](https://github.com/openlayers/openlayers/runs/5962041699?check_suite_focus=true#step:5:79)
	    at Assertion.assert (/home/runner/work/openlayers/openlayers/node_modules/expect.js/index.js:96:13)
[80](https://github.com/openlayers/openlayers/runs/5962041699?check_suite_focus=true#step:5:80)
	    at Assertion.be.Assertion.equal (/home/runner/work/openlayers/openlayers/node_modules/expect.js/index.js:216:10)
[81](https://github.com/openlayers/openlayers/runs/5962041699?check_suite_focus=true#step:5:81)
	    at Assertion.<computed> [as be] (/home/runner/work/openlayers/openlayers/node_modules/expect.js/index.js:69:24)
[82](https://github.com/openlayers/openlayers/runs/5962041699?check_suite_focus=true#step:5:82)
	    at Context.<anonymous> (/tmp/_karma_webpack_43096/webpack:/ol/test/browser/spec/ol/control/scaleline.test.js:224:1)
[83](https://github.com/openlayers/openlayers/runs/5962041699?check_suite_focus=true#step:5:83)
```

**Comment by jipexu** [comment]
thanks @ahocevar   ... i try to understand where it's fail and how to correct .... but not sure i am able to do .....

**Comment by ahocevar** [comment]
Thanks @jipexu. See the stack trace in the failing test. `ol/test/browser/spec/ol/control/scaleline.test.js:224` is the place to fix it in the tests.

**Comment by jipexu** [comment]
thanks ok i see now !

**Comment by jipexu** [comment]
seems to be ok

**Review by ahocevar — APPROVED** [review]
Thanks, @jipexu

**Comment by jipexu** [comment]
welcome

so this can be closed
https://github.com/openlayers/openlayers/issues/13497

**Pull request merged**
