### PR TITLE
Remove console.assert in ol.structs.PriorityQueue tests

### PR DESCRIPTION
**Pull request by fredj**
All `console.assert` have been removed

### CODE REVIEW

**Comment by fredj** [comment]
Added a new commit that removes the `no-console` eslint rule

**Comment by ahocevar** [comment]
@fredj does this mean that eslint now does not complain about the use of `console` anymore? If so, the rule should be added back, but without the exceptions.

**Comment by fredj** [comment]
@ahocevar we are extending eslint-config-openlayers and the use of `console` is not allowed:
https://github.com/openlayers/eslint-config-openlayers/blob/v7.0.0/index.js#L20

(I've just checked and an error is correctly raised)

**Comment by ahocevar** [comment]
Thanks for the clarification @fredj, all is great then :smile:.

**Pull request merged**
