### PR TITLE
Add demo based on 3rd party supercluster library

### PR DESCRIPTION
**Pull request by ThomasG77**
We added the library in the resources as we didn't found it on a CDN or the official github repository.

We named the sample 'supercluster.html' and used the associated 'supercluster.js'.
The particularity of this example is the use of web workers with 'supercluster-worker.js'.
We added the GeoJSON version of the KML earthquakes data as 'supercluster' needs GeoJSON for input.

We may need to correct eslint comment '// eslint-disable-next-line' as it was
the fastest way to make eslint happy with importScripts and supercluster
declarations in the worker file.

Related to #5742 discussion.

### CODE REVIEW

**Comment by ThomasG77** [comment]
Do you need a rebase before reviewing?

**Comment by marcjansen** [comment]
No, not necessarilly. Makes things easier most of the time, though. Also the commit history is then more cleaned up.

I will have look tomorrow, whether this is rebased or not.

**Comment by marcjansen** [comment]
I have had a look at the example. Thanks for it.

Right now I don't want to merge it, because I want an external resource (URL) of `supercluster`, and not included in the `resource/` directory.

If at one point an online URL exists, I would also want a bigger dataset that gets clustered, if possible.

Thanks any how. This PR can be left open, so you can update it when things change.

**Comment by ThomasG77** [comment]
Ongoing PR on supercluster repo to publish library to a CDN. Will update PR when done

**Comment by ThomasG77** [comment]
> If at one point an online URL exists, I would also want a bigger dataset that gets clustered, if possible.

Didn't find one at the moment. Except this, all requirements for PR review & merge OK IMO.

**Comment by ThomasG77** [comment]
> If at one point an online URL exists, I would also want a bigger dataset that gets clustered, if possible.

Except this, ready for review & merge IMO

**Comment by tschaub** [comment]
Please reopen if this can be completed before the 4.6 release.

**Pull request closed without merging**
