### PR TITLE
Fix control styles on Full Screen Mobile example

### PR DESCRIPTION
**Pull request by mike-000**
Correct the css path

### CODE REVIEW

**Comment by tschaub** [comment]
The other examples use the css at `/theme/site.css` instead.

**Comment by mike-000** [comment]
I copied the setup from https://github.com/openlayers/openlayers/blob/main/examples/geolocation-orientation.html  I presumed from that `site.css` was not a full replacement for `ol.css` but site specific customisations?

**Comment by mike-000** [comment]
I think at least one more example may be need changing and/or files may need de-duping.

Most examples use `https://openlayers.org/theme/ol.css` **and** `https://openlayers.org/theme/site.css`

Geolocation Tracking with Orientation is using `https://openlayers.org/en/latest/examples/theme/site.css` **and** `https://openlayers.org/en/latest/examples/theme/ol.css`

while Full Screen Mobile  was attempting to use `https://openlayers.org/en/latest/theme/ol.css` which is a 404.

Should the examples not be version specific?

**Comment by tschaub** [comment]
We decided to have the hosted examples use the css at /theme/.  The other linked style sheets are there for the dev setup.

**Comment by mike-000** [comment]
I have now made `Full Screen Mobile` and `Geolocation Tracking with Orientation` consistent with the other examples.

**Review by tschaub — APPROVED** [review]

**Comment by tschaub** [comment]
Thanks, @mike-000

**Pull request merged**
