### PR TITLE
Allow icon and text styles to be scaled in two dimensions

### PR DESCRIPTION
**Pull request by mike-000**
This revives one of the aims of #6100 and also provides a fix for #10817 if a negative scale is used (images or text are flipped around their anchor point).  Similar to tileSize the API interface is `number | module:ol/size~Size` to be backward compatible, although scales are always stored as arrays which can be accessed using `getScaleArray()` for rendering.

A new example demonstrates an icon and label being scaled in both dimensions in a vector layer and in a vector context..

### CODE REVIEW

**Comment by mike-000** [comment]
My aim was to be able to dynamically scale icons (in a style function if necessary) using `setScale()` while maintaining backward compatibility so that anyone who had set a single scale value continued to get a number returned by `getScale()` .  But instead of simply setting
    `this.scale_ = options.scale;`
I could add
    `this.scaleArray_ = toSize(options.scale);`
and use a non-API `getScaleArray()` method when rendering

 I had not initially intended to extent this to text but as point placement text shared the same logic it was easy to include (I hadn't even considered line placement until type checking picked up I had missed it).  I am not attempting to support RTL line placement either by flip or real RTL in this PR, but I think a `drawTextOnPathRTL()` would be needed as both would require right hand anchor points.

If there is going to be a scale option on text having it two dimensional would surely make it more useful, and it you are going to scale (stretch or squash) an icon you might want to make a corresponding change to the associated text?  I would be more likely to change the font size instead of using the same scale in both dimensions.

**Comment by tschaub** [comment]
@mike-000 - you'll need to rebase on the latest `openlayers/master` to get a new script for the `deploy/netlify` check:
```
git pull --rebase openlayers master
```

Apologies for the churn.

**Comment by mike-000** [comment]
`toSize()` is now called only in the style constructors and `setScale` methods.  New arrays will be created during render only where scales are adjusted for pixel ratio (even that could be reduced by testing `pixelRatio == 1` and adding a new constant `defaultScale = [1, 1]` to  `ol/render/canvas.js`).  I have dropped the addition of scale to the labels example in favour of a new simple example showing both icon and text.

**Comment by tschaub** [comment]
@mike-000, are you able to rebase these commits on master?  That would get rid of the merge commits an other unrelated history above.

If your "upstream" remote (the one for https://github.com/openlayers/openlayers.git or git@github.com:openlayers/openlayers.git) is named `openlayers`, a rebase would look like this:
```bash
git pull --rebase openlayers master
```
If your remote is named something other than `openlayers`, you'd need to substitute that name.  Running `git remote --verbose` will list the names of your remotes.

After rebasing, if you force push, it should remove the extraneous commits above.
```bash
git push --force origin patch-11
```
(Substitute `origin` for the name of the remote corresponding to https://github.com/mike-000/openlayers.git or git@github.com:mike-000/openlayers.git).

**Comment by ahocevar** [comment]
Thanks for your continued effort on this, @mike-000.

**Pull request merged**
