### PR TITLE
Use https for bing and stamen attributions

### LINKED ISSUE #7002: Attribution for BingMaps still served on HTTP, making our HTTPS site unsecure
Our website uses OL3. We recently enabled HTTPS on our website, but maps on Bing still serve the attribution on HTTP, making our map pages unsecure. I found that the links to OpenLayers and the Bing logo is served on HTTP (see screenshot). Can you please fix this immediately so we avoid an audit issue?

Thank you.
attribution

### PR DESCRIPTION
**Pull request by fredj**
fixes #7002

### CODE REVIEW

**Comment by joelaldor** [comment]
Hi there. We're still encountering the same issue. Still serving http://fonts.googleapis.com and http://dev.virtualearth.net. However http://fonts.googleapis.com is no longer accessible.

Please see screenshot. 
attribution

**Comment by fredj** [comment]
http://fonts.googleapis.com comes from https://www.philippineheritagemap.org/static/css/app.css

**Comment by fredj** [comment]
And the resource from http://dev.virtualearth.net is the bing logo but it should be converted to https:
https://github.com/openlayers/openlayers/blob/master/src/ol/source/bingmaps.js#L128-L131

**Comment by joelaldor** [comment]
Oh thanks for correcting. When will this take effect? Right now the image is still being served over HTTP.

**Comment by fredj** [comment]
What version of OpenLayers are you using?

**Comment by fredj** [comment]
Looks like you're using v3.1.1 : https://www.philippineheritagemap.org/static/plugins/openlayers/ol.js

That's very old, and the http -> https conversion was not included in the version; you should update

**Comment by joelaldor** [comment]
Hi there,

Much as we would want to update, it'll take some time before we can upgrade to the next version of our software that uses the latest version of OpenLayers, for various reasons. Is it possible the Bing logo image can be hosted on an HTTPS site so that browsers won't see our map pages are insecure? I believe that's the only issue remaining here. Appreciate all your help so far. Thank you.

**Comment by fredj** [comment]
Maybe by providing your own `getLogo` function, something like:
```js
var bing = new ol.source.BingMaps({
    key: '<api_key>',
    imagerySet: 'Road'
});

bing.getLogo = function() {
    return "https://dev.virtualearth.net/Branding/logo_powered_by.png"
};

layers.push(new ol.layer.Tile({
  source: bing
}));
```

**Comment by joelaldor** [comment]
Where should I put this code?

**Comment by fredj** [comment]
Where `ol.source.BingMaps` is created

**Comment by fredj** [comment]
Probably in https://www.philippineheritagemap.org/static/js/map/base-layers.js

**Comment by mradamcox** [comment]
Hi @fredj, I was trying this out like so

    _.each(bingLayers, function(layer) {
 
        var bing = new ol.source.BingMaps({
            key: arches.bingKey,
            imagerySet: layer.id
        });

        bing.getLogo = function() {
            return "https://dev.virtualearth.net/Branding/logo_powered_by.png"
        };
        
        layer.layer = new ol.layer.Tile({
            visible: false,
            preload: Infinity,
            source: bing
        });
    });

to no avail. getLogo() didn't seem to be called to find the logo. Any thoughts? Is there a way to make sure ol uses that function to acquire the logo?

**Comment by joelaldor** [comment]
Thanks for helping out @mradamcox !

**Comment by joelaldor** [comment]
@fredj any updates on this one?

**Pull request merged**
