### PR TITLE
GML Format Improvements #8516 #8517 #8518

### PR DESCRIPTION
**Pull request by NielsCharlier**
This PR is for three issues unfortunately, because the patches are interdependent. There are however three separate commits.

faetureMember tag support #8516 
basic GML 3.2 format and namespace support #8517  
complex feature support #8518

all patches have test cases included.

### CODE REVIEW

**Comment by NielsCharlier** [comment]
Hmmm the tests for the complex feature parser pass on linux but fail on windows. I have no idea why.

**Comment by NielsCharlier** [comment]
@ahocevar could you perhaps  have a look at this?
would like to have an idea of the chances or what else needs to change before I resolve the merge issues

**Comment by ahocevar** [comment]
@NielsCharlier, I don’t know much about the XML parsers. @fredj or @bartvde would be better reviewers.

**Comment by bartvde** [comment]
I don't have time for an in-depth review but from glancing over the code it looks fine to me, and it's got tests. So I'm +1 for getting this in once it's updated for master and typescript.

**Comment by fredj** [comment]
The code looks good to me too (but I'm not a GML expert ...).

@NielsCharlier If you want, I can update your code to fix the type annotation.

**Comment by NielsCharlier** [comment]
thanks @bartvde. I have fixed the current merging issue and will do this again once the typescript PR has been merged so that this one can be merged shortly afterwards

**Comment by NielsCharlier** [comment]
that would be fantastic @fredj

**Comment by fredj** [comment]
@NielsCharlier I've pushed a commit into your branch that fixes the type annotations.
I will take a last look tomorrow morning and merge this.

And thanks again for your contribution!

**Comment by schmidtk** [comment]
@fredj Should #8711 be merged first to fix existing TS errors in the GML stack? That fixes all of them, which will make it easy to verify this PR doesn't introduce new errors.

**Comment by fredj** [comment]
@schmidtk yes, I've merged merged #8711, thanks

**Comment by NielsCharlier** [comment]
Thanks @fredj !

**Pull request merged**
