### PR TITLE
Rich text labels

### PR DESCRIPTION
**Pull request by ahocevar**
This pull request adds support for rich text labels, i.e. labels that contain formatted text.

https://deploy-preview-13410--ol-site.netlify.app/examples/rich-text-labels.html

To use formatted text, pass an array with text/font tuples as `text` in `ol/style/Text`, e.g.
```
new TextStyle({
  font: '10px sans-serif'
  text: [
    'foo', 'bold 10px sans-serif',
    ' bar', 'italic 10px sans-serif',
    ' baz', ''
  ]
});
```
will yield "**foo** *bar* baz".

### CODE REVIEW

**Comment by mike-000** [comment]
Is the polyfill in the example obsolete now? (also applies to Vector Label Decluttering).

**Comment by ahocevar** [comment]
it is. Thanks, @mike-000.

**Comment by jipexu** [comment]
So cool ! 👍

**Review by tschaub — APPROVED** [review]

**Comment by tschaub** [comment]
Great new feature, @ahocevar.

**Pull request merged**
