### PR TITLE
Mark ol.format.filter.Spatial as abstract class

### PR DESCRIPTION
**Pull request by fredj**
fixes #7217 and add missing `@abstract` tag

### CODE REVIEW

**Comment by fredj** [comment]
Yes, it make sense to remove the `@api` annotation but will it require a new major release (5.0.0) ?

**Comment by ahocevar** [comment]
Hm. Well, you cannot add a `@deprecated` annotation, because you will get a compiler warning. But you could mention that those are deprecated in their docs. And we can remove the `@api` annotation later, i.e. before we release 5.0.

**Comment by fredj** [comment]
@ahocevar I've added the deprecation warning in the doc

**Comment by fredj** [comment]
Thanks for the review

**Pull request merged**
