### PR TITLE
Use ol/array#includes instead of Array.prototype.includes()

### PR DESCRIPTION
**Pull request by mike-000**
Fixes browser compatibility in the IIIF Image API example which currently doesn't work with IE and perhaps some other old browsers.

### CODE REVIEW

**Comment by MoonE** [comment]
Please also change the uses of includes in `ol/source/IIIF.js`.

**Comment by mike-000** [comment]
> Please also change the uses of includes in `ol/source/IIIF.js`.
> 
> Maybe it would be reasonable to add `includes` / `find` / `findIndex` to the list of required polyfills instead?

If those (and all other built-in polyfill) methods exists they should be used consistently, not duplicated.  I noticed the problem with `ol/format/IIIFInfo` on the v6.4.3 example but a Mapbox update now means none of the dev or 6.5.0 examples currently work with IE so I was unable to test if further changes were needed.

**Comment by MoonE** [comment]
The examples should work again in ie11 with #11871.
Please rebase on the latest version in the main branch.

**Comment by MoonE** [comment]
You are of course correct that the available methods should be used consistently. 
Though in my optinion it would make sense to rely on polyfills for these functions instead as it is a bit of a hassle for every contributor to remember which functions should not be used.

**Review by MoonE — APPROVED** [review]
Thanks, @mike-000.

**Pull request merged**
