### PR TITLE
Fix textAlign start/end for placement: line

### LINKED ISSUE #14930: textAlign start/end regression
It looks like we had an unnoticed regression regarding the `'start'` and `'end'` values of the `Text` style's `textAlign` property.

When I updated the reference images of the rendering tests in #14928, I noticed a difference in `test/rendering/cases/text-style-linestring-nice` that went unnoticed for a long time: the texts 'Small text' and 'negative offsetX' are aligned at the wrong end.

### PR DESCRIPTION
**Pull request by ahocevar**
Fixes #14930

### CODE REVIEW

**Review by jahow — COMMENTED** [review]
The change in this PR looks good but I'm confused because the image currently on main seems correct: "small text" is at the start of the line and "negative offset X" is at the end.

Am I missing something?

**Comment by ahocevar** [comment]
The image in main is correct, but a failing test in #14923 revealed the problem, which was unnoticed because the change was below the image tolerance threshold.

**Comment by ahocevar** [comment]
@jahow Now that #14923 is merged, I rebased this pull request and you can see the change in the diff of the reference image.

**Comment by jahow** [comment]
> @jahow Now that #14923 is merged, I rebased this pull request and you can see the change in the diff of the reference image.

Ok yes, I understand, the image on main wasn't what the actual result looked like! But now doesn't that mean that this PR will significantly change the behavior for the `textAlign` property on lines? I mean, if that regression was there for a while, maybe people inverted `end` and `start` values in their application?

**Comment by ahocevar** [comment]
`start` and `end` is useful for applications that mix left-to-right and right-to-left text. I don't think there are many, otherwise someone would have created a bug issue.

To avoid such regressions in the future, I lowered the test tolerance.

**Comment by ahocevar** [comment]
I was wrong in assuming that this was a regression. The failed attempt to get left-to-right/right-to-left detection right was #11722, and that simply failed to fix the problem for text alignment along lines. So it was still broken after #11722, and is now fixed.

**Comment by ahocevar** [comment]
@jahow Were you suggesting to add a note about this in the release notes, or do you not agree with the fix in its entirety?

**Review by jahow — APPROVED** [review]
Yes a mention of this in the release notes wouldn't hurt I guess! Thanks for the fix and taking the time to make sense of all this :)

**Pull request merged**
