### PR TITLE
getGetLegendRequestUrl accepts a LAYER parameter

### LINKED ISSUE #9829: getGetLegendRequest should take a layer name as parameter
Follow up to #9762

While using the getGetLegendRequest method I found that it would be very useful if it was possible to set the layer for which a legend is requested instead of just aborting the execution.

https://github.com/openlayers/openlayers/blob/ec10cda088cdfc447b0e94fce8fccf6d9d5d9ae0/src/ol/source/ImageWMS.js#L210

I would suggest it is possible to set the `LAYER` property of params which will be checked for existence and only abort if either `LAYER` is set or the source has more than one or no wms layers.

### PR DESCRIPTION
**Pull request by simonseyock**
Fixes #9829

### CODE REVIEW

**Comment by tschaub** [comment]
Unrelated to this change, but I wonder what folks would think of renaming `getGetLegendGraphicUrl` to `getLegendUrl`.

**Comment by simonseyock** [comment]
The name was chosen to be similar to getGetFeatureInfoUrl. I am in favour of renaming, it is really clunky now. But then the other method should be renamed as well.

**Comment by marcjansen** [comment]
This is what we major releases for. Plus one on renaming

**Comment by jahow** [comment]
Once the renaming is done this PR is good to merge IMO. Thanks!

As for renaming `getGetFeatureInfoUrl`, what would you call it @simonseyock ?

**Comment by simonseyock** [comment]
Sorry for answering this late I am on vacation right now. I would rename it to `getFeatureInfoUrl` . But I would prefer a different PR for renaming.

**Comment by simonseyock** [comment]
But I can open another one first and then rebase this one.

**Comment by simonseyock** [comment]
Rebasing done.

**Comment by tschaub** [comment]
Thanks @simonseyock.

**Pull request merged**
