### PR TITLE
Fix MapGuide example resolves #7325

### LINKED ISSUE #7325: MapGuide source doesn't work anymore
The MapGuide example doesn't work for months: https://openlayers.org/en/latest/examples/mapguide-untiled.html
Seems that the service has changed or isn't provided anymore:

[Domain](http://data.mapguide.com)
[request example](http://data.mapguide.com/mapguide/mapagent/mapagent.fcgi?USERNAME=Anonymous&OPERATION=GETMAPIMAGE&VERSION=2.0.0&LOCALE=en&CLIENTAGENT=ol.source.ImageMapGuide%20source&CLIP=1&SETDISPLAYDPI=96&SETDISPLAYWIDTH=3306&SETDISPLAYHEIGHT=1000&SETVIEWSCALE=28889.585495355568&SETVIEWCENTERX=-87.80837026736403&SETVIEWCENTERY=43.756715686555566&MAPDEFINITION=Library%3A%2F%2FSamples%2FSheboygan%2FMaps%2FSheboygan.MapDefinition&FORMAT=PNG)

Maybe it could be removed.

### PR DESCRIPTION
**Pull request by TDesjardins**
This pull request fixes the MapGuide source example by switching to a new working MapGuide server (see #7325).

### CODE REVIEW

**Comment by bartvde** [comment]
@ahocevar any idea on the font check failure in Edge?

**Comment by ahocevar** [comment]
@bartvde Looks like a font took too long to load. I restarted the build, and now everything passed.

**Comment by bartvde** [comment]
thank you @TDesjardins and @flipper44

**Comment by bartvde** [comment]
thanks @ahocevar

**Pull request merged**
