### PR TITLE
Replace Bing sources in some examples

### LINKED ISSUE #10294: Bing based examples fail to show map
**Describe the bug**
Bing based example on OpenLayers website show gray map zone with nothing inside.

**To Reproduce**
1. Go to https://openlayers.org/en/latest/examples/index.html?q=bing
2. Open any of the filtered examples
3. Map zone only show + and – zoom buttons

**Expected behavior**
Map with Bing map background?

### PR DESCRIPTION
**Pull request by mike-000**
Fixes #10294

Replace Bing sources with Esri World Streets and Esri World Imagery in some examples where Bing is not specifically required,

### CODE REVIEW

**Comment by ahocevar** [comment]
Can you please provide a link to the terms of use of the Esri layers, to make sure we can use them this way in the examples?

**Comment by ahocevar** [comment]
Looks like I'm right and we cannot use these layers. See the [Terms of use link](http://downloads2.esri.com/ArcGISOnline/docs/tou_summary.pdf) at the bottom of https://www.arcgis.com/home/item.html?id=a2e7c99be14d421abac4f002d6c301f5. Even worse, I believe that Esri's world imagery is just a wrapped Bing Maps service, and the linked terms do not apply to Bing Maps. In that case, Bing Maps terms apply, and we're back to where we were.

I would suggest for all examples that do not need imagery data to use the OSM or Stamen source.

**Comment by mike-000** [comment]
All those examples use imagery (two also use streets).  I had assumed it would be OK as the xyz-esri and xyz-esri-4326-512 examples already used Esri sources but you may also need to review those.

**Comment by ahocevar** [comment]
Good point. @bartvde, I think you did the work on Esri sources back then. Do you remember if there was any agreement with Esri, or if the terms of use allow us to use these layers?

**Comment by ahocevar** [comment]
@petrsloup @klokan Given the current situation, would it be ok for you guys if we switch to MapTiler Cloud raster maps as Bing replacement for the examples in this pull request?

**Comment by klokan** [comment]
Yes. We are very happy to provide the satellite layer for demonstration purposes at openlayers.org domain with proper attribution links in place. Please use the previously provided key.

**Comment by mike-000** [comment]
> Everything is fine, however `preload.html` sample is also using Bing map.

It uses Aerial with Labels - as does feature-move-animation (and of course bing-maps).  Neither Esri or MapTiler have a single source equivalent for that.   But removing Bing from 6 examples will free up API key quota for the remaining 3 examples.

**Comment by klokan** [comment]
Aerial/Satelite with burned-in labels: https://cloud.maptiler.com/maps/hybrid/
Pure Aerial/Satelite: https://cloud.maptiler.com/tiles/satellite/
BTW we recommend to use 512px tiles / tilgrid (less tile requests=more efficiency).

**Comment by tschaub** [comment]
Thanks @klokan!

**Comment by mike-000** [comment]
@klokan Is pure satellite available as 512px tiles?

**Comment by bartvde** [comment]
> Good point. @bartvde, I think you did the work on Esri sources back then. Do you remember if there was any agreement with Esri, or if the terms of use allow us to use these layers?

I don't think there was any specific agreement, I am not sure if the terms of use have changed since then

**Comment by bartvde** [comment]
@mpriour do you maybe know more about the Esri terms of use?

**Comment by emcastro** [comment]
> @mpriour do you maybe know more about the Esri terms of use?

Not formally forbiden, not formally authorized.

Summary:
http://downloads2.esri.com/ArcGISOnline/docs/tou_summary.pdf

Complete terms of use:
https://www.esri.com/en-us/legal/terms/full-master-agreement

Involved ressources:
* World Street Map: https://www.arcgis.com/home/item.html?id=3b93337983e9436f8db950e38a8629af
* World Imagery: https://www.arcgis.com/home/item.html?id=10df2279f9684e4a9f6a7f08febac2a9

**Pull request merged**
