### PR TITLE
Fix Region growing example

### PR DESCRIPTION
**Pull request by drnextgis**
Fix issue https://github.com/openlayers/ol3/issues/5075

### CODE REVIEW

**Comment by fredj** [comment]
@tschaub can you please take a look at this? thanks

**Comment by tschaub** [comment]
Thanks for the effort here.  I'm concerned that there is a bug lurking though.  I haven't dug yet, but wouldn't you expect `map.getPixelFromCoordinate(coordinate)` to provide a useful pixel coordinate even when rotated?

**Comment by drnextgis** [comment]
Yes, fetching useful pixel coordinate even when rotated is expected behavior of `getPixelFromCoordinate`. Current behavior is not obvious and user have to recalculate pixels manually.

**Comment by simonseyock** [comment]
I am looking into this now. A proposed solution is a `getRenderedPixelFromCoordinate` at the layer.

**Pull request closed without merging**
