### PR TITLE
GML: remove srsName from linearring

### PR DESCRIPTION
**Pull request by fgravin**
Fixes https://github.com/openlayers/openlayers/issues/11512

Remove `srsName` attribute in GML `linearring` serializers.

Reference: http://www.datypic.com/sc/niem21/e-gml32_LinearRing.html

### CODE REVIEW

**Comment by mprins** [comment]
this is just wrong, linearring being derived from abstractgeometry it can have srsname, 
see https://github.com/openlayers/openlayers/issues/11512#issuecomment-686620502

**Review by ahocevar — COMMENTED** [review]
@fgravin I'd be curious to hear what this pull request fixes. `srsName` is an optional attribute (see schema links posted by @mprins in #11512) and should not do any harm if present.

**Comment by tschaub** [comment]
As mentioned on the other ticket, a linear ring is not a geometry.  A polygon is (and can contain a linear ring in its exterior or interior elements).

**Review by ahocevar — CHANGES_REQUESTED** [review]
In order to accept this pull request, it would need to be changed so when serializing a `LinearRing` that stands on its own (i.e. from an `ol/geom/LinearRing`), it should still have a `srsName` attribute. For the rings of a polygon, the `srsName` attribute can be removed.

**Pull request closed without merging**
