### PR TITLE
Adds option to View for using larger resolution value when clamping #10586

### PR DESCRIPTION
**Pull request by jeremy-smith-maco**
Adds functionality for #10586

### CODE REVIEW

**Comment by mike-000** [comment]
The proposed description in a API 

> If true, the constrained resolution values will use the larger value to do so.

wouldn't be easily understood by a user

Looking at you code I think the effect could be better described as

> If true, the extent constraint can be exceeded along one but not both axes

and something like `constrainOneAxis` would be a more understandable option name

**Comment by jeremy-smith-maco** [comment]
Wasn't sure how to best explain it. I have updated it. Hopefully it is more concise.

**Comment by tschaub** [comment]
This looks like nice functionality.  What do you think about calling the option `showFullExtent`?  I’m trying to think how someone might find the option if they don’t know it exists.  And maybe the documentation could be something like this:

Allow the view to be zoomed out to show the full configured extent.  By default, when a view is configured with an extent, users will not be able to zoom out so the viewport exceeds the extent in either dimension.  This means the full extent may not be visible if the viewport is taller or wider than the aspect ratio of the configured extent.  If `showFullExtent` is true, the user will be able to zoom out so that the viewport exceeds the height or width of the configured extent, but not both, allowing the full extent to be shown.

**Comment by jeremy-smith-maco** [comment]
Makes more sense. Updated.

**Comment by ahocevar** [comment]
Thanks @tschaub for your valuable input. I was hesitant to review this pull request because neither the option name nor the documentation made sense to me. Now everything should be clear. Thanks @jeremy-smith-maco for your continued effort on this.

**Pull request merged**
