### PR TITLE
Cast to ol.VectorTile so getReplayState is valid

### PR DESCRIPTION
**Pull request by ahocevar**
Addresses https://github.com/openlayers/ol3/commit/c1b16217f28f50d4585a2ffda603b83042cbd2cc#commitcomment-18885235.

### CODE REVIEW

**Comment by ahocevar** [comment]
@schmidtk I'm wondering how your setup differs from ours, because as far as I know, we have all type checking enabled for the Closure Compiler, and did not run into an issue here.

**Comment by ahocevar** [comment]
Maybe related to #5642.

**Comment by ahocevar** [comment]
@gberaudo, didn't you change some compiler settings a while ago that made it smarter detecting types?

**Comment by ahocevar** [comment]
I'll be away for a week now, so if this needs to be merged or closed, please go ahead @openlayers/core.

**Comment by gberaudo** [comment]
I experimented switching to the [new type inference](https://github.com/google/closure-compiler/wiki/Using-NTI-(new-type-inference)) but I got lots of errors and decided to suspend the experiment until this matures in the compiler. So nothing was merged.

@ahocevar, if a cast is needed, it is better to do it early on the `tilesToDraw` variable (as an `Array<ol.VectorTile>`).

**Comment by schmidtk** [comment]
@ahocevar I'm out of the office for about a week as well so I don't have access to our compiler options, but I can provide them when I get back if you'd like.

I also had issues with the new typedefs file. Our build was providing the file to the compiler, but I got a pile of unknown type errors for references to those types. I think syncing back up with the latest OL3 is on tap in our next sprint, so I'll have more information then.

**Comment by pgiraud** [comment]
@ahocevar It needs to be done in https://github.com/ahocevar/ol3/blob/c4ee4e2359a55330b7c0871141782008124277dc/src/ol/renderer/canvas/vectortilelayer.js#L293 as well.

**Comment by ahocevar** [comment]
I'd still like to hear about circumstances when the compiler complains about this, because it does not when building OpenLayers.

**Comment by pgiraud** [comment]
Here's a way to reproduce the issue.
Follow the "[Compile application](http://openlayers.org/en/latest/doc/tutorials/closure.html)" tutorial. Fix the issue with bad annotation types by adding "node_modules/openlayers/src/ol/typedefs.js" in the "js" section.
Compiling the application + OL3 code seem to work well.
However, adding `manage_closure_dependencies` and setting it to true in the compiler configuration seem to break the compilation.

**Comment by schmidtk** [comment]
We're compiling with `--dependency_mode=strict --entry_point=<root namespace>` which will build the dependency list from provides/requires. Since typedefs.js doesn't have a provide, it doesn't get included and types are reported as unknown.

**Comment by ahocevar** [comment]
I don't think this pull request is relevant any more.

**Comment by fredj** [comment]
> I don't think this pull request is relevant any more.
@ahocevar and what about #5927

**Pull request closed without merging**
