### PR TITLE
Add a constrainCenter option to ol.View

### PR DESCRIPTION
**Pull request by elemoine**
IThis is unfinished work. Probably needs discussions, tests and a better example. I'm just creating this PR for people to be able track progress on this. See [this post](https://groups.google.com/d/msg/ol3-dev/w7gLnpMr2nY/jRjqENSVhQUJ) and [this post](https://groups.google.com/d/msg/ol3-dev/QAdniHP-lsE/j_CHoswmhfQJ) on the mailing list for related discussions.

EDIT: and [this question](http://stackoverflow.com/q/27200086/1064422) on StackOverflow.

### CODE REVIEW

**Comment by tremby** [comment]
For anyone waiting on this, I posted a temporary solution of sorts to the Stackoverflow question mentioned in the OP.

**Comment by Honigbaum** [comment]
Is there any chance that the pull request gets merged in one of the next versions?

**Comment by tschaub** [comment]
@elemoine can you resurrect this (rebase, resolve conflicts, and merge if you like it)?

**Comment by elemoine** [comment]
I'll try to go back to this for the next release.

**Comment by ahocevar** [comment]
@elemoine, just a gentle reminder that you wanted to go back to this. If you don't have much time, it'd also be nice if you could just update what's here to remove conflicts. Your remaining concerns could be addressed in a separate pull request.

**Comment by elemoine** [comment]
I've just rebased this. But this cannot be merged as-is. The example doesn't work correctly. You'll observe jumps when the view is at `minZoom` and you try to zoom out again (with the mousewheel or the zoom control's minus button).

**Comment by tbarsballe** [comment]
Is this still going anywhere? 
I recently build a custom restricted extent implementation for an OL3 project I was working on, and was wondering if I would be better off polishing it up and contribuiting it seperately?
It seems like restricted extent is one portion of this PR, but not the main goal.

**Comment by ahocevar** [comment]
@tbarsballe Thanks for asking. Currently, the `extent` option on `ol.View` creates a center constraint. This means that you will be able to pan the map to any place where the center is within the specified extent. If we had an additional boolean `restrictExtent` (or whatever a good name for it would be) option, the configured `extent` could be used to restrict panning and zooming to places where the whole viewport is within that extent. Is this along the lines of what you had in mind with your implementation?

I think the challenge with implementing this properly is restricting the zoom properly, and creating a nice user experience when zooming out an area that will not be fully within the constrained extent any more after zooming out.

That said, we'd gladly accept a contribution that is able to address this properly.

**Comment by tremby** [comment]
It seems to me that things would get very tricky as soon as the map is rotated! But if it can be made to work, it'd certainly be a very useful feature.

**Comment by ahocevar** [comment]
Yes, rotation will be equally challenging as the zoom user experience I outlined above.

**Comment by tbarsballe** [comment]
@ahocevar Yes, that was aproximately what I had in mind, although I was thinking of restrictedExtent as its own ol.Extent value, not neccessarily the same as the extent of the view. My solution for zoom was to have a custom zoom constraint that does not allow zooming outside of the bounds of the extent.

One requirement for both these constraints is that the view needs to be aware of the element it is getting drawn in (in the same way that Map has a target parameter) in order to determine the size and aspect ratio of the actual view. 

I had not considered how rotation would act with this, and don't really have a good solution. I feel like rotation would have to be mutually exclusive with restricted extent.

**Comment by ahocevar** [comment]
@tbarsballe:

> I was thinking of restrictedExtent as its own ol.Extent value, not neccessarily the same as the extent of the view.

Where would it make sense to keep those separate? Or in other words: what would be a use case for having a larger `restrictedExtent` than `extent`? Because in the opposite case, when `restrictedExtent` is smaller than `extent`, you would never reach the bounds of `extent`.

> My solution for zoom was to have a custom zoom constraint that does not allow zooming outside of the bounds of the extent.

That sounds good. And even better if the `restrictExtent` option can influence the default zoom constraint so it does this.

> One requirement for both these constraints is that the view needs to be aware of the element it is getting drawn in (in the same way that Map has a target parameter) in order to determine the size and aspect ratio of the actual view.

To constrain center, resolution and rotation, `ol.View#constrain*` functions are called by `ol.interaction.Interaction` instances, which know about the map and can use `ol.Map#getSize` to get the size of the view. So these `constrain*` functions could be called with the size as additional argument.

> I had not considered how rotation would act with this, and don't really have a good solution. I feel like rotation would have to be mutually exclusive with restricted extent.

It could work similar to the way you handle zoom - with a rotation constraint that only allows rotations where the viewport wouldn't exceed the restricted extent.

**Comment by samimussbach** [comment]
Any news on this issue? Unfortunately I am not able to help with code.

**Comment by 0xBADDCAFE** [comment]
This PR works like this example (on ol2)?

http://dev.openlayers.org/examples/restricted-extent.html

And I check this issue https://github.com/openlayers/ol3/issues/1243 but it not correct because above example (`restrictedExtent` in ol2) restrict drag area but in this issue (`extent` in ol3) couldn't restrict drag area correctly. I want to restrict drag area.

**Comment by klickagent** [comment]
Any news on this issue yet? Looking forward to this functionality. Thanks a lot!

**Pull request closed without merging**
