### PR TITLE
Check for proj4 in a way that also works in module environments

### PR DESCRIPTION
**Pull request by ahocevar**
This is better than #2330, and it should also address @probins's [concern](https://github.com/openlayers/ol3/pull/2330#issuecomment-48630893).

### CODE REVIEW

**Comment by mokkabonna** [comment]
This still requires proj4 to be in the global namespace even when using module loaders. And since proj4 hides from the scope when using AMD this requires code that uses it to force a leak of proj4 like this: window.proj4 = proj4

Something like this needs to be done:

```
(function (root, factory) {
  if (typeof define === "function" && define.amd) {
    define(['proj4'], factory);
  } else if (typeof exports === "object") {
    //is this for node??, if so use this, if not window.proj4 as well here
    module.exports = factory(require("proj4"));
  } else {
    root.ol = factory(window.proj4);
  }
}(this, function (proj4) {
```

**Comment by ahocevar** [comment]
@mokkabonna Thanks for pointing this out. Would you be able to provide a pull request with this fix?

**Comment by tcoopman** [comment]
@mokkabonna I would love a fix for this!

**Comment by mokkabonna** [comment]
I can put together something yes. Just need to find some time, will put it in my backlog :)

**Pull request merged**
