### PR TITLE
Bring back coverage

### PR DESCRIPTION
**Pull request by marcjansen**
This brings back the coverage reporting we lost in #6953.

Please review.

### CODE REVIEW

**Comment by ahocevar** [comment]
Local coverage with WebGL tests executed:

coverage

**Comment by marcjansen** [comment]
ping @tschaub, tvis PR was not created from a phone!

**Comment by tschaub** [comment]
Thanks for tackling this @marcjansen.

Perhaps we can separate the coverage stuff and WebGL rendering.  For me, rendering tests fail:
```
Chrome 60.0.3112 (Mac OS X 10.12.6) ol.rendering.style.Polygon different types with stroke tests the webgl renderer FAILED
	Error: Uncaught Error: expected 12.5 to be below 1.5 (/Users/tschaub/projects/openlayers-orig/node_modules/expect.js/index.js:102)
Chrome 60.0.3112 (Mac OS X 10.12.6): Executed 1436 of 2801 (1 FAILED) (skipped 3) (0 secs / NaN secs)
```

**Comment by marcjansen** [comment]
will do as suggested, probably later today

**Comment by marcjansen** [comment]
Changed as suggested, I opened #7174 for the WebGL thingy.

**Comment by marcjansen** [comment]
Thanks for the review, Tim.

**Pull request merged**
