### PR TITLE
support fullscreen for bootstrap tooltip

### PR DESCRIPTION
**Pull request by jipexu**
#11369

### CODE REVIEW

**Comment by jipexu** [comment]
please check if the english is correct in the description ...thanks

**Comment by jipexu** [comment]
arghh something wrong i lost the tags ... why ?...

**Comment by ahocevar** [comment]
@jipexu Can you please pay more attention to making sensible commits? Our [pull request guidelines](https://github.com/openlayers/openlayers/blob/main/CONTRIBUTING.md#pull-request-guidelines) should give you an idea. Example: commits like "fix typos" should not be necessary when you have appropriate tooling locally, or run npm run lint before committing changes. You can also rewrite history in your feature branches, e.g. using git commit --amend or git rebase --interactive.

**Comment by jipexu** [comment]
yes sorry  i will try .. i tried this morning to do it but without success .. i still  try to understand more the use of github ...

**Pull request closed without merging**
