### PR TITLE
Export SelectEvent class

### LINKED ISSUE #8699: SelectEvent is unknown type in OL 5.2
How can I call dispatchEvent method and pass an instance of SelectEvent object when SelectEvent is unknown type?

### PR DESCRIPTION
**Pull request by fredj**
Fixes #8699

### CODE REVIEW

**Comment by tschaub** [comment]
Is it clear why an application would need to dispatch this event?

**Comment by fredj** [comment]
ping @zgeorgiev

**Comment by zgeorgiev** [comment]
@fredj Thanks a lot.
@tschaub I have a feature depending on another one and when I click on the first feature I would like to dispatch select event to the second feature. Both features are on different places on the map.

**Comment by ahocevar** [comment]
I'm still not convinced we need this change. @zgeorgiev Can you share your code where you are using this exported event?

**Comment by zgeorgiev** [comment]
@ahocevar unfortunately I cannot share the code but will try to explain my issue. I have a feature for car on the map and feature for the trail of this car. I would like to select the car feature even if I click on the trail feature. My code with older version of OL was in the select event handler of the trail feature I was triggering dispatchEvent select car feature. Now this is not possible, because SelectEvent object is not accessible. I will appreciate if you have a different solution for this case.

**Pull request closed without merging**
