### PR TITLE
Scale interaction

### PR DESCRIPTION
**Pull request by Morgul**
This adds a scale interaction, with examples and unit tests.

I am assuming there will be quite a bit of discussion about this, as it draws handles and there will likely be some desire to change how some of this works.

### CODE REVIEW

**Comment by ul** [comment]
It need to update handles on feature change, e.g. when it is translated. Smth. like this:
```javascript
/**
 * @param {ol.CollectionEvent} evt Event.
 * @private
 */
ol.interaction.Scale.prototype.handleFeatureAdd_ = function(evt) {
  evt.element.on('change', this.updateSketchFeatures_.bind(this));
  this.updateSketchFeatures_();
};


/**
 * @param {ol.CollectionEvent} evt Event.
 * @private
 */
ol.interaction.Scale.prototype.handleFeatureRemove_ = function(evt) {
  evt.element.un('change', this.updateSketchFeatures_.bind(this));
  this.updateSketchFeatures_();
};
```

**Comment by Morgul** [comment]
@ul That definitely seems like a worth-while change.

**Comment by mkv123** [comment]
Any update on the status of this? I'm looking for a way to scale and rotate (transform) some geojson data on top of a map background to basically fix alignment issues of the data. I'm using ol3-rotate-feature which is working well but I'm really struggling to find a nice interaction implementation for scaling.

**Comment by ahocevar** [comment]
This is a good quality pull request. @Morgul, would you be able to update it so it can be merged? This would include rebasing against current master, and replacing the use of `goog.*` functions with the equivalents we have introduced since.

**Comment by kevinp1335** [comment]
It's been over a year now. Will anything become of this? I could really use this right now...

**Comment by Morgul** [comment]
@kevinp1335 I haven't had time to try and get this rebased. If you need this now, you can feel free to take my branch and rebase, or just use it as a guide for a new PR.

**Comment by tschaub** [comment]
If the remaining work and conflict resolution can be completed before the upcoming 4.6 release, please reopen this pull request.  After 4.6, we will be transforming the sources to ES modules, and if we want to pick up this effort, it may be easier to create the changes from scratch.

**Pull request closed without merging**
