### PR TITLE
Add validation to prevent incorrect calculations when handling undefined values in the updateElement_ method

### LINKED ISSUE #15852: Control ScaleLine - Error Cannot read properties of undefined (reading 'toFixed')
The error you're encountering, TypeError: Cannot read properties of undefined (reading 'toFixed'), indicates that the count variable is undefined when the code tries to call the toFixed method on it.

Error:
ScaleLine.js:352 Uncaught TypeError: Cannot read properties of undefined (reading 'toFixed')
    at ScaleLine.updateElement_ (ScaleLine.js:352:15)
    at ScaleLine.render (ScaleLine.js:487:10)
    at Map.dispatchEvent (Target.js:119:11)
    at Map.renderFrame_ (Map.js:1633:10)
    at Map.animationDelay_ (Map.js:1449:10)

Code:
  const html = this.scaleBar_
      ? this.createScaleBar(width, count, suffix)
      : count.toFixed(decimalCount < 0 ? -decimalCount : 0) + ' ' + suffix;

    if (this.renderedHTML_ != html) {
      this.innerElement_.innerHTML = html;
      this.renderedHTML_ = html;
    }
    
 Code implements Map:
  const scaleControl = new ScaleLine({
        units: "metric",
        bar: false,
        text: true,
        minWidth: 150,
        maxWidth: 150,
      });
      
       const mapInstance = new Map({
        controls: [overviewMapControl, scaleControl],
        target: mapRef.current!,
        layers: [
          ...dataLayers,
        ],
        view: new View({
          projection: "EPSG:4326",
          center: [-38.2999, -12.6153],
          zoom: 16,
        }),
      });

It is necessary to check the variable to avoid the error.

### PR DESCRIPTION
**Pull request by edsonmsj**
Add validation to prevent incorrect calculations when handling undefined values in the updateElement_ method.

This PR adds a validation to the updateElement_ method to handle cases where values may be undefined, preventing incorrect calculations from occurring. This ensures the method behaves more robustly when encountering unexpected input.

Fixes #15852: The validation ensures that calculations will not be incorrect when undefined values are encountered in the method.

### CODE REVIEW

**Comment by ahocevar** [comment]
Looks like an easier fix would be to initialize `previousCount` with `0`.

**Comment by edsonmsj** [comment]
The check after calculation ensures that no unexpected values are passed on.

**Comment by ahocevar** [comment]
I'm a big fan of knowing what's going on, and to avoid having to deal with unexpected values. Where except from the uninitialized `previousCount` variable would an `undefined` value come from?

**Comment by edsonmsj** [comment]
I focused on solving the specific toFixed bug here to avoid any unexpected behavior. Initializing the previousCount variable would also work, but since this is my first contribution and I'm still familiarizing myself with the code, I wanted to make sure that other variables like pointResolution don't introduce unexpected values. That said, I'd be happy to submit a new pull request with your suggested solution if needed.

**Comment by ahocevar** [comment]
No need to create a new pull request, you can change the implementation in this pull request by using `git commit --amend` and `git push --force`.

**Review by ahocevar — APPROVED** [review]
Thanks, @edsonmsj

**Pull request merged**
