### PR TITLE
Animated GIF example

### PR DESCRIPTION
**Pull request by mike-000**
Adds an animated GIF example similar to that in https://github.com/openlayers/openlayers/issues/11412#issuecomment-685783562 using a different icon and Gifler from CDN to avoid a dependency.

### CODE REVIEW

**Comment by marcjansen** [comment]
Cool thanks, @mike-000.

For reference, here is [the online example](https://deploy-preview-11565--ol-site.netlify.app/examples/animated-gif.html).

Where is ghe gif coming from? Did you create it from scratch?

The gif is huge on my mobile, can we somehow scale it?

Would be awesome if you could enhance this a bit and please answer the question wrt the source of the gif.

**Comment by mike-000** [comment]
The size is much as I expected, so it allows the hit detection to be easily seen with pointermove, but I can reduce it to be more mobile friendly.  It is based on https://webqoe.telecom-paristech.fr/ although watermarks indicate that originated from PicMix where at least 4 people claim to be authors.  There are also many monochrome versions (without watermarks) online so I converted it to single color using https://ezgif.com/

**Comment by marcjansen** [comment]
Hm. Any chance we can include a CC-BY globe? And simply attribute it in the text of the example?

I'd much prefer that.

Thanks for your work, and I hope you understand I only want a clearly usable image to be included in the library.

The size issue is really not that important.

**Comment by marcjansen** [comment]
Cool thanks again.

**Review by marcjansen — APPROVED** [review]

**Pull request merged**
