### PR TITLE
Test reorganization

### PR DESCRIPTION
**Pull request by tschaub**
This organizes the `rendering` and `browser` tests under the `test` directory, making room for `node` tests.

Since the diff here is pretty unbearable, here is what the two commits do:
 * Organize tests
   * moves things from `test` to `test/browser`
   * moves things from `rendering` to `test/rendering`
   * updates all import paths to point to the source
   * removes the unused `webpack.resolve.alias` from the `karma.config.js`
   * removes the `/rendering/` proxy from the `karma.config.js`
 * Remove unused rendering assertion from browser tests
   * removes pixelmatch and the associated assertions from the browser test extensions

### CODE REVIEW

**Comment by ahocevar** [comment]
I looked into the issue with the two failing rendering tests. It seems that Puppeteer fails silently on those, because the resulting image is empty. The same happens for me locally. There are no errors, so I'm not sure how to investigate this further.

**Comment by tschaub** [comment]
Thanks for looking into it.  Other tests were failing initially due to broken links when I moved the rendering dir (earthquake data was linked from examples).  I'll debug the remaining ones.

(the map is also blank when you load the test cases in a regular browser with `--interactive` - so not a Puppeteer issue)

**Comment by tschaub** [comment]
That was a puzzle!  My overeager deleter got me in trouble again.  Looks like `ol-mapbox-style` requires the `ol` alias that I had removed from the webpack config.  That is restored in d72368667d3f6ecd72891dec5041ddeb851b4c08.

**Comment by ahocevar** [comment]
Ok, that makes sense. Since `ol-mapbox-style` has `ol` as peer dependency and imports modules from `ol`, we need that alias. Thanks for the investigation and the fix!

**Review by ahocevar — APPROVED** [review]

**Comment by marcjansen** [comment]
888 files changed, wow. Thanks

**Pull request merged**
