### PR TITLE
Continue supporting IE11 in examples and legacy build

### PR DESCRIPTION
**Pull request by ahocevar**
This pull request modifies the webpack configurations for the example and legacy build to transpile for IE11, including all dependencies. Because geotiff brings in dependencies that publish code with async/await, we can no longer use buble for transpiling. So this pull request also gets rid of the buble dev dependency, and uses babel instead, which we have as dependency already for the worker build.

This pull request fixes one of the problems described in #12730.

### CODE REVIEW

**Comment by ahocevar** [comment]
@mike-000, can you please test the examples and the legacy build from this pull request in IE11? I don't have access to such an old browser.

**Comment by mike-000** [comment]
Do you have a download link available?  The deploy preview examples do not work in any browser.

**Comment by ahocevar** [comment]
@mike-000 The examples preview should work again now, and I added a legacy build test map to the preview entry page (https://deploy-preview-12734--ol-site.netlify.app).

**Comment by mike-000** [comment]
Examples and legacy build working in both Chrome and IE (when copied and polyfills used)

**Comment by ahocevar** [comment]
@mike-000 I added the polyfills to https://deploy-preview-12734--ol-site.netlify.app. Can you please test again if it works out of the box now in IE?

**Comment by ahocevar** [comment]
I just found a rusty Windows virtual machine with Internet Explorer on it. I could verify that both the legacy build preview and the preview examples work fine there. So this is now ready for review.

**Comment by mike-000** [comment]
Yes, it is working.  The new WebGL examples have highlighted some more polyfills are needed, e.g. Array.from()

**Comment by ahocevar** [comment]
Thanks for testing, @mike-000.

> Yes, it is working. The new WebGL examples have highlighted some more polyfills are needed, e.g. Array.from()

I'll leave that to you to document/add those, if that's ok for you. Thanks in advance!

**Review by tschaub — APPROVED** [review]

**Pull request merged**
