### PR TITLE
Move olx.layer.* to ol/layer/*

### PR DESCRIPTION
**Pull request by romanzoller**
Continuation of #8016, move the remaining `ol.layer.*` externs to `ol/layer/*`, see #7947 for an overview of this ongoing work.

Last commit: Fix setting of the `useInterimTilesOnError` in `ol/layer/VectorTile`.

### Notes

All default values were moved from documentation text to the JSDoc syntax `[opacity=1]`, which will be supported for documentation generation according to https://github.com/openlayers/openlayers/issues/7838.

Sometimes this would lead to minor changes in the documentation text, e.g.

> Preload. Load low-resolution tiles up to `preload` levels. By default `preload` is `0`, which means no preloading.

was transformed to

> Preload. Load low-resolution tiles up to `preload` levels. `0` means no preloading.

### Questions

Other things I stumbled over while working on this, not necessarily to be addressed in this PR, but I would by happy to get some feedback from someone more familiar with ol:

- The `options` Object is optional everywhere except for `ol/layer/Base` and `ol/layer/Layer`, but neither of them have any mandatory options-attributes. Should the `options` Object be optional everywhere?
- Is there a preferred order for attributes in the `Options` typedefs? I was currently following more or less the existing order and generally putting all inherited options first for easy copy-pasting.
- Minor: Is there a preference for putting one or two spaces after periods in documentation text?

### CODE REVIEW

**Comment by romanzoller** [comment]
Closing and re-opening to trigger new CI build, tests were passing locally...

**Comment by ahocevar** [comment]
@romanzoller, answering your other questions:

> * The options Object is optional everywhere except for ol/layer/Base and ol/layer/Layer, but neither of them have any mandatory options-attributes. Should the options Object be optional everywhere?

Good question. Since both `layer/Base` and `layer/Layer` are base classes that are not used for anything but extending them, it does not matter. For any class that can be constructed in an application, `options` should be optional when an instance can be created without any option.

> * Is there a preferred order for attributes in the Options typedefs? I was currently following more or less the existing order and generally putting all inherited options first for easy copy-pasting.

We should sort options by importance, i.e. those that are mandatory or recommended first, and those for special configuration cases last. This does not need to happen as part of this current effort, but should be done eventually.

**Comment by ahocevar** [comment]
Thanks fo working on this, and for the good summary of the changes you made. I'm reviewing in detail now.

**Comment by romanzoller** [comment]
Thanks for the quick review and for the clarifications @marcjansen and @ahocevar!

**Pull request merged**
