### PR TITLE
Use global scope for addEventListener

### PR DESCRIPTION
**Pull request by bartvde**
Same as #9601 but for v5.3.x

### CODE REVIEW

**Comment by ahocevar** [comment]
Ok sorry for killing your first pull request on this, I hadn’t seen it was against 5.x. The failing test is caused by a puppeteer update. I think using v1.10.0 should fix it.

**Comment by bartvde** [comment]
I will change back to ```window``` @tschaub it's what I originally had ;-)
@ahocevar agreed?

**Comment by bartvde** [comment]
PR updated @tschaub

**Comment by bartvde** [comment]
I'm unsure what is up with the CI @ahocevar for the v5.3.x branch. I tried adding pupeteer as a dev dependency but the result is the same

**Comment by tschaub** [comment]
We didn’t use Puppeteer in the 5.x series, right?  I think the Karma confit sets the browser to Chrome in CI (only reviewing on a small device though).

**Comment by tschaub** [comment]
@bartvde the failure I see is about precision in an assertion in the scaleline tests.  I assume there is a change in floating point math in a Chrome update.  To get this passing, I would lower the precision of the equality check in the scaleline test.

**Comment by bartvde** [comment]
@tschaub correct, I pushed a fix for the test. Let me know if this would also make sense on master or not

**Comment by ahocevar** [comment]
@bartvde:

> Let me know if this would also make sense on master or not

In master, this was already fixed with #9305.

**Comment by bartvde** [comment]
ah right, that makes sense @ahocevar

**Pull request merged**
