### PR TITLE
Add missing externs to custom builds examples

### PR DESCRIPTION
**Pull request by Toilal**
I need to add those externs entry to make both example builds pass.

### CODE REVIEW

**Comment by Toilal** [comment]
What's wrong with the build ?

**Comment by fredj** [comment]
Not related to you changes, travis hiccup.
I've restarted the build

**Comment by fredj** [comment]
thanks @Toilal

**Comment by ahocevar** [comment]
@Toilal, it looks like we do not have a CLA from you yet. Can you please [submit one](https://github.com/openlayers/cla)? Thanks.

**Pull request merged**
