### PR TITLE
Allow WebGL tile layer style to be updated

### LINKED ISSUE #13019: WebGLTile Layer missing `setStyle` method
Currently, there is no way to replace the visualization of a `WebGLTile` Layer object, it is only possible to completely remove the layer and insert a new one. There are setters for other visualization properties (variables and source).

One use-case for this is letting users define the visualization dynamically, without throwing away the already downloaded raster data (e.g: in case of GeoTIFFs).

I'm aware that changing the style is more work (rebuilding shaders, re-binding buffers and textures, etc) but I think this function would be quite beneficial.

### PR DESCRIPTION
**Pull request by tschaub**
This adds a `layer.setStyle()` method to WebGL tile layers.  The `layer.updateStyleVariables()` is the efficient way to re-render a WebGL tile layer based on changes in the application state.  In cases where it is desirable to change more of the style than can be represented in variables, a `layer.setStyle()` method can be useful.

I'd like to add additional documentation around this so people know when *not* to call `layer.setStyle()`.  We load all of the source data associated with a layer even if only a portion of it (not all bands) are used in a style.  So it will likely lead to a bad user experience if people try to configure layers with sources that load many more bands than are needed for any one single style and then provide the user with an option to change the style.

I'd also like to add a compelling example that demonstrates the use of this, but all the publicly accessible Sentinel COGs I've seen are bulky and slow to load when adding too many bands.  I'm open to other suggestions if anybody has pointers to efficiently optimized COGs.

Fixes #13019.

### CODE REVIEW

**Comment by constantinius** [comment]
@tschaub You could add these cloudless mosaics (https://s2downloads.eox.at/demo/EOxCloudless/2020/rgbnir/) in the examples. They only have the RGBNir bands and are pretiled. We could do true color (RGB), false color (NirRG) and NDVI visualizations.

Would it somehow be feasible to update the source when a new band is requested? So that not all the bands have to be re-fetched, only new data. e.g when switching from true color to false color: only the Nir band has to be requested, as Red and Green are already available.

**Comment by Schpidi** [comment]
Using this 16bit data as demo it would be nice to allow adjusting the strech to 8bit.

**Comment by tschaub** [comment]
I've added [an example](https://deploy-preview-13020--ol-site.netlify.app/examples/cog-style.html) using one of the 16-bit GeoTIFFs at https://s2downloads.eox.at/demo/EOxCloudless/2020/rgbnir/.  Switching from the true- or false-color composite to NDVI demonstrates the purpose of the `layer.setStyle()` method (just changing from the true- to false-color composite could be done with `layer.updateStyleVariables()`).

I think the example would be a bit nicer using a GeoTIFF with built in overviews.  Any chance anyone has an equally nice (4 band) one of those lying around?

**Comment by Schpidi** [comment]
Very nice! Could the stretch be adjusted using this method as well?

> I think the example would be a bit nicer using a GeoTIFF with built in overviews. Any chance anyone has an equally nice (4 band) one of those lying around?

Sure, I added a single GeoTIFF holding the same data as the pyramid: https://s2downloads.eox.at/demo/EOxCloudless/2020/rgbnir/s2cloudless2020-16bits_sinlge-file_z0-4.tif

**Comment by tschaub** [comment]
> Could the stretch be adjusted using this method as well?

I think that a contrast stretch is better handled with `layer.updateStyleVariables()`.  See the style expression used in this example: https://openlayers.org/en/latest/examples/numpytile.html.  That stretches each channel with a single min and max.  But the user could also control min/max values per channel.

One limitation of style variables right now is that the `band` value must be a numeric literal and cannot come from a style variable.  This is something that would be nice to change.



> Sure, I added a single GeoTIFF holding the same data as the pyramid: https://s2downloads.eox.at/demo/EOxCloudless/2020/rgbnir/s2cloudless2020-16bits_sinlge-file_z0-4.tif

Thanks!  I updated the example to use that.

**Review by ahocevar — APPROVED** [review]
Very slick. Thanks, @tschaub!

**Comment by tschaub** [comment]
> One limitation of style variables right now is that the `band` value must be a numeric literal and cannot come from a style variable. This is something that would be nice to change.

#13083 adds support passing expressions to the `band` operator.

**Pull request merged**
