### PR TITLE
Handle rotated, skewed or flipped GeoTIFF tile grids

### LINKED ISSUE #15294: GeoTIFF layers do not support TIFFs with GeoTransform/rotation
**Describe the bug**
When trying to add a certain GeoTIFF to an OpenLayers map, it renders in an incorrect location. The GeoTIFF in question is https://unnerving-monsoon.ams3.cdn.digitaloceanspaces.com/Georgia/2023-10-30-06-47-55_UMBRA-04.tif. This is not reproduced in QGIS or other COG tools.

**To Reproduce**
1. Go to https://www.cogeo.org/map/ and use the URL above. The TIFF renders correctly, using Marblecutter.
2. Go to https://geotiffjs.github.io/cog-explorer/ and use the URL above. The TIFF renders in an incorrect location, using OpenLayers.

It can also be reproduced by adding the following source to an OpenLayers map:

```
const source = new GeoTIFF({
  normalize: true,
  bands: [1, 1, 1],
  sources: [
    {
      url: 'https://unnerving-monsoon.ams3.cdn.digitaloceanspaces.com/Georgia/2023-10-30-06-47-55_UMBRA-04.tif',
      bands: [1, 1, 1],
      max: 300,
    },
  ],
});
```

**Expected behavior**
The projection and extent is read and interpreted correctly.

### LINKED ISSUE #15370: GeoTIFF rotation
Hello,
I'm trying to load a TIF into OpenLayers but it doesn't seem to be rotating the image.
In QGIS it is displayed correctly.
The URL is: http://ftpcdd.cnig.es/Vuelos_2015_2016/Vuelos_2015/Baleares/1.VF/1.08_PNOA_L6_2015_BAL_25cm_VF_img8c_rgb_hu31/h50_0697_fot_002-0015.tif
The projection is EPSG:25831.

Example:
const sources = [new GeoTIFF({
   convertToRGB: 'auto',
   sources: [{
     url: 'https://ftpcdd.cnig.es/Vuelos_2022/Vuelos_2022/extremadura_2022/Sur/01.VF/01.08_PNOA_2022_EXT_S_22cm_VF_img8c_rgb_hu29/h50_0752_fot_02-3221_cog.tif',
   }, ],
})];

const layer = new TileLayer({
   sources: sources,
});

I attach a screenshot of how it is displayed in QGIS and OpenLayers.

all the best
QGIS
Ol

### LINKED ISSUE #15428: error if GeoTiffs origin is set to the lower left corner
**Describe the bug**
I create several GeoTiffs in python, where the origin was set to the lower left corner. The result in OpenLayers was, that all my cells had 0 as value.
When I retranspose my GeoTiff, so that the upper left corner is the origin, all is represented as expected.

**To Reproduce**
1. Download the test setup with a given GeoTiff: [tif_test.zip](https://github.com/openlayers/openlayers/files/13672169/tif_test.zip)
3. extract the content an cd into th directory
4. Install the npm packages: `npm i`
5. Start the vite server `npm start`
6. open a Browser and see the black image. If you open the console and click on a pixel, you will see the value

**Expected behavior**
The tif_layer should show data between 10-360 in greyscale, no matter how the origin is defined. At least as long as the pixel size is then set to (1,1) and not (1,-1)

### PR DESCRIPTION
**Pull request by mike-000**
Fixes #15294
Fixes #15370
Fixes #15428

Replaces #15402

An update to `getTileCoordForTileUrlFunction` was needed to use the correct grid and fix the issue in https://github.com/openlayers/openlayers/pull/15402#issuecomment-2197354410.  I made this specific to `ol/source/DataTile` but it might be possible to apply the change to `ol/source/Tile` if other tile sources are compatible.

### CODE REVIEW

**Review by ahocevar — CHANGES_REQUESTED** [review]

**Comment by mike-000** [comment]
Browser tests are failing because the source does not have a tile grid, which is now required if a view projection is not specified in `getTileCoordForTileUrlFunction`.  In real conditions is it ever possible for a tile source to not have a tile grid?

**Comment by ahocevar** [comment]
If a tile source does not have a tile grid, `ol/tilegrid#getForProjection()` should be used. This can be seen in the `getTileGridForProjection(projection)` methods of the respective TileSource classes.

**Comment by mike-000** [comment]
> If a tile source does not have a tile grid, `ol/tilegrid#getForProjection()` should be used. This can be seen in the `getTileGridForProjection(projection)` methods of the respective TileSource classes.

While a GeoTIFF source should always have a tile grid I can see it would be possible for a DataTile source to not have one, and as a `transformMatrix` will cause reprojection I have also updated `getReprojTile_` to allow for that.  There is currently no API method to set a `transformMatrix` but it might be useful for debug tiles.

**Comment by mike-000** [comment]
Also updated rendering test to show ModelTransformation can work in COG without a projection, which would not have been possible in #15402.

**Pull request closed without merging**
