### PR TITLE
Update Google KML icon anchors and correct icon scaling

### LINKED ISSUE #12670: KML Symbol Alignment/Placement/Size
I believe there is a bug with the anchor point for some symbols when displaying a KML layer.

I'm using the latest examples, specifically this one:
https://openlayers.org/en/latest/examples/drag-and-drop-custom-kmz.html

Dragging the attached kml file into that example, I can see that point symbols seem to be anchored at the center-bottom.
This is mostly visible at the two star symbols that should be at the center point of the two red circles.

image

I've attached a screen clipping from Google Earth to show how it is supposed to look. 
image

Further, the point symbols seem to be much larger in the example than how they are displayed in Google Earth.

[20180910_Sonar-Pool27.zip](https://github.com/openlayers/openlayers/files/7069077/20180910_Sonar-Pool27.zip)

### PR DESCRIPTION
**Pull request by mike-000**
Fixes #12670

Use the hotspots listed in https://kml4earth.appspot.com/icons.html#notes as the default anchors for Google icons.

Add `resizeScaleFunction` option to `ol/Style/Icon` to normalize a KML icon images to 32 pixels as described in https://groups.google.com/g/google-earth-browser-plugin/c/bj_9poNvB2A and https://stackoverflow.com/a/22569590/10118270. Replace `DEFAULT_IMAGE_SCALE_MULTIPLIER` in `ol/format/KML` with a `resizeScaleFunction`.  Apply the resize scale in renderers.

### CODE REVIEW

**Review by ahocevar — COMMENTED** [review]
Please, not another `Icon` style option. The API is confusing enough already. Why not create a style function instead of a static style for KML styles?

**Comment by mike-000** [comment]
I don't see how that would help, there would still be the problem that we won't know the final OpenLayers scale until the image has loaded, and `writeFeatures` needs to know the KML scale, not the OpenLayers scale regardless of whether it has loaded.  Specifying the `resizeScaleFunction` from ol/format/KML effectively makes the OpenLayers scale always the same as the KML scale behind the scenes.  Thinking about it more it should be possible to `import {resizeScaleFunction} from ol/format/KML` when creating styles intended for `writeFeatures` (similar to the predefined geometry functions for Draw).

**Comment by mike-000** [comment]
I have replaced the option with a non-API setter.  It should be noted that `.writeFeatures()` will not be able calculate the correct KML scale unless one of the following is true:

- the style was created by `.readFeatures()`
- the image has been rendered
- the `.load()` method has been called and the image state has changed to `READY`
- `size` or `imgSize` were specified in the constructor
- the `.setResizeScaleFunction()` method has been called (in which case it and the `resizeScaleFunction` export should be included in the API)

If the icon size is unknown a default of [64, 64] is assumed and an OpenLayers scale of 1 will become a KML scale of 2.

**Comment by ahocevar** [comment]
I think this is still more complicated than it needs to be. To simplify this, the `KML` format could prefetch all required icon images and asynchronously call `setStyle()` on the respective features. That way the image size is known, and the scale of the `Icon` style can be calculated. Calling `setStyle()` will also trigger a re-render when the source was already rendered with the default styles.

**Pull request closed without merging**
