### PR TITLE
Initial work to add filter function support for IsLike

### PR DESCRIPTION
**Pull request by glenselle**
This PR is first take on the work needed to make https://github.com/openlayers/openlayers/issues/10823 possible. In order to add support for this internally on our project we created a new WFS subclass which made these changes. I would like to make the check when it writes the filter more robust and also add tests.

### CODE REVIEW

**Comment by glenselle** [comment]
It appears taking this approach is going to be really messy with Typescript enforcing types. And probably error-prone anyway? Is there another design pattern that would be better suited here? Also, our focus (as described in the linked issue) was on `IsLike` -- but I imagine `Function` will be used with other operators.

**Comment by tschaub** [comment]
#10862 brought in some new formatting rules that will require a small change to your commit.  I've pushed a rebased, reformatted version of your commit in f988fc42a9b9b3617015e396df6a21f834e21a68.  You can either do the rebase and reformatting yourself or use this commit.

If you want to rebase and reformat yourself, you can do something like this:
```
git pull --rebase openlayers master
npm run lint -- --fix
```

If you want to use the commit above, you can do this:
```
git fetch openlayers
git reset --hard f988fc42a9b9b3617015e396df6a21f834e21a68
```

In either case, you'll want to force push a change to your branch after making the changes:
```
git push --force origin issue-10823
```

**Comment by glenselle** [comment]
I hate to create a stale PR on the repo so I'm going to close for now but leave the issue open. As I mentioned, not sure how best to proceed but totally willing to work on this if the maintainers have a specific way they'd like to handle this.

**Comment by ahocevar** [comment]
@glenselle Thanks for your contribution! If you are able to finish this pull request with tests in a timely manner, it would be appreciated. Feel free to do the refactoring you suggested, or stick with passing around `propertyName` as string. If you need help for type checking, I'll be able to help. If you rebase your existing work on master, this will be easier than it used to be, because I made some type checking related changes to the XML formats.

**Pull request closed without merging**
