### PR TITLE
Fix vectortile ignoring custom tilegrid for projection

### LINKED ISSUE #7199: ol.source.VectorTile ignores custom tilegrid for projection
If i pass custom tile grid to ol.source.VectorTile, it is not saved to this.tileGrids_ and therefore it is ignored by ol.source.VectorTile.prototype.getTileGridForProjection.

It is necessary to save it to tileGrids_ in ol.source.VectorTile constructor. 

See #7200

### PR DESCRIPTION
**Pull request by AlesJiranek**
Fixes #7199

### CODE REVIEW

**Comment by AlesJiranek** [comment]
In my app, i`m using projection EPSG:5514, and tileGrid created like this.

In some edge cases, like when I`m in low zoom level, It generates wrong tile coords. 
For example [13, -1, 0], [13. -1, 1] althougt x and y should be always positive.

If I add my tile grid to tileGrids_, everything works as expected

```
var baseResolution = options.baseResolution;
var resolutions = new Array(26);
for (var z = 0; z < 26; ++z) {
  resolutions[z] = baseResolution / Math.pow(2, z);
}

options.tileGrid = new ol.tilegrid.TileGrid({
  extent: extent,
  origin: ol.extent.getBottomLeft(extent),
  resolutions: resolutions
  tileSize: options.tileSize
});
```

**Comment by ahocevar** [comment]
Can you share more of your configuration? Especially how your view is set up, and the whole configuration of your vectortile layer and source.

**Comment by ahocevar** [comment]
Without seeing more of your configuration, I think that this change could fix your issue properly:
```diff
--- a/src/ol/vectorimagetile.js
+++ b/src/ol/vectorimagetile.js
@@ -94,6 +94,10 @@ ol.VectorImageTile = function(tileCoord, state, src, format, tileLoadFunction,
     sourceTileGrid.forEachTileCoord(extent, sourceZ, function(sourceTileCoord) {
       var sharedExtent = ol.extent.getIntersection(extent,
           sourceTileGrid.getTileCoordExtent(sourceTileCoord));
+      var sourceExtent = sourceTileGrid.getExtent();
+      if (sourceExtent) {
+        sharedExtent = ol.extent.getIntersection(sharedExtent, sourceExtent);
+      }
       if (ol.extent.getWidth(sharedExtent) / resolution >= 0.5 &&
           ol.extent.getHeight(sharedExtent) / resolution >= 0.5) {
         // only include source tile if overlap is at least 1 pixel
```
Can you please verify?

**Comment by AlesJiranek** [comment]
yes, awesome, that`s it. It fixes my problem. Thank you very much.

**Comment by AlesJiranek** [comment]
Are you going to create PR with your changes?

**Comment by ahocevar** [comment]
Thanks for verifying @AlesJiranek. I have created #7206 with the change I posted above.

**Comment by AlesJiranek** [comment]
thank you

**Pull request closed without merging**
