### PR TITLE
Use number literal for sphere radius

### PR DESCRIPTION
**Pull request by probins**
See #6885. I could create a const for this, but as this is purely internal I think a literal with a comment should be enough.

### CODE REVIEW

**Comment by ahocevar** [comment]
I'm wondering if it wouldn't make sense to get rid of `ol.sphere.WGS84` and `ol.sphere.NORMAL` entirely. Instead, `ol.Sphere#haversineDistance`, `ol.Sphere#offset` and `ol.Sphere#geodesicArea` could become static functions with a `radius` argument in the `ol.sphere` namespace. `ol.Sphere` could be marked `@deprecated` and removed in 5.0.

What do others think?

**Comment by fredj** [comment]
+1 to have static functions. That will be in line with what we already doing in `ol.extent.*`, `ol.size.*`, ...

**Comment by probins** [comment]
+1

I used to use `ol.sphere.WGS84` in my own apps, but changed to static functions quite some time ago. Two examples use it, but they can easily be changed.

Once ES modules are more widely used, there will probably be freely available modules containing this sort of utility function; then OL won't need to provide its own version.

**Comment by probins** [comment]
just noticed that `proj.EPSG3857`, which also uses this radius, defines it as a constant. It would be better for both this and 4326 to do the same thing.

**Comment by tschaub** [comment]
> What do others think?

@ahocevar - I agree it would be nice to provide a convenient way to do spherical calculations on ol geometries.  Probably best for another ticket, but I like the idea of functions with convenient defaults.  E.g.

```
ol.sphere.getArea(geometry, options);
ol.sphere.getLength(geometry, options);
ol.sphere.getDistance(geometry1, geometry2, options);

// options.projection defaults to 'EPSG:3857'
// options.radius defaults to the WGS:84 radius
```

**Comment by probins** [comment]
amended so that 4326 uses a constant as 3857 does (and added a comment to 3857)

@ahocevar I too would prefer to get rid of `ol.Sphere`, but I think that's a separate issue/PR. The aim of this PR is to remove a couple of unnecessary dependencies.

**Pull request merged**
