### PR TITLE
Pluggable renderers

### LINKED ISSUE #6303: Explicitly require the renderer
We currently offer runtime renderer configuration with `renderer: 'canvas'` or `renderer: 'webgl'` as map options.  This was a nice idea, but it has the major drawback of not being able to explicitly depend on just one renderer.  We assumed everybody would be using Closure Compiler build flags like `ENABLE_WEBGL=false`.  Instead people use the full build - which includes far more code than anybody needs - since it is far more convenient than using the Closure Compiler.  While the WebGL renderer has been gaining functionality, it is still incomplete, and I don't think there has been a good reason to push it on all of our users for 2.5 years.

So, I think it would make sense to specify more explicitly which renderer an application depends on.  I see two alternatives for doing this.

### Alternative 1

Make it so the `renderer` option accepts a renderer constructor instead of a string.  Keep the Canvas renderer the default.

People who want to use the Canvas renderer would not change any application code.  People who want to use the WebGL renderer would do this:
```
var map = new ol.Map({
  renderer: ol.renderer.webgl.Map,
  // ...
});
```
To get a smaller build with the Closure Compiler, people using the WebGL renderer would set `ENABLE_CANVAS=false` (as they have to now).  The downside of this alternative is that all layer renderer types are still required for each layer type. 

### Alternative 2

Create a new map constructor that pulls in the WebGL renderer.  Keep the `ol.Map` constructor using the Canvas renderer.  Create new layer renderers that pull in WebGL layer rendering code.  Keep the existing layer constructors using Canvas rendering code.

People who want to use the Canvas renderer would not change any application code.  People who want to use the WebGL renderer would do this:
```
var map = new ol.WebGLMap({
  layers: [
    new ol.layer.WebGLTile({
      // ...
    })
  ]
});
```

There would be no renderer-related build flags in this alternative.  Everybody could get smaller builds just by using the correct type of map and layer.

### PR DESCRIPTION
**Pull request by tschaub**
### The Problem

We have a lot of unnecessary dependencies within the library.

For example, `ol.layer.Tile` [depends on both](https://github.com/openlayers/openlayers/blob/29a6473c3dfd7f97ecf84c77dcc9391033217dfd/src/ol/layer/tile.js#L8-L9) `ol.renderer.canvas.TileLayer` and `ol.renderer.webgl.TileLayer`.  Same situation with the rest of the layers.

And `ol.Map` [depends on both](https://github.com/openlayers/openlayers/blob/29a6473c3dfd7f97ecf84c77dcc9391033217dfd/src/ol/layer/tile.js#L8-L9) `ol.renderer.canvas.Map` and `ol.renderer.webgl.Map`.

The map also [depends on](https://github.com/openlayers/openlayers/blob/29a6473c3dfd7f97ecf84c77dcc9391033217dfd/src/ol/control.js#L4-L6) `ol.control.Attribution`, `ol.control.Zoom`, and `ol.control.Rotate`.  And a [whole lot of interactions](https://github.com/openlayers/openlayers/blob/29a6473c3dfd7f97ecf84c77dcc9391033217dfd/src/ol/interaction.js#L4-L13).

The Compiler and build flags can ameliorate some of this, but we can improve the situation.

### Proposed Solution

We can treat map and layer renderers as plugins.  To maintain backwards compatibility (and for convenience), `ol.Map` can register both map renderers and all the layer renderers.

In addition, `ol.Map` can continue to use the `defaults()` functions for controls and interactions (and these will retain their dependencies).

Then, for people who don't need all the extra stuff (and don't mind a bit of inconvenience), we can create a `ol.PluggableMap` (and `ol.Map` will extend this).  People using `ol.PluggableMap` will register just the map renderer and layer renderers that they need.  And they can provide controls and interactions directly (by default, `ol.PluggableMap` comes with no controls or interactions).  In this way, all dependencies will be explicit.  No build flags will be necessary and other minifiers can be used.

Fixes #6303.

### CODE REVIEW

**Comment by tschaub** [comment]
This works, but I need to create some `olx` types to keep the Compiler from renaming the static methods.

**Comment by bartvde** [comment]
interesting @tschaub thanks for taking this forward

**Comment by probins** [comment]
Presumably, this replaces #6303? (And fixes much of #6311.)

A dramatic reduction in the number of unwanted dependencies, and way more flexible than the current setup. Once this passes Travis, I'll pull in the branch and try some tests, and also look at the new dependency tree.

I'm not sure about the `PluggableMap` name, which doesn't seem very descriptive to me, as the only 'pluggables' are the renderers. It's essentially a map without any defaults, so perhaps `BaseMap` (or 'raw' or 'bare' or something) would be better?

Something that's missing here is documentation, particularly for those wanting to use `PluggableMap`. The custom build tutorial has always stated that you list the classes/methods you use in your app in your build config, but the renderers aren't referred to in apps, and do not appear in the docs anywhere, so people have to be told what to include. I notice that `api` (stable?) has been added to the renderer constructors, but they have no docs text. ISTM there should be some examples of using `PluggableMap` too, though that could be in a separate PR.

**Comment by probins** [comment]
also, it would be good if `View` could be included in this, as the `fit` method is currently 'requiring' a lot of vector files, which are only needed if you use a geometry with `fit()`, probably only used by a small %age of maps. `view.js` and `map.js` can remain as is for bc. View is only included in `map.js` to create a default view if none is provided in the constructor options, but I can use `setView()` at some later time, so is this actually necessary? This view creation can be omitted from `PluggableMap`, and if a View _is_ needed at construction time, then those using `PluggableMap` can be told they have to supply one in the options.

If we then create `viewwithoutgeoms.js`, and put `fit()` (or at least the geom bit) in a separate file, then `PluggableMap` users can use the no-geoms view, and add `fit`/geoms separately if they wish. This would then enable people to have maps without vectors if they want.

**Comment by tschaub** [comment]
For people who want to explicitly depend on just what they use, there is now a `PluggableMap` constructor.  To use it, you first need to register the map and layer renderers that you use.  It also doesn't come with any interactions or controls, so you add those explicitly.  For example:
```js
import Map from 'ol/pluggablemap';
import MapRenderer from 'ol/renderer/canvas/map';
import PluginType from 'ol/plugintype';
import TileLayer from 'ol/layer/tile';
import TileLayerRenderer from 'ol/renderer/canvas/tilelayer';
import View from 'ol/view';
import XYZSource from 'ol/source/xyz';
import control from 'ol/control';
import interaction from 'ol/interaction';
import plugins from 'ol/plugins';

plugins.register(PluginType.MAP_RENDERER, MapRenderer);
plugins.register(PluginType.LAYER_RENDERER, TileLayerRenderer);

new Map({
  target: 'map-container',
  interactions: interaction.defaults(),
  controls: control.defaults(),
  renderer: MapRenderer,
  layers: [
    new TileLayer({
      source: new XYZSource({
        url: 'http://tile.stamen.com/terrain/{z}/{x}/{y}.jpg'
      })
    })
  ],
  view: new View({
    center: [0, 0],
    zoom: 2
  })
});
```

For a bit of convenience, there is now a `CanvasMap` constructor.  So to get just the canvas renderer (this still depends on all canvas layer renderer types and you get the default controls and interactions), you can do this:
```js
import Map from 'ol/canvasmap';
import View from 'ol/view';
import Tile from 'ol/layer/tile';
import XYZ from 'ol/source/xyz';

new Map({
  target: 'map-container',
  layers: [
    new Tile({
      source: new XYZ({
        url: 'http://tile.stamen.com/terrain/{z}/{x}/{y}.jpg'
      })
    })
  ],
  view: new View({
    center: [0, 0],
    zoom: 2
  })
});
```

Both examples above will be possible with the next release.

**Comment by nboisteault** [comment]
@tschaub Hi, I don't find `ol/plugins` nor `ol/PluginType` in OL6. Can you update your code above for OL6 please ? Thanks.

**Comment by MoonE** [comment]
Have a look at the `ol/Map` code, there is now a `createRenderer` method instead.
https://github.com/openlayers/openlayers/blob/main/src/ol/Map.js

**Comment by nboisteault** [comment]
@MoonE Thanks for the hint but if I load `ol/Map` instead of `ol/PluggableMap`, how do I avoid `module:ol/interaction~defaults` in final bundle?

**Comment by ahocevar** [comment]
@nboisteault You can continue using `ol/PluggableMap`. Just make sure you implement the `createRenderer` method, e.g. like in https://github.com/openlayers/openlayers/blob/2cac6c4/src/ol/Map.js#L75-L77

**Comment by nboisteault** [comment]
Thanks @ahocevar. What I did if it can help someone : 

```javascript
import PluggableMap from 'ol/PluggableMap';
import CompositeMapRenderer from 'ol/renderer/Composite';
import { assign } from 'ol/obj';

class olMap extends PluggableMap {
    /**
     * @param {import("./PluggableMap.js").MapOptions} options Map options.
     */
    constructor(options) {
        options = assign({}, options);

        super(options);
    }

    createRenderer() {
        return new CompositeMapRenderer(this);
    }
}

const myMap = new olMap({...});
```

**Pull request merged**
