### PR TITLE
Use custom query function to replace missing taffydb query features

### LINKED ISSUE #14397: Missing file content in dist folder of v7.2.0-package.zip
Are the files ol.js and ol.js.map no longer distributed? Both have a size of only 1 KB in the current version. Or is that just a mistake?

### PR DESCRIPTION
**Pull request by ahocevar**
Fixes #14397

### CODE REVIEW

**Comment by ahocevar** [comment]
When this is approved, I can publish v7.2.1.

**Comment by tschaub** [comment]
Thanks for debugging and figuring out a fix.  I missed this in my review of the JSDoc upgrade.  Would be nice to have something that fails for such a severe issue.

**Review by tschaub — APPROVED** [review]

**Comment by marcjansen** [comment]
Sorry I did not notice this, I second @tschaub s call fpr a check here.

**Comment by ahocevar** [comment]
@marcjansen @tschaub Here you go: #14405

**Pull request merged**
