### PR TITLE
Improved drawing experience on touch devices

### PR DESCRIPTION
**Pull request by ahocevar**
With this change, the Draw interaction allows accurate drawing when using finger/stylus. Geometries are not being updated while panning the map, and the vertex being drawn can be moved before lifting the finger/stylus when in a long press gesture.

On mouse devices, long press works now too, but nothing else changes.

### CODE REVIEW

**Comment by ahocevar** [comment]
I have now made the new behavior configurable (it can also be turned off), and added tests.

**Comment by tschaub** [comment]
@ahocevar - are the videos above labeled correctly?  In the "after" one, it looks to me like vertices are getting added on drag.  While in "before", you can drag the map without adding a vertex.

**Comment by ahocevar** [comment]
They are labeled correctly @tschaub. The "after" video also shows how a vertex that is already set can be dragged on long press. It's probably easier to see live with the branch checked out.

**Comment by ahocevar** [comment]
Thanks for the review @tschaub.

**Pull request merged**
