### PR TITLE
Add an option to remove feature silently in ol.source.Vector.

### PR DESCRIPTION
**Pull request by ger-benjamin**
For #15642 

Be able to remove a feature from vector source without triggering events. Useful to batch remove features.

### CODE REVIEW

**Comment by ahocevar** [comment]
I'm not sure this really fixes #15642. Please see my https://github.com/openlayers/openlayers/issues/15642#issuecomment-1999452896.

**Review by ahocevar — CHANGES_REQUESTED** [review]
Thanks for the contribution! From an API consistency perspective, it would make sense to add a `removeFeatures()` method, instead of adding a `silent` option to `removeFeature()`. Would you be able/willing to change this pull request accordingly?

**Comment by ger-benjamin** [comment]
I've added a first simple version of removeFeatures/removeFeature

**Comment by ahocevar** [comment]
I think going the other way around would be easier, something like
```js
diff --git a/src/ol/source/Vector.js b/src/ol/source/Vector.js
index b02b81da5e..b8f71d3200 100644Source extends Source {
--- a/src/ol/source/Vector.js
+++ b/src/ol/source/Vector.js
@@ -1093,6 +1093,20 @@ class VectorSource extends Source {
     }oveFeatures(features) {
   } const removedFeatures = [];
     for (let i = 0, ii = features.length; i < ii; ++i) {
+  removeFeatures(features) { this.removeFeatureInternal(features[i]);
+    const removedFeatures = [];
+    for (let i = 0, ii = features.length; i < ii; ++i) {
+      const removedFeature = this.removeFeatureInternal(features[i]);
+      if (!removedFeature) {emovedFeature);
+        continue;
+      }(removedFeatures.length > 0) {
+      removedFeatures.push(removedFeature);
+    }
+    if (removedFeatures.length > 0) {
+      this.changed();
+    }
+  }
+
   /**
    * Remove feature without firing a `change` event.
    * @param {FeatureType} feature Feature.
@@ -1113,9 +1127,11 @@ class VectorSource extends Source {
       delete this.idIndex_[id.toString()];
     }
     delete this.uidIndex_[featureKey];
-    this.dispatchEvent(
-      new VectorSourceEvent(VectorEventType.REMOVEFEATURE, feature),
-    );
+    if (this.hasListener(VectorEventType.REMOVEFEATURE)) {
+      this.dispatchEvent(
+        new VectorSourceEvent(VectorEventType.REMOVEFEATURE, feature),
+      );
+    }
     return feature;
   }
 ```

**Comment by ger-benjamin** [comment]
I've done the asked changes, but in this way, I've to duplicated the whole `removeFeature` code into the `removeFeatures` methode. Are you sure that's the right thing to do ?
If I do that, I've probably to duplicate tests about it `removeFeature`, no ?

**Comment by ahocevar** [comment]
I have to apologize, I somehow managed to garble the diff I had posted above. I edited the post to show the correct diff.

That said, there should be no duplicated code. The change is essentially this new `removeFeatures()` method:
```js
  removeFeatures(features) {
    const removedFeatures = [];
    for (let i = 0, ii = features.length; i < ii; ++i) {
      const removedFeature = this.removeFeatureInternal(features[i]);
      if (!removedFeature) {
        continue;
      }
      removedFeatures.push(removedFeature);
    }
    if (removedFeatures.length > 0) {
      this.changed();
    }
  }
```
And to make `removeFeatureInternal()` more efficient, events are only dispatched if someone listens to them:
```js
    if (this.hasListener(VectorEventType.REMOVEFEATURE)) {
      this.dispatchEvent(
        new VectorSourceEvent(VectorEventType.REMOVEFEATURE, feature),
      );
    }

**Comment by ger-benjamin** [comment]
I've edited my post above.

But I can't call only `removeFeatureInternal`. Otherwise, this part about deleting nullGeometryFeatures_ and featuresRtree_.remove would be missing and break the feature

**Comment by ahocevar** [comment]
Looks like you have messed up something. This is what I had in mind: https://github.com/ahocevar/openlayers/commit/1e14403c34c604904d2cf93ad4444b2c9bb3920f

**Comment by ahocevar** [comment]
Oh, sorry again, you're right. The code you marked above can simply be moved from `removeFeature()` to the top of `removeFeatureInternal()`.

**Review by ahocevar — APPROVED** [review]
And that's what you did. Beautiful! Thanks for the contribution.

**Pull request merged**
