### PR TITLE
Improve documentation of getGetLegendGraphicUrl

### PR DESCRIPTION
**Pull request by marcjansen**
This also adresses one review comment by @jahow on #9762.

Please review.

### CODE REVIEW

**Comment by jahow** [comment]
This is missing the identical comment on tile WMS :wink: 
https://github.com/openlayers/openlayers/blob/993bf0d2cb8b7abff582aca12ddc8dbc60e016c6/src/ol/source/TileWMS.js#L214-L224

**Comment by marcjansen** [comment]
> This is missing the identical comment on tile WMS 
> https://github.com/openlayers/openlayers/blob/993bf0d2cb8b7abff582aca12ddc8dbc60e016c6/src/ol/source/TileWMS.js#L214-L224

… aaaargh. On it. Thanks for catching this.

**Comment by marcjansen** [comment]
@jahow updated, TIA for another look.

**Comment by marcjansen** [comment]
Thanks for the review.

**Pull request merged**
