### PR TITLE
Simplify icon example

### LINKED ISSUE #11953: Popup opens on the wrong marker
**Describe the bug**
Popup opens on the wrong marker.

recording

**To Reproduce**
1. Go to https://openlayers.org/en/latest/examples/icon.html
2. Move worldmap till you see the marker again
3. Click on the marker
4. Notice that the popup opens on the main marker

**Expected behavior**
Popup should open on the clicked marker

### PR DESCRIPTION
**Pull request by ahocevar**
Fixes #11953.

### CODE REVIEW

**Comment by mike-000** [comment]
The problem with simply using `evt.coordinate` is that the popup does not stay on the icon when you zoom in

image

**Comment by ahocevar** [comment]
> The problem with simply using evt.coordinate is that the popup does not stay on the icon when you zoom in

Same with the existing example. This is because the Bootstrap Popover lives outside the div element that's automatically anchored to the coordinate by `ol/Overlay`.

**Comment by mike-000** [comment]
Yes, there was a regression between version 6.3 and 6.4 which is fixed by going back to the previous version of bootstrap.

**Comment by ahocevar** [comment]
> Yes, there was a regression between version 6.3 and 6.4 which is fixed by going back to the previous version of bootstrap.

It could also be fixed by creating the Bootstrap popover with a `container` property, like in the `overlay.html` example. But because the purpose of this example is to showcase working with icons, not popups, I added a commit that simply closes the popup when the map is moved.

**Review by MoonE — APPROVED** [review]
Thanks, @ahocevar.

**Pull request merged**
