### PR TITLE
Unify rendering tests

### LINKED ISSUE #9330: Unify rendering tests
**Unify rendering tests**
Currently there are two different approaches for testing the rendering output.
A part of the rendering tests is in `rendering` and the other part is in `test/rendering`.

IMHO it would be better to unify the split tests to use one method for both.

### PR DESCRIPTION
**Pull request by KaiVolland**
This PR transforms the old rendering tests to the new approach.

All tests under `test/rendering/ol` are moved to `rendering/cases` and adapted.

TODOS:
- [x] map
- [ ] layer
- [ ] reproj
- [x] source
- [x] style

closes #9330

### CODE REVIEW

**Comment by KaiVolland** [comment]
@ahocevar @tschaub is there any way to access the rendering-images created by the CI? They are stored in an artifact, but i don't know if its possible or how to see them.

The rendering tests of the TextStyle are all good on my system with the same browser version as running on the CI. But they are currently failing on the CI. Maybe due to different fonts so i'd like to check what the CI produces.

**Comment by fredj** [comment]
You can access the artifacts in the [CircleCI page](https://circleci.com/gh/openlayers/openlayers/971), in the 'Artifacts' tab

**Comment by KaiVolland** [comment]
... so easy :smile: . I just had to log in. thx @fredj

**Comment by KaiVolland** [comment]
### STATUS

I transfomed the majority of the tests but now im stuck with some tests for different reasons:
- `clip.test.js` `tile.test.js` (render listener)
  - I couldn't manage to transform these tests as they rely on OL events/listeners which don't work as aspected for me in the test environment.
- `vectorimage.test.js` (test with TextStyle)
  - Al tests with `TextStyle` are hard to compare with current setup as the CI seems to have different fonts installed which leads to high pixel mismatch numbers. Found a workaround for the `TextStyle` tests themselves but nut for the declutter tests in the `vectorimage.test.js`
- `ReprojImage`
  - Every current test of the new test approach is based on a rendered map. But the `ReprojIamge` tests don't. I didn't dove to deep into these so i might miss the simple solution.

Nevertheless i could need some help / hints for the last missing tests.

**Comment by marcjansen** [comment]
Really nice progress, @kaivolland.

Wrt your questions, maybe @ahocevar, @tschaub or @fredj hopefully have input.

Thanks so far

**Comment by tschaub** [comment]
If you have an example of the tests using events that don’t work, that would be helpful.

There is a lot of great work here.  It could make sense to get this in and continue the effort on the remaining tests separately.

**Comment by marcjansen** [comment]
Plus one for getting this in and then continue with dedicated PRs.

**Comment by KaiVolland** [comment]
`package-lock.json` was remove via force-push.

**Comment by tschaub** [comment]
Thanks @KaiVolland for all the work on this.

**Pull request merged**
