### PR TITLE
Add DblClickDragZoom interaction

### PR DESCRIPTION
**Pull request by oterral**
Proposal for https://github.com/openlayers/openlayers/issues/13751 .

You can test the behavior in the [drag-rotate-and-zoom.html example](https://deploy-preview-13752--ol-site.netlify.app/examples/drag-rotate-and-zoom.html)

### CODE REVIEW

**Review by ahocevar — COMMENTED** [review]
Thanks for this contribution, @oterral. Would you be able to add tests? And instead of adding the new interaction to an existing example, I think it would deserve its own dedicated example with a proper description.

**Comment by oterral** [comment]
@ahocevar  Yes I can do that.

**Comment by oterral** [comment]
@ahocevar  Tests added

**Review by ahocevar — APPROVED** [review]
Thanks, @oterral

**Comment by oterral** [comment]
@ahocevar  vielen danke !!!

**Comment by alexkleinwaechter** [comment]
In the actual 7.4 version, the DblClickDragZoom interaction throws an error while compiling in typescript, angular.

Compiled with problems:
ERROR
node_modules/ol/interaction/DblClickDragZoom.d.ts:103:26 - error TS2503: Cannot find namespace 'NodeJS'.

Best!
Alex

**Comment by ahocevar** [comment]
@alexkleinwaechter Please update to the latest `ol@dev`, where this is fixed.

**Pull request merged**
