### PR TITLE
Hit detect with pixelRatio of 1

### LINKED ISSUE #11333: 6.4.0 pointermove performance
Performance of pointermove event is much slower than in 6.3.1.

Example with 1000 features with non cached styles:
6.4.0.
https://codesandbox.io/s/prod-fast-hh1zd?file=/main.js:1438-1449

6.3.1.
https://codesandbox.io/s/dazzling-varahamihira-fmzkd?file=/main.js

It affects many operations like zoom, panning etc in my app. It's not so visible in examples above but you can see it on cursor. The cursor change in 6.3.1 is super fast but the change in 6.4.0 is much slower.

### PR DESCRIPTION
**Pull request by ahocevar**
Fixes #11333. This is a regression introduced by #11277

### CODE REVIEW

**Comment by M393** [comment]
Should the hit detection image be always created with pixel ratio of 1 then, or did I misunderstand the title of this pull request?
https://github.com/openlayers/openlayers/blob/cad5057a969fb3de0f3b5acd64a6d2c34064d57d/src/ol/style/IconImage.js#L168-L186

**Comment by ahocevar** [comment]
@M393 For hit detection, the instruction group is replayed with a pixel ratio of 1. So we need to use that in the hit detection instructions. The image itself should be scaled properly anyway. Do you have indication that this might not be the case?

**Comment by ahocevar** [comment]
Update: I think you are right, @M393. For hit detection, we either need to take the image's pixel ratio into account (or create another image with pixel ratio 1, which would add unnecessary overhead).

**Comment by M393** [comment]
Why not always create the hit detection image with an pixel ratio of 1?

**Comment by ahocevar** [comment]
> Why not always create the hit detection image with an pixel ratio of 1?

Wouldn't that mean you have to create two images on Retina devices? One for the device pixel ratio, and one for the pixel ratio 1.

**Comment by M393** [comment]
Oh, you are right There is only one image created for hit detection and for display.

**Comment by ahocevar** [comment]
I force-pushed a revised version of this change, which makes hit detection work for icon images, scaled icon images and regular shapes. The key to achieving this was a significant simplification: we always use a canvas with a pixel ratio of 1 for hit detection, so we also can hit detection images with a pixel ratio of 1.

**Pull request merged**
