### PR TITLE
Test individual example compilation

### PR DESCRIPTION
**Pull request by gberaudo**
Related to https://github.com/openlayers/ol3/issues/5340.

This PR adds a new task `test-compile-each-example.sh` which allows to compile each example individually and thus detect more errors than the fast combined examples we run with `make ci`.

This task is very time consuming so should be run only on occasions, for examples to prepare a release or after a significant commit.

The task returns `1` on error.

### CODE REVIEW

**Comment by tschaub** [comment]
The reason we went with compiling the examples together is that the build times for individual compilation made waiting for approval on a pull request very painful.

I haven't checked here yet.  What does this mean for the time it takes to run `make-ci`?

**Comment by marcjansen** [comment]
We could run this check only if the pr number is evenly dividable by 10, so most PRs will get fast feedback.

I like it as long as it uncovers probable issues, even though we may get broken builds that stem from a previous unrelated change.

**Comment by probins** [comment]
it doesn't have to be in CI though. It can be run as a separate task.

**Comment by gberaudo** [comment]
The total compilation time is very long, at least 30min on my fast computer, which makes it unreasonable to run by Travis every time. As a result it is not triggered by `make ci` or other.

The task being avaiable, anyone can run it manually as desired.
But I think it could be great to run it before each release. It would then be up to the release manager to fix the issues or release any way.

**Comment by bartvde** [comment]
Right let's add it to the release procedure on the Wiki so the release manager cannot forget about the step.

**Comment by marcjansen** [comment]
Agreed!

**Comment by gberaudo** [comment]
[logs.txt](https://github.com/openlayers/ol3/files/263033/logs.txt)

See attached the logs. Currently, 5 tests have errors and 135 are passing.

**Comment by gberaudo** [comment]
I fixed many errors and one warning about a global use of `this` which was confusing closure.

What is left is:
- one example with many warnings about a global use of `this`;
- some examples with errors in `olx`.

These errors look like (see logs for details):
```
1 getfeatureinfo-layers examples/getfeatureinfo-layers.js
info ol Parsing dependencies
info ol Compiling 318 sources
ERR! compile externs/olx.js:2435: ERROR - Bad type annotation. Unknown type ol.interaction.DragBoxEndConditionType
ERR! compile  *     boxEndCondition: (ol.interaction.DragBoxEndConditionType|undefined)}}
ERR! compile                          ^
ERR! compile 
ERR! compile 
ERR! compile externs/olx.js:2472: ERROR - Bad type annotation. Unknown type ol.interaction.DragBoxEndConditionType
ERR! compile  * @type {ol.interaction.DragBoxEndConditionType|undefined}
ERR! compile           ^
ERR! compile 
ERR! compile externs/olx.js:3818: ERROR - Bad type annotation. Unknown type ol.layer.VectorTileRenderType
ERR! compile  *     renderMode: (ol.layer.VectorTileRenderType|string|undefined),
ERR! compile                     ^
ERR! compile 
ERR! compile externs/olx.js:3854: ERROR - Bad type annotation. Unknown type ol.layer.VectorTileRenderType
ERR! compile  * @type {ol.layer.VectorTileRenderType|string|undefined}
ERR! compile           ^
ERR! compile 
```

Do someone has a clue about the cause of these errors?

**Comment by probins** [comment]
see #4945

**Comment by gberaudo** [comment]
Thanks @probins.

Does that mean we should stop using `manage_closure_dependencies: true` for example builds? In https://github.com/openlayers/ol3/blob/master/doc/tutorials/custom-builds.md is stated the option should always be activated; should we change the wording there?

**Comment by probins** [comment]
only for the sort of minimal examples that create these sort of errors. Those that are causing errors are not maps but just capabilities and other minimal things (I think you can skip index.js :-) ) which don't include the types referred to. Alternatively suppress/ignore that error for those examples.

**Comment by probins** [comment]
btw, if you could use the latest master whenever you next run this, I'd be interested to know if putting the typedefs in one file fixes the typedef errors.

**Comment by probins** [comment]
> the sort of minimal examples

what I mean is that these cases aren't realistic, as you wouldn't compile the library with the code to for example parse a capabilities doc

**Comment by tschaub** [comment]
> Does that mean we should stop using manage_closure_dependencies: true for example builds? In https://github.com/openlayers/ol3/blob/master/doc/tutorials/custom-builds.md is stated the option should always be activated; should we change the wording there?

I think we need to stop using `manage_closure_dependencies` until the library is structured in a way that it is safe to use.  And it may be that we never recommend its use.  This is unfortunate because the compiler is not able to remove as much unused code as it should when we throw the whole library at it (see #3447).

**Comment by gberaudo** [comment]
+1 to stop using `manage_closure_dependencies` for now. I updated the configuration file and now all examples except one are compiling properly.

The remaining example complains about a dangerous use of the global this object:
```
ERR! compile /home/gberaudo/dev/ol3/build/examples/snap.js:51: WARNING - dangerous use of the global this object
ERR! compile     this.select = new ol.interaction.Select();
ERR! compile     ^
ERR! compile 
ERR! compile 
ERR! compile /home/gberaudo/dev/ol3/build/examples/snap.js:51: WARNING - dangerous use of this in static method Modify.init
ERR! compile     this.select = new ol.interaction.Select();
ERR! compile     ^
ERR! compile 
ERR! compile /home/gberaudo/dev/ol3/build/examples/snap.js:52: WARNING - dangerous use of the global this object
ERR! compile     map.addInteraction(this.select);
ERR! compile                        ^
ERR! compile 
```

Should I add annotations to the example to fix the warnings?
Then there is the PR on closure-util: https://github.com/openlayers/closure-util/pull/150.

**Comment by gberaudo** [comment]
@probins you asked for the result of a run on top of your work about moving the typedefs. I rebased on to p of master and tested (with manage_closure_dependencies=false) and it works (only one warning about the global this).

**Comment by probins** [comment]
it should work with manage_closure_dependencies=true too, for the typedefs. You'll still have problems with `ol.layer.VectorTileRenderType` as that's an enum.

**Comment by gberaudo** [comment]
This now returns 1 on errors (warnings are ignored). I updated `tasks/readme.md` and rebased on top of master.

The task compiles all the examples without errors so I think it is now ready for merging.

@probins, I tried restoring managed dependencies but I got these errors:
```
ERR! compile externs/olx.js:1263: ERROR - Bad type annotation. Unknown type ol.control.ScaleLine.Units
ERR! compile  *     units: (ol.control.ScaleLine.Units|string|undefined)}}
ERR! compile                ^
ERR! compile 
ERR! compile 
ERR! compile externs/olx.js:1303: ERROR - Bad type annotation. Unknown type ol.control.ScaleLine.Units
ERR! compile  * @type {ol.control.ScaleLine.Units|string|undefined}
ERR! compile           ^
ERR! compile 
ERR! compile 
ERR! compile 2 error(s),
```

**Comment by gberaudo** [comment]
Updated the PR description.

**Comment by probins** [comment]
yup, this is the same issue as #4945. You could fix it for the enums by doing the same as what we did for typedefs: move them all into one file which is always included in the build script and put them all in `ol` namespace so there are no circular dependency issues.

**Comment by ahocevar** [comment]
Not sure we want enums I. A separate file. With one provide per file and enums tugged on the class they belong to, this issue should be gone.

**Comment by tschaub** [comment]
Let's revisit this after transforming sources to ES modules for the 5.0 release.

**Pull request closed without merging**
