### PR TITLE
Fix renderer.canvas.TileLayer to calculate correct canvas height for drawing.

### PR DESCRIPTION
**Pull request by kollhof**
Fixes https://github.com/openlayers/openlayers/issues/6473

### CODE REVIEW

**Comment by tschaub** [comment]
Looks like the right fix.  It would be great to have a rendering test for this.

**Comment by ahocevar** [comment]
I took the liberty to add a rendering test.

**Comment by ahocevar** [comment]
@kollhof, can you please submit a [CLA](https://github.com/openlayers/cla/) so we can merge this? Thanks!

**Comment by kollhof** [comment]
@ahocevar Thank you for the adding the tests, I shall read through them.
I have emailed a signed CLA.

**Comment by waxenegger** [comment]
Sorry to sound a bit pushy but it would be very much appreciated if this was part of the next release. Using the TileLayer and building with the sources from the release I'm going to have to patch it in my build  for now since I have a few cut-off images in the y direction.

**Comment by kollhof** [comment]
@waxenegger I am using the npm package ol@4.0.1-beta.2, it has the fix and works like a charm.

**Comment by waxenegger** [comment]
@kollhof thank you, that's definitely an option.

why it didn't occur to me that there are packages out there other than the 'official'/stable release, God only knows...

**Pull request merged**
