### PR TITLE
Use different constant value to indicate NO_IMAGE in KML format

### PR DESCRIPTION
**Pull request by ahocevar**
This is a follow-up on #5745 and addresses https://github.com/openlayers/ol3/pull/5745#discussion_r75606099.

### CODE REVIEW

**Comment by ahocevar** [comment]
cc @tamarmot

**Comment by tamarmot** [comment]
Is it too late for me to fix the NO_IMAGE constant in this pull request?

**Comment by ahocevar** [comment]
I merged your pull request, and came up with this follow-up. I just wanted you to have a look to see if I did the right thing @tamarmot-

**Comment by ahocevar** [comment]
I don't really care about this, so closing.

**Pull request closed without merging**
