### PR TITLE
Added the srs property to the js object that is the result of the par…

### PR DESCRIPTION
**Pull request by BasieP**
…sing of the xml capabilities.

see: http://docs.geoserver.org/stable/en/user/services/wms/reference.html

### CODE REVIEW

**Comment by BasieP** [comment]
oke i've been working for more then 20  hours now to get the tests running on my windows (cygwin) machine but it simply won't work..
so sorry i can't make a pull request that fixes the build. if you require it of me, please write a decent guide, cause so far the 10 lines written here: https://github.com/openlayers/openlayers/blob/master/CONTRIBUTING.md#building-on-windows are simply not working (i get dependency errors)

ontopic:
I want to use for example this WMS server:
https://geodata.nationaalgeoregister.nl/ahn2/wms?request=GetCapabilities&version=1.1.1
it doesn't return an xml with CRS fields, but with SRS fields.
It changed in version 1.3 but in older versions of the WMS protocol it still says SRS.
If openlayers is providing a parser (which it does) it beter support both versions.

I love to fix the problem, but if you guys don't want it fixed i don't start on it, cause it will be a waste of my time...

**Comment by bartvde** [comment]
WMS Capabilities only supports 1.3.0

**Comment by bartvde** [comment]
Your service supports WMS 1.3.0 so why can't you use that version?

**Comment by bartvde** [comment]
Also see https://github.com/openlayers/openlayers/pull/2944 which got stalled

**Comment by BasieP** [comment]
yeah that is certain...

the point is that i can fix that.......

**Comment by ahocevar** [comment]
Instead of this pull request, maybe a doc improvement pull request that states the supported version(s) of our WMS Capabilities parser would be the right thing to do.

**Comment by BasieP** [comment]
or throw an exception when the version is not high enough... cause right now it parses perfectly.. just with empty fields..

**Pull request closed without merging**
