### PR TITLE
Update links to external resources

### PR DESCRIPTION
**Pull request by MoonE**
Most links are simply changed to https but some of them have a different url.

The links below no longer work and I couldn't find a new version:
- ~http://demo.boundlessgeo.com/geoserver/wms~
- ~http://tilemill.com~
- http://www.swisstopo.admin.ch/internet/swisstopo/en/home/products/software/products/skripts.html
- ~http://a.tiles.mapbox.com/v4/mapbox.mapbox-streets-v6.json~
- ~https://www.openplans.org/topp~
- ~https://www.topografix.com/fells_loop.gpx~
- ~http://mapserver.org~
- ~http://my.zoomify.info/~

### CODE REVIEW

**Comment by ahocevar** [comment]
Thanks for looking through these, @MoonE. Let me help out with some of those you did not find a replacement for:
* http://demo.boundlessgeo.com/geoserver/wms -> https://ahocevar.com/geoserver/wms
* http://tilemill.com -> https://tilemill-project.github.io/tilemill/
* http://www.swisstopo.admin.ch/internet/swisstopo/en/home/products/software/products/skripts.html -> @fredj?
* http://a.tiles.mapbox.com/v4/mapbox.mapbox-streets-v6.json -> https://docs.mapbox.com/vector-tiles/reference/mapbox-streets-v6/
* http://www.openplans.org/topp -> leave as-is - XML namespace uri, not a web url
https://www.topografix.com/fells_loop.gpx > https://openlayers.org/en/latest/examples/data/fells_loop.gpx
http://mapserver.org -> leave as-is - XML namespace uri, not a web url
http://my.zoomify.info/ -> leave as-is - example url, not meant to be visited

**Review by tschaub — APPROVED** [review]
Thanks, @MoonE

**Comment by fredj** [comment]
@MoonE I've pushed a commit to your branch for the Swisstopo link:
https://www.swisstopo.admin.ch/en/knowledge-facts/surveying-geodesy/reference-systems/map-projections.html

The formulas are in the "Documents & Publications" tab at the bottom of the page

**Comment by MoonE** [comment]
Thanks for the help and review!

**Pull request merged**
