### PR TITLE
Make ol.style.Icon scalable in both X and Y

### PR DESCRIPTION
**Pull request by tchandelle**
Implements #2720 and #3803. Add scaleX, scaleY, width and height to ol.style.Image.

Still a few problems: 

- [x] Scale and rotation doesn't work together
- [x] Rendering problem on Firefox

### CODE REVIEW

**Comment by tchandelle** [comment]
That's weird, rendering test on canvas fail on Firefox, generated image does not scale correctly.
But changing scaleX and/or scaleY on an example (icon-color) works.

**Comment by tschaub** [comment]
The change here makes it so we have:

 * size
 * width
 * height
 * scale
 * scaleX
 * scaleY
 * imgSize

We'll need very clear documentation on which does what and where one takes precedence over others.  If there is not a need for all (and I hope there isn't), we should avoid duplication.

@tchandelle - can you provide detail on how each works and why all are needed?

**Comment by tchandelle** [comment]
- `size` and `imgSize` : I didn't change them. And I still don't know the difference. But it's about the size of the source image.
- `width` and `height` : Change the destination width and/or height of the image. If only one of them is declared, the other one is the source size
- `scaleX` and `scaleY` : Apply a scale factor horizontally and/or vertically to the destination image size, can be paired with `width` and/or `height`
- `scale` : It's not used as-is anymore. If defined, it will set both `scaleX` and `scaleY` to the same value. If scaleX and scaleY are different, getScale() will return 1, I'm not sure what else to return.

@tschaub, is this more clear, any suggestions ?

**Comment by tchandelle** [comment]
After some thoughts, here is my new suggestion :
 - (not changed) `imgSize` : original size of the image, if it's manually loaded
 - (not changed) `size` : size of the image to be cropped
 - `destinationSize` : pair of number, to resize the image, 
    - If one of the two values is `null`, it will be calculated by the other, keeping the image ratio.  
An image of `size = [10, 20]` with `destinationSize = [20, null]` will be resized to `[20, 40]`
 - `scale` : either a pair of number (`[scaleX, scaleY]`), or a number

**Comment by tchandelle** [comment]
Rebased, solved conflicts and changed options names as mentioned in my previous comment.

**Comment by tchandelle** [comment]
Rebased with the recent changes made to the webgl renderer.

**Comment by tchandelle** [comment]
What's the status for this PR, it has been opened for quite some time now ? Should I make any changes ?

**Comment by ahocevar** [comment]
I think this looks good now. @tschaub, do you want to take another look?

**Comment by tschaub** [comment]
At a glance, I'm confused.  Perhaps it is just a documentation issue.  Are `scale` and `destinationSize` supposed to be used together?  If these properties are redundant, let's remove one.

**Comment by tchandelle** [comment]
Both serve the same purpose, but one represent a relative percentage, and the other an absolute size in pixels. They can be used together (as illustrated in my last example here-below), although I personally doesn't see the point.

Considering an image of size `[16, 32]` : 
 - `scale: 2` will result to an image of `[32, 64]`
 - `scale: [4, 2]`, an image of size `[64, 64]`
 - `destinationSize: [32, 64]`, an image of size `[32, 64]`
 - `destinationSize: [32, null]` or `[null, 64]`, an image of size `[32, 64]`, keeping the original size ratio
 - `destinationSize: [32, 64], scale: 2`, an image of size `[64, 128]`

**Comment by omarkljung** [comment]
I've tried it out and it works well for my use case when I know the size I want it to have but not the original size so scale is not possible to provide without preloading the image separately.

It's a bit confusing with two different size properties though.
Wouldn't it be possible to just expand the meaning of `size` and `scale` using something similar to what `destinationSize` is here?
What you need is to provide a way to auto scale and not crop. So perhaps if `scale` could take `null` and treat it as unknown scale and therefore automatically scale the whole image (or just one axis?) it would be sufficient?
Giving a proper `size` and `scale` would still crop and scale the cropped image as is the case now.
A `size` and `scale: null` would auto scale.
Combining `size` and `scale` as in your last example would no longer be possible.

Another possibility could perhaps be to introduce a new property to control the cropping i.e `crop: true`.
That would then tell how the `size` property would be applied. `scale` can then be applied afterwards in both cases. For `crop: false` you'd then get auto scaling.

**Pull request closed without merging**
