### PR TITLE
Interactive overview map

### PR DESCRIPTION
**Pull request by felixveysseyre**
Hello,

I have been confronted to the missing interactive _OverviewMap_ control recently: https://github.com/openlayers/ol3/issues/5874

@jonataswalker began some work on the subject, you can find his work here: https://github.com/jonataswalker/ol3-interactive-overview

Therefore I have based my work on his, as you can see in the commit https://github.com/openlayers/ol3/commit/2b7ed7381fb5d353f092b0dee84b3fd44e625f99.

I have tested my modifications thanks to `make check` and made the requested syntax corrections.

This is my first pull request on OL3 repository so make sure to let me know if something is wrong.

### CODE REVIEW

**Comment by felixveysseyre** [comment]
I commited some new changes in order to improve performance.

I was binding necessary functions into the box-updating method instead of the constructor.

Make sure to look at commit https://github.com/openlayers/ol3/pull/5887/commits/7649281900ee8418f6a8d5cba5a914e97a975427 for more information.

**Comment by felixveysseyre** [comment]
@ahocevar Sorry to bug you here but you are the only OpenLayers I had the occasion to work with. Do you know if there is anything to do to push along this pull request ?

**Comment by jhwegener** [comment]
Hi, is there a reason, why this PR is not merged yet?!

**Comment by HelenaWu** [comment]
Would really appreciate having this PR merged too.

**Comment by jhwegener** [comment]
I think on mobile devices it should be possible to disable interactivity. Otherwise the mobile user can get confused!?
Is there a definitiv need to let it always be interactive?

**Comment by ahocevar** [comment]
@jhwegener I don't see how interactivity would be confusing. It's an improvement that all users should benefit from.

**Comment by ahocevar** [comment]
@felixveysseyre, please submit a [CLA](https://github.com/openlayers/cla) so we can merge this.

**Comment by felixveysseyre** [comment]
@ahocevar, I just submitted my CLA.

**Pull request merged**
