### PR TITLE
fixed the degreesToStringHDMS_() function to promote a seconds value …

### PR DESCRIPTION
**Pull request by rjackson64840**
…of 60 up to the next minute

see issue:  https://github.com/openlayers/openlayers/issues/5827

### CODE REVIEW

**Comment by ahocevar** [comment]
Thanks @rjackson64840! Can you please submit a [CLA](https://github.com/openlayers/cla) so we can merge this?

**Comment by rjackson64840** [comment]
Will do next week when I'm back in the office.  

Sent from my Fire

On January 28, 2017, at 9:15 AM, Andreas Hocevar <notifications@github.com> wrote:

Thanks @rjackson64840! Can you please submit a CLA so we can merge this?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or mute the thread.￼

{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/openlayers/openlayers","title":"openlayers/openlayers","subtitle":"GitHub repository","main_image_url":"<a href="https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png">https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png</a>","avatar_image_url":"<a href="https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png">https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png</a>","action":{"name":"Open in GitHub","url":"<a href="https://github.com/openlayers/openlayers">https://github.com/openlayers/openlayers</a>"}},"updates":{"snippets":[{"icon":"PERSON","message":"@ahocevar in #6410: Thanks @rjackson64840! Can you please submit a [CLA](<a href="https://github.com/openlayers/cla">https://github.com/openlayers/cla</a>) so we can merge this?"}],"action":{"name":"View Pull Request","url":"<a href="https://github.com/openlayers/openlayers/pull/6410#issuecomment-275853700">https://github.com/openlayers/openlayers/pull/6410#issuecomment-275853700</a>"}}}

**Comment by marcjansen** [comment]
Looks good to me as well. I think it was me who introduced the tests with basically wrong expectations. My bad.

**Comment by fredj** [comment]
@openlayers/core: have we received the CLA from @rjackson64840 ?

**Comment by rjackson64840** [comment]
I have to get the formed signed by someone at work and that person is out
sick today.

**Comment by rjackson64840** [comment]
I have the CLA now.  How/where do I submit it?

Russ



On Tue, 31 Jan 2017 10:12:29 -0600, Frédéric Junod  
<notifications@github.com> wrote:

>
> @openlayers/core: have we received the CLA from @rjackson64840 ?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub, or mute the thread.



-- 
Using Opera's revolutionary email client: http://www.opera.com/mail/

---
This email has been checked for viruses by Avast antivirus software.
https://www.avast.com/antivirus

**Comment by tschaub** [comment]
@rjackson64840 if this is a [CCLA](https://github.com/openlayers/cla/blob/master/ccla.txt), you can email it to openlayers-cla < at > lists.osgeo.org.

**Pull request merged**
