### PR TITLE
Fix allow to pass apiOptions array to Google source

### PR DESCRIPTION
**Pull request by KenyStev**
This is mostly added to allow opt-in for new styles of google rebranding

closes https://github.com/openlayers/openlayers/issues/15862

### CODE REVIEW

**Comment by tschaub** [comment]
Thanks for the contribution, @KenyStev.

it looks like your editor is set up to make style changes that conflict with the rules for this project.  You can run `npm run lint -- -fix` to fix this.  See the developer doc for more details https://github.com/openlayers/openlayers/blob/main/DEVELOPING.md#style-guidelines

**Comment by KenyStev** [comment]
thanks @tschaub I thought I had resolved all the linter issues

**Comment by KenyStev** [comment]
Hi @tschaub I was wondering is there's an upcoming releases schedule with this change?

**Comment by marcjansen** [comment]
You could try installing `ol@dev` ... but this obviously has some caveats.

**Comment by RubSR** [comment]
> Hi @tschaub I was wondering is there's an upcoming releases schedule with this change?

+1

**Comment by ahocevar** [comment]
I'm going to publish v10.0.0 this weekend.

**Pull request merged**
