### PR TITLE
add ol.source.IIP, tests and example

### PR DESCRIPTION
**Pull request by thhomas**
Related to #6165

### CODE REVIEW

**Comment by ahocevar** [comment]
If this is so similar to Zoomify, wouldn't it make sense to make Zoomify more flexible to also support IIP, and maybe call it DeepZoom instead?

**Comment by thhomas** [comment]
As you can read on [the IIPImage server page](http://iipimage.sourceforge.net/documentation/protocol/)  IIP, IIIFZoomify, DeepZoom seems to be different protocols (even if quite similar). 
Basically, we would just need to change the [createFromTemplate](https://github.com/thhomas/openlayers/blob/iip-source/src/ol/source/zoomify.js#L96) function to adapt to IIP url with template `&JTL={z},{tileIndex}`

**Comment by ahocevar** [comment]
Cool. We'd accept a pull request that adds a `{tileIndex}` placeholder to `ol.source.Zoomify`. Then you could use a configuration like this to get images from your server:
```js
new ol.source.Zoomify({
  url: ''http://vips.vtech.fr/cgi-bin/iipsrv.fcgi?FIF=/mnt/MD1/AD00/plan_CHU-4HD-01/FOND.TIF&WID=256&JTL={z},{tileIndex}',
  // ...
});
```
If you create such a pull request, please make sure to add appropriate documentation to mention the new supported protocol and how to use it.

**Comment by thhomas** [comment]
moved to #7221

**Pull request closed without merging**
