### PR TITLE
Only test ol.interaction.DragAndDrop if FileReader is supported

### PR DESCRIPTION
**Pull request by fredj**

### CODE REVIEW

**Comment by ahocevar** [comment]
I'm wondering about the decreased test coverage. Could it be possible that the feature detection returns a false negative for FileReader? Because it looks like Coveralls was previously able to run the tests, and does not run them any more.

**Comment by fredj** [comment]
In phantomjs, `typeof FileReader` is `"object"`, not `"function"`.
Same goes for `typeof ArrayBuffer`.

**Comment by fredj** [comment]
I will change the test to `'FileReader' in window`

**Comment by fredj** [comment]
Thanks for the review

**Pull request merged**
