### PR TITLE
Pass destination extent to avoid garbage generation

### PR DESCRIPTION
**Pull request by fredj**
An other small memory optimization

### CODE REVIEW

**Comment by tschaub** [comment]
The [test failures](https://travis-ci.org/openlayers/openlayers/builds/338068608) look related.

**Comment by fredj** [comment]
Yes, the test failure is related.
When there's no intersection between the extents, the function returns an empty entent: `[Infinity, Infinity, -Infinity, -Infinity]`. But if an `opt_extent`is provided, this value is returned instead of an empty extent

**Comment by fredj** [comment]
I've added a commit to fix this `getIntersection` issue

**Comment by fredj** [comment]
Thanks for the review

**Pull request merged**
