### PR TITLE
Allow interpolation to be configured for data tile sources

### LINKED ISSUE #13100: Respect tile source's imageSmoothing setting when using WebGLTile renderer
When zoomed in the Sea Level example shows a pixelated edge to the sea, corresponding to the pixels in the DEM.  Although, being an old example, this is implemented via a prerender event, where there is no reprojection this is equivalent to the `imageSmoothing: false` setting.  Without it image smoothing distorts the pixel values and thin lines of "sea" are visible along some contours, especially at 3107 meters.  Although such lines are not obvious in the WebGL Sea Level example, some distortion can be demonstrated with exaggerated sea level values - slightly south of the opening extent (in Chrome and Edge) a row of pixels (possibly at a tile boundary) can appear above the sea when the map is panned https://codesandbox.io/s/webgl-sea-level-forked-bn9dw  It would be easy to support the source's `imageSmoothing: false` setting if the renderer passed it to the `TileTexture` which could then use `gl.NEAREST` instead `gl.LINEAR` for its `gl.TEXTURE_MIN_FILTER` and `gl.TEXTURE_MAX_FILTER` configuration https://codesandbox.io/s/webgl-sea-level-smoothing-disabled-5vnj3  Currently only `TileImage` sources support the `imageSmoothing` option - are there any scenarios where it might be necessary to add support for `DataTile` and `GeoTIFF`?

### PR DESCRIPTION
**Pull request by tschaub**
This branch adds a boolean `interpolate` option for data tile sources.  By default, values are not interpolated when resampling – the nearest neighbor value is used.  If set to true, linear interpolation is used.  When using the WebGL tile layer renderer, style expressions will have access to pixel values directly from the data source if `interpolate` is false.  This is especially important for non-continuous data sources or any source that represents discrete data values.

**Update**: Based on discussion below, I've deprecated the `imageSmoothing` option for sources in favor of a new `interpolate` option.  The `imageSmoothing` option can still be used, but will be removed in the next major release.

Previously, all sources had a (non-API, internal only) `source.getContextOptions()` method.  This returned properties that are specific to the Canvas 2d rendering context.  Instead, sources now have a (non-API, internal only) `getInterpolate()` method.  The previous `source.getContextOptions()` method was only used to control whether data was interpolated during resampling.  The new `source.getInterpolate()` method now controls this.

The `IMAGE_SMOOTHING_DISABLED` object has been moved from `ol/source/common.js` to the `ol/renderer/canvas/common.js` module – since it represents properties that are conditionally applied to the Canvas 2d rendering context.

I've added tests to demonstrate that the deprecated `imageSmoothing` option still works for sources where it was used previously.

Fixes #13100.

### CODE REVIEW

**Review by jahow — APPROVED** [review]
Thanks! Code looks good and all my tests were fine. I have two questions on this PR:

* this changes the default sampling behavior for DataTiles but not for the other tile sources relying on images, as I understand it this is on purpose since linear interpolate can cause visual artifacts, is that right?

* if I'm not mistaken the `interpolate` option will have no effect for layers that are not relying on a WebGL renderer; on the other hand the `imageSmoothing` works only for canvas-based renderers. Shouldn't these two options be made into one? so basically use `imageSmoothing` everywhere instead of introducing `interpolate`?

I'm approving since everything looks good otherwise and it's probably just a matter of clarifications, thanks :)

**Comment by tschaub** [comment]
> * this changes the default sampling behavior for DataTiles but not for the other tile sources relying on images, as I understand it this is on purpose since linear interpolate can cause visual artifacts, is that right?

Yes.  This change only adds the `interpolate` option to data tile sources, and the default behavior for those sources is now to avoid interpolation.  When rendering data tile sources in a WebGL tile layer, style expressions have access to the original data values by default.  The GeoTIFF source sets `interpolate: true`, so the default behavior has not changed.  I'll add a note to clarify that for "bare" data tile sources, the default behavior has changed.

> * if I'm not mistaken the `interpolate` option will have no effect for layers that are not relying on a WebGL renderer; on the other hand the `imageSmoothing` works only for canvas-based renderers. Shouldn't these two options be made into one? so basically use `imageSmoothing` everywhere instead of introducing `interpolate`?

Just my personal opinion, but I think it is a mistake to model an abstraction after a single specific implementation.  For example, I think giving a tile source an `imageSmoothing` option that corresponds to the Canvas 2d context's `imageSmoothingEnabled` property is a mistake.  If the default tile layer renderer at the time of #10429 had been the WebGL, someone might have been tempted to name this property `textureMinMagFilterLinear` or something instead.  Names like this become awkward as we have additional implementations or otherwise broaden the use cases.  For a data tile source and for an image tile source, I think a name like "interpolate" makes sense.  I think "imageSmoothing" is awkward when describing how values for data tile sources are over- or under-sampled.

I'd be happy to add `interpolate` as an option to all sources and to mark `imageSmoothing` as deprecated.  Or if others prefer it the other way around, I can live with renaming `interpolate` to `imageSmoothing` now and then renaming it to `interpolate` in the next major release.

**Comment by ahocevar** [comment]
@tschaub I think if you could add an `interpolate` option to all sources and mark `imageSmoothing` as deprecated, that would be great.

**Comment by tschaub** [comment]
I've deprecated the `imageSmoothing` option, added `interpolate` in its place, and documented the change.

**Comment by mike-000** [comment]
`lintear` is a recurring typo in the updated docs.  Also `with smoothing enabled` in the example description should be changed to `with interpolation enabled`.

**Comment by tschaub** [comment]
> `lintear` is a recurring typo in the updated docs

Thanks for the catch.  Corrected in the latest commit.

> Also `with smoothing enabled` in the example description should be changed to `with interpolation enabled`

Good point.  I updated the language in the example.  I also removed the opacity slider and the imagery layer that was only used on one of the two maps.  I think these things add confusion to the example.  Without them, I think it is clearer what the example is about.

Before:
image

After:
image

**Comment by mike-000** [comment]
There is a special case that is not covered here, the old `imageSmoothing: false` setting is needed to create 2d canvas ReprojTiles without interpolation of the RGB bands, but when using a WebGLTile layer the resulting ReprojTiles can still be styled by interpolation of the calculated Float elevation values https://codesandbox.io/s/disable-image-smoothing-forked-t78lq?file=/main.js  Since that only applies to WebGL I think that would best be handled by a `interpolateAfterReprojection` or similar option on `ol/layer/WebGLTile` in a follow up PR which also adds `forEachLayerAtPixel` to WebGL.

**Comment by tschaub** [comment]
@mike-000 - I think we should avoid adding another source option related to resampling.  If we want to always avoid interpolation/smoothing during reprojection, let's make that change.

I'm going to merge this as is.  If there are additional problems that need addressing, I think it would be best to open separate issues for each, and we can discuss the appropriate solution.

**Comment by mike-000** [comment]
> @mike-000 - I think we should avoid adding another source option related to resampling. If we want to always avoid interpolation/smoothing during reprojection, let's make that change.


The defaults are correct, in most cases `ReprojTiles` are produced for the view zoom level even if the source being reprojected has fewer zoom levels, so changes would have no effect.  In the special case where `ReprojTiles` are being overzoomed and interpolated as Float values it can be done using a `DataTile` source loading `ReprojTile` canvases as data, although the `source.getTile()` method needed is not documented in the API.  https://codesandbox.io/s/disable-image-smoothing-forked-em6pi?file=/main.js

**Pull request merged**
