### PR TITLE
Fixes extent calculation in WMTS optionsFromCapabilities when BoundingBox exists

### PR DESCRIPTION
**Pull request by amir-ba**
As mentioned  in #11350 when creating the extent, the WMTS optionsFromCapabilities dose not consider the Wgs84BoundingBox. This pull request attempts to fix this by using the Wgs84BoundingBox extent in cases where it exists.

### CODE REVIEW

**Comment by ahocevar** [comment]
@amir-ba A minimal fix would look something like this:
```diff
diff --git a/src/ol/format/WMTSCapabilities.js b/src/ol/format/WMTSCapabilities.js
index 9e72eb213e..9dceae171d 100644
--- a/src/ol/format/WMTSCapabilities.js
+++ b/src/ol/format/WMTSCapabilities.js
@@ -103,7 +103,7 @@ const LAYER_PARSERS = makeStructureNS(
   makeStructureNS(OWS_NAMESPACE_URIS, {
     'Title': makeObjectPropertySetter(readString),
     'Abstract': makeObjectPropertySetter(readString),
-    'WGS84BoundingBox': makeObjectPropertySetter(readWgs84BoundingBox),
+    'WGS84BoundingBox': makeObjectPropertySetter(readBoundingBox),
     'Identifier': makeObjectPropertySetter(readString),
   })
 );
@@ -196,6 +196,7 @@ const TMS_PARSERS = makeStructureNS(
   makeStructureNS(OWS_NAMESPACE_URIS, {
     'SupportedCRS': makeObjectPropertySetter(readString),
     'Identifier': makeObjectPropertySetter(readString),
+    'BoundingBox': makeObjectPropertySetter(readBoundingBox),
   })
 );
 
@@ -304,9 +305,9 @@ function readResourceUrl(node, objectStack) {
 /**
  * @param {Element} node Node.
  * @param {Array<*>} objectStack Object stack.
- * @return {Object|undefined} WGS84 BBox object.
+ * @return {Object|undefined} BBox object.
  */
-function readWgs84BoundingBox(node, objectStack) {
+function readBoundingBox(node, objectStack) {
   const coordinates = pushParseAndPop(
     [],
     WGS84_BBOX_READERS,
diff --git a/src/ol/source/WMTS.js b/src/ol/source/WMTS.js
index b61af5eee2..b618a1edbc 100644
--- a/src/ol/source/WMTS.js
+++ b/src/ol/source/WMTS.js
@@ -6,6 +6,7 @@ import TileImage from './TileImage.js';
 import WMTSRequestEncoding from './WMTSRequestEncoding.js';
 import {appendParams} from '../uri.js';
 import {assign} from '../obj.js';
+import {containsExtent} from '../extent.js';
 import {createFromCapabilitiesMatrixSet} from '../tilegrid/WMTS.js';
 import {createFromTileUrlFunctions, expandUrl} from '../tileurlfunction.js';
 import {equivalent, get as getProjection} from '../proj.js';
@@ -479,7 +480,9 @@ export function optionsFromCapabilities(wmtsCap, config) {
   const tileSpanX = matrix.TileWidth * resolution;
   const tileSpanY = matrix.TileHeight * resolution;
 
-  const extent = [
+  const matrixSetExtent = matrixSetObj['BoundingBox'];
+
+  let extent = [
     origin[0] + tileSpanX * selectedMatrixLimit.MinTileCol,
     // add one to get proper bottom/right coordinate
     origin[1] - tileSpanY * (1 + selectedMatrixLimit.MaxTileRow),
@@ -487,6 +490,10 @@ export function optionsFromCapabilities(wmtsCap, config) {
     origin[1] - tileSpanY * selectedMatrixLimit.MinTileRow,
   ];
 
+  if (!containsExtent(matrixSetExtent, extent)) {
+    extent = matrixSetExtent;
+  }
+
   if (projection.getExtent() === null) {
     projection.setExtent(extent);
   }
```
I think the wrapX handling you added makes sense, and could be added here too.

Would you be able to modify your pull request like this? If not let me know, then I'll start a new one.

**Comment by amir-ba** [comment]
thank you @ahocevar for your suggestion I will fix my pull request shortly.

**Comment by ahocevar** [comment]
Thank you, @amir-ba

**Comment by amir-ba** [comment]
@ahocevar can you tell why the tests are failing? I cant quite figure out what to fix to make them work.

**Comment by ahocevar** [comment]
@amir-ba The failing test are due to a random problem that's unrelated. I restarted all tests. They should all be green in a few minutes.

**Comment by amir-ba** [comment]
I can add the tests, but since Its my first time contributing to this repo, I am not clear about the test data structures. should I extent the exiting [capabilities_wgs84.xml](https://github.com/openlayers/openlayers/blob/main/test/spec/ol/format/wmts/capabilities_wgs84.xml) with a layer that has such configuration and add the tests or do you have a better Idea?

**Comment by ahocevar** [comment]
Thanks for your continued effort on this, @amir-ba! You could save a copy of https://www.basemap.at/wmts/1.0.0/WMTSCapabilities.xml in the `test/spec/ol/format/wmts/` folder and use that for the tests.

**Comment by ahocevar** [comment]
@amir-ba Thanks for your work on this so far! Do you think you'd be able to add the test as discussed above, or do you need additional guidance?

**Comment by FrankyBoy** [comment]
This issue is still unresolved and should not have been closed.

**Comment by amir-ba** [comment]
@ahocevar , sorry for the Absence, can I still add my test and push the current develop into this feature branch?

**Comment by MoonE** [comment]
Feel free to continue working on this PR here.

**Comment by amir-ba** [comment]
@MoonE can you please restart the failing spec test here.

**Review by ahocevar — APPROVED** [review]
Thanks, @amir-ba

**Comment by amir-ba** [comment]
> Thanks, @amir-ba

Thanks for your review🎉🎉

**Pull request merged**
