### PR TITLE
Handle setActive(false) on an interaction without map

### PR DESCRIPTION
**Pull request by fredj**

### CODE REVIEW

**Comment by fredj** [comment]
I've restarted the build and coverage is back to normal.

**Comment by fredj** [comment]
@ahocevar what "Should just be a comment" ?

**Comment by ahocevar** [comment]
@fredj I had revoked my disapproval, and GitHub asked me why: I just wanted to comment, and not disapprove.

So please merge.

**Comment by fredj** [comment]
Thanks for the review

**Pull request merged**
