### PR TITLE
Uniformly grayscale controls

### PR DESCRIPTION
**Pull request by tschaub**
Following up on https://github.com/openlayers/openlayers/pull/9013#issuecomment-442613882, this updates the style for controls to be uniformly grayscale.

image

### CODE REVIEW

**Comment by MoonE** [comment]
These css variables should be prefixed with `ol-` to avoid any name clashes.

**Comment by tschaub** [comment]
> These css variables should be prefixed with `ol-` to avoid any name clashes.

Good point.  Done.

**Comment by MoonE** [comment]
The controls kind of disappear against a white background.
image

Maybe use a darker color for the subtle background?
`--ol-subtle-background-color: rgba(128, 128, 128, .25);`
image

**Comment by tschaub** [comment]
> The controls kind of disappear against a white background.

Agreed.  I darkened the background.  I also reduced the margin on the controls so the background isn't as big.

image

I think this looks tighter than the 2px background.

**Review by ahocevar — APPROVED** [review]
So beautiful!

**Pull request merged**
