### PR TITLE
Avoid disposal of tiles that are still needed

### LINKED ISSUE #10465: Pieces of map do not appear when a tile layer is being reprojected.
**Describe the bug**

When zooming in and out on a map with a reprojected Tile layer, sometimes there are white areas. This turns out to be because the underlying Tile object has been disposed and is therefore excluded from the stitching process to make the source canvas for the reprojection.

**To Reproduce**
1. Go to https://pskreporter.info/testaeqd.html
2. Zoom in and out a bunch and pan around
3. See error -- example below

image

**Expected behavior**
No white area.

It seems that just modifying the loop in ol.reproj.Tile to include tiles in the ABORT state doesn't actually work -- that causes problems later on. I suspect that these tiles should not be disposed, or that some piece of code should refetch them...

### PR DESCRIPTION
**Pull request by ahocevar**
Fixes #10465.

### CODE REVIEW

**Comment by pjsg** [comment]
Unfortunately, this doesn't solve the problem. When I run this, I see three TileCaches being created. The first two are of size 80 and the last is the (increased) 400. It fairly quickly starts to overflow (at least one of) the size 80 caches. 

image

**Comment by pjsg** [comment]
Question: when the tiles get flushed fro the cache, why are they 'disposed'? If this is the last reference to them, then the garbage collector will get rid of them, and if there are remaining references then it will cause problems if the tile contents are eliminated.

**Comment by ahocevar** [comment]
This is actually a very legitimate question @pjsg. The root of the evil here is an old design flaw: a map-wide tile queue, paired with a per-source tile cache. I'm going to experiment a bit and see how much effort it would be to get rid of the ABORT state of tiles, while still being able to abort loading tiles that are no longer being used.

**Comment by ahocevar** [comment]
@pjsg One interesting observation in your issue description is that of invalid tile coordinates. Were you able to track down where these come from? It would be good indeed if we could avoid caching (or even creating) those.

**Comment by pjsg** [comment]
This is the failing function at the time of adding a negative x coordinate (sorry for the images, but I couldn't figure out how to get the variable values copied!)

image
image

It appears that there is something wrong with the calculated extent. In particular the `layerState` doesn't have an extent associated with it. The extent of my view is (approx) [-2e7, -2e7, 2e7, 2e7] and the calculated extent is much bigger than that -- and this is why (I think) that we are trying to render tiles which are outside the view's extent.

**Comment by ahocevar** [comment]
I am closing this in favor of #10478.

**Pull request closed without merging**
