### PR TITLE
Named Map export for ol/Map

### PR DESCRIPTION
**Pull request by raiyni**
title

### CODE REVIEW

**Comment by raiyni** [comment]
Random test failure?

**Comment by tschaub** [comment]
I restarted them.

**Comment by tschaub** [comment]
@raiyni - instead of merging and trying to fix the conflicts in a merge commit, we prefer that you rebase your feature branch on master, fixing any conflicts in the commits that caused them.

So:

    git pull --rebase openlayers master

And then fix any commits, following instructions to add commits and continue the rebase.  And then:

    git push --force origin map

This assumes that you have the OpenLayers repo set up as the `openlayers` remote and your own fork as `origin`.

**Comment by tschaub** [comment]
Not related, but you should also configure your `user.email` with one that GitHub knows about:

    git config user.email "one-that-github-knows-about@mail.com"

**Comment by raiyni** [comment]
Noted.

**Comment by tschaub** [comment]
@raiyni - I took the liberty of rebasing and getting rid of the conflicts.  Thanks for the work on this.  I'll merge when it is green.

PS - if you want a copy of these same commits locally, don't `git pull` - instead `git fetch origin && git reset --hard origin/map`.

**Comment by raiyni** [comment]
I did that. The 4th commit didn't trigger a new check?

**Pull request merged**
