### PR TITLE
Update bootstrap, cleanup css, make pages more responsive

### PR DESCRIPTION
**Pull request by ahocevar**
Creating this pull request on behalf of @jipexu. Replaces and closes #11262, which has a broken commit history due to unlucky rebase attempts.

### CODE REVIEW

**Comment by jipexu** [comment]
deploy preview failed ?

**Comment by ahocevar** [comment]
@jipexu The deploy preview will be fixed when #11309 is merged. Thanks for verifying that the changes in this pull request match the ones in #11262.

I'll be giving this a thorough review tomorrow. Thanks a lot for your effort on this, especially for the huge css cleanup!

**Comment by jipexu** [comment]
@ahocevar thanks i  just note that in this pull request  is 23 files modified and 26 in the original ? i have not identified what file are missing and if we need them ? i dont know how to compare quicly to know this ...

**Comment by ahocevar** [comment]
Thanks for double-checking @jipexu. I removed the three other fonts now. For your information: git only creates folders that hold files, because it does not have the concept of folders. So we should be fine now.

**Comment by ahocevar** [comment]
Deploy preview is now available: https://deploy-preview-11310--ol-site.netlify.app

**Comment by jipexu** [comment]
@ahocevar thanks for your help and cool it's look good !
 (next time i will want to finish the API layout to make it more lisible on small screen in clear adapt or remove the "imbricated tabular" html architecture ... :-)

**Pull request merged**
