### PR TITLE
Cache hit detect indexes and check closest pixels first.

### PR DESCRIPTION
**Pull request by MoonE**
replaces / closes #11782

@ahocevar Could you explain what kind of user experience problems you were trying to solve by checking the center first?
After looking at this some more as far as I understand it the order in which features are checked is determined by the render order, not by how close the user clicked to a feature.

Using an array with indexes still makes sense and looking at the closest pixels first will probably find a hit sooner (if it exists) but I think the user experience will be the same.

### CODE REVIEW

**Comment by ahocevar** [comment]
Thanks for your research @MoonE! You are right, my thinking was wrong. What I wanted to achieve is that the feature closest to the pointer gets highlighted when using `forEachFeatureAtPixel()` to get the first (i.e. most relevant) feature. Like you found out correctly, the way hit tolerance handling is implemented, this won't be the case. I created an example that shows the problem: https://github.com/ahocevar/openlayers/commit/7119412caeb72b27d4c8232f33a327c0f28b0b74.

Regardless of that, I think this pull request is a good improvement.

While we're at it, do you see a good way to fix this problem? I think we could collect all matching features and sort them in `ExecutorGroup#forEachFeatureAtCoordinate`, before executing the callback passed to that function. But that could potentially complicate things a fair bit.

**Comment by MoonE** [comment]
I tried your suggestions in  https://github.com/MoonE/openlayers/tree/hitdetect-closest.
This works per layer at the moment The matches would need to be collected one level above to make it work across all layers.
Would need to be implemented in a similar way for the other renderers.
Please let me know if this looks promising.

For features with direct hits the callback is called immediately, the other features are collected and sorted by distance before calling the callback with them. 
If a truthy value is returned from the callback for a feature that was directly hit the hit detection is stopped early, like before.

**Comment by ahocevar** [comment]
This looks great, @MoonE! Less complicated than I thought. It would be awesome if you could finish that as you proposed - by making it work across layers and for the other renderers. I'd also be willing to take on some of the remaining tasks. Just let me know.

This is a significant usability improvement, thanks a lot for your effort!

**Comment by MoonE** [comment]
This should now work for `VectorLayerRenderer` and `VectorTileLayerRenderer`.
`CanvasLayerRenderer.getDataAtPixel` and  `WebGLPointsLayerRenderer.forEachFeatureAtCoordinate` ignore the hitTolerance, so I did not change anything there.
Should hitTolerance be used in the those two?

`MapRenderer.hasFeatureAtCoordinate` is kind of inefficient now when no direct hit is made because it still collects all features.

I did not see more places that need to be changed.

**Comment by MoonE** [comment]
Could the executor group be skipped entirely if `tileContainsCoordinate` is false (line 438)? Its value only changes per tile.
Or is it broken with declutter and the check should be removed (see line 411)? 
https://github.com/openlayers/openlayers/blob/8cc78acde90c9e4b1751d16aa388b8d1cd073224/src/ol/renderer/canvas/VectorTileLayer.js#L405-L454

**Comment by ahocevar** [comment]
> CanvasLayerRenderer.getDataAtPixel and WebGLPointsLayerRenderer.forEachFeatureAtCoordinate ignore the hitTolerance, so I did not change anything there.
Should hitTolerance be used in the those two?

No, that's ok to leave it unchanged.

**Comment by ahocevar** [comment]
> Could the executor group be skipped entirely if tileContainsCoordinate is false (line 438)? Its value only changes per tile.
Or is it broken with declutter and the check should be removed (see line 411)?

Thanks for spotting this flaw! Now that I look at it, I would say the executor group can be skipped entirely in that case.

**Comment by MoonE** [comment]
OK, thanks. Now it only checks for tiles containing the provided coordinate.

Another question:
Shouldn't the check if the tile contains the coordinate account for the hitTolerance?

**Comment by ahocevar** [comment]
> Shouldn't the check if the tile contains the coordinate account for the hitTolerance?

Good question. Thinking about it, I would say it cannot hurt. Usually vector tiles use a buffer where features are repeated on neighboring tiles, so it should not strictly be necessary. But we cannot take that for granted, because we don't know how the tiles we process were generated.

**Comment by MoonE** [comment]
This is ready for review. Thank you for your help with this so far, @ahocevar.

**Comment by ahocevar** [comment]
This looks excellent, @MoonE! Unfortunately the merging of #11781 caused conflicts in this pull request. Would you be able to resolve those, or do you want me to look into it?

**Comment by MoonE** [comment]
I added the template argument to the new HitMatch typedef and got an error that T|void is not asignable to T.
I then changed the signature of the forEachFeatureAtPixel function from T|void to T|undefined and added this also to the inline featureCallback functions. I hope this makes sense.

**Comment by ahocevar** [comment]
This makes perfect sense. Thanks again for your effort on this, @MoonE!

**Review by ahocevar — APPROVED** [review]
Great work, @MoonE. Thanks and please merge!

**Comment by MoonE** [comment]
Thanks for your help with this, @ahocevar.

**Pull request merged**
