### PR TITLE
Fix ol.interaction.Draw~createRegularPolygon

### PR DESCRIPTION
**Pull request by iamplex**
fix [#8394](https://github.com/openlayers/openlayers/issues/8394)

### CODE REVIEW

**Comment by ahocevar** [comment]
Can you add tests for this please? Also to prove that it works with all cases of 2*n+1 edges?

**Comment by iamplex** [comment]
For prove that it works with all cases of 2*n+1 edges, just make sure the sketch of first coordinate(or last coordinate) always equals the mouse point coordinate, but i don't know how to get the mouse position in test case.

Could you provide an idea for this tests? I have no experience in unit test, but i still happy and learn mocha for that

**Comment by ahocevar** [comment]
Thanks for looking into tests. To get the pointer coordinate, you can modify the existing `simulateEvent` function to return the simulated event. Then you can do something like
```js
const event = simulateEvent('pointermove', 80, 80);
const pointerCoordinate = map.getEventCoordinate(event);
```

**Comment by iamplex** [comment]
Sorry, i try to add test case but always fail. Other problem, in local when i run `npm run test` or `npm run karma` it always build success, so i can't debug, that's why there are so many commit.

I think i need to take some time to learn unit tests. Thank you.

**Comment by ahocevar** [comment]
I took the liberty to add tests and simplify the calculation you introduced.

**Comment by iamplex** [comment]
Nice simplify!

**Pull request merged**
