### PR TITLE
Make zDirection option available for all tile sources

### LINKED ISSUE #12351: Description of zDirection
**Describe the bug**
The description of the `zDirection` option in tile sources and direction option for the `getZForResolution` method of tilegrids seems to be wrong.

> If 1, the nearest lower resolution will be used. If -1, the nearest higher resolution will be used.

**To Reproduce**
https://codesandbox.io/s/simple-forked-g88d1

A direction of 1 results in the next lower z level which has a higher resolution

`input:  1 8.5 432.3931282735686  result: 8 611.49622628141`

A direction of -1 results in the next higher z level which has a lower resolution

`input: -1 8.5 432.3931282735686  result: 9 305.748113140705`

**Expected behavior**
The behaviour seems to be correct, but the description should reflect the behaviour.

### PR DESCRIPTION
**Pull request by mike-000**
Fixes #12351 and #12353

Update description of `zDirection` to clarify higher resolution (lower Z) and lower resolution (higher Z).
Add `zDirection` option to tile sources which do not already have it.

Also allow fractional values while keeping the existing default as 0. The midpoint between resolutions is a fractional zoom level z + 0.41503 with a zoom factor of 2, while most mapping clients change z level at z + 0.5. This can be achieved by specifying a `NearestDirectionFunction` to compare the resolution with one calculated for the zoom midpoint (or any other offset as required). This could be used where consistency with other client behaviour is desirable (e.g. raster tile sources in ol-mapbox-style) https://codesandbox.io/s/mapbox-raster-side-by-side-forked-zgsdt or where the content of tiles from a higher z viewed at the previous z + 0.41503 is not clearly legible while always enlarging lower z tiles would be excessive.

Add tests for fractional direction values.

### CODE REVIEW

**Review by ahocevar — COMMENTED** [review]
I really like this new feature, but "Fractional values give intermediate behavior." should be expanded to a sentence that reflects the gist of the pull request description, i.e. the formula and the recommended value to achieve a tile zoom level change at z + 0.5.

**Comment by ahocevar** [comment]
Looking at this closer, I find the calculation of the desired `zDirection` value quite unintuitive, due to the range of `-1` to `+1`. What if `linearFindNearest` would also accept a function `zDirection`:
```js
zDirection: (value, high, low) => value > low * Math.SQRT2 ? high : low
```
What do you think, @mike-000?

Also, it would maybe be better to document how this works in `TileGrid.getZForResolution`, and link to that from the sources where `zDirection` can be configured.

**Comment by mike-000** [comment]
Yes, I think a function would be useful as it could better handle non-standard tile grids with resolutions derived from paper maps such as 10, 25, 50, 100, etc. where the midpoint of the zooms would be slightly different at steps with zoom factor 2.5

```
const factor = (high - low) / low;
const midzoom = low * Math.sqrt(factor);
return value > midzoom ? high : low;
```

and in a situation like that much more understandable.

**Review by ahocevar — COMMENTED** [review]
I think it would be more intuitive if the function returned the same values/types as when provided a constant value, i.e. values greater than `0` for `high`, smaller than `0` for `low`, and maybe even `0` for the closest:
```js
function(value, high, low) {
  return value - low * Math.sqrt(high / low);
}
```

Regarding documentation, I think for the sources it could be shortened to something like
```js
/**
 * @property {number|import("../array.js").NearestDirectionFunction} [zDirection=0]
 * Choose whether to use tiles with a higher or lower zoom level when in between integer
 * zoom levels. See {@link module:ol/tilegrid/TileGrid~TileGrid#getZForResolution}.
 */
```

**Review by ahocevar — APPROVED** [review]
Thanks for your effort on this, @mike-000

**Pull request merged**
