### PR TITLE
[WIP] Renames class names to be more explicit

### PR DESCRIPTION
**Pull request by KaiVolland**
Changes the classnames to be more explicit.

This should be helpful when using intellisense or autmatic import functionality.

Addresses #9376

### CODE REVIEW

**Comment by tschaub** [comment]
I’m not clear on the justification for this.  For consistency, are we also planning to rename the exports from modules like ol/style.js?  If so, this is a breaking change and should have a clear justification.

**Comment by ahocevar** [comment]
> I’m not clear on the justification for this

An example would be to avoid IntelliSense trying to do this:
```js
import VectorTile from `ol/source/VectorTile`;
import VectorTile /* ! */ from `ol/layer/VectorTile`;
```

> For consistency, are we also planning to rename the exports from modules like ol/style.js?

I'd be hesitant to do this, but I agree it would be good for consistency.

**Comment by tschaub** [comment]
Maybe we have a different setup or workflow.  Here is how things currently work for me:
import

I don't have a problem with this, which is why I'm having a hard time understanding the problem that motivates this change.

This is personal preference, but I also like the readability of this (and feel that the longer names are clunky):
```js
import {Fill, Stroke, Style} from 'ol/style';
```

We're also talking about breaking everything like this (which I think would be unfortunate):
```js
import Map from 'ol/Map';
import {Tile} from 'ol/layer';
import {OSM, XYZ} from 'ol/source';

const url = 'https://example.com/{z}/{x}/{y}';

new Map({
  layers: [
    new Tile({source: new OSM()}),
    new Tile({source: new XYZ({url})})
  ]
});
```

**Comment by tschaub** [comment]
Seeing "IntelliSense auto import", I'm wondering if you are talking about a problem with a workflow using a specific plugin for VS Code.  I don't use an auto-import plugin, but I tried installing the two most popular results here https://marketplace.visualstudio.com/search?term=auto%20import&target=VSCode&category=All%20categories&sortBy=Relevance and couldn't get either to auto-import modules from `node_modules`.  Are you talking about a problem with one of these plugins?  Do you have a specific configuration?

Is the problem with

**Comment by ahocevar** [comment]
Ok. Sorry for the noise then. I‘m not using any plugins, just typing e.g. `new VectorTile(/* Auto-Import works */{source: new VectorTile( /* auto-import does not work */`.

@KaiVolland and @tschaub, sorry for wasting your time, looks like this change does not improve anything.

**Comment by ahocevar** [comment]
> We're also talking about breaking everything like this (which I think would be unfortunate):

None of those would break though.

**Comment by tschaub** [comment]
I appreciate the work you've done here @KaiVolland and definitely agree with @ahocevar's intent of making the library easier to use (with nice tooling like auto-import).

Right now we have some consistency in these things:

 * our file names (e.g. `ol/source/OSM.js`)
 * our default export names (`OSM`)
 * our named exports from "package" modules (e.g. `OSM` from `ol/source.js`)

I think this adds a bit of niceness to the dev story because things are guessable (if I see `ol/source/OSM.js` I can guess that I can `import {OSM} from 'ol/source'` and if I see an import named `OSM` I can guess that I can find a file named `OSM.js`).

This change looks like it is just about the default export names.  Which I agree doesn't break the API  and it sounds like it might fix something.  If making our default export names unique makes auto-import work for application developers, that sounds nice.  I can't reproduce the problem or verify the fix right now, but I don't doubt it.

If we make this change, I imagine the next suggestion (or one in the future) might be to regain the consistency we have now (between default export name, file name, and convenience named exports).  Maybe this won't happen, or maybe we won't do it, or maybe we will and it isn't a big deal (either way, slippery slope fallacy).

How about we leave this up here and I work on getting auto-imports working (I'd like that anyway)?

**Pull request closed without merging**
