### PR TITLE
Fix detection of activex support to work in IE11

### PR DESCRIPTION
**Pull request by szekerest**

### CODE REVIEW

**Comment by ahocevar** [comment]
Thanks! Can you confirm that tests still pass with this in major browsers, including IE8?

One improvement suggestion: It would even be nicer to only detect this once, e.g.
```js
OpenLayers.Format.XML.supportActiveX = (function() {
    return (Object.getOwnPropertyDescriptor &&
            Object.getOwnPropertyDescriptor(window, "ActiveXObject")) ||
            ("ActiveXObject" in window);
})();
```
Or maybe even without the anonymous function.

**Comment by szekerest** [comment]
Tested the approach in Chrome, Firefox and IE11. 
Need to find a PC which runs IE8.

**Comment by ahocevar** [comment]
Let me see if I can find that old WinXP VM of mine...

**Comment by ahocevar** [comment]
Works fine in IE8. @szekerest, are you able to implement the improvement I suggested above, and also use `OpenLayers.Format.XML.useActiveX` in `OpenLayers.Format.WPSExecute#write()`, like @bkiselka did?

**Comment by szekerest** [comment]
@ahocevar Modified the pull

**Comment by ahocevar** [comment]
Thanks for the continued effort on this @szekerest. Can you please submit a [CLA](https://github.com/openlayers/cla) so we can merge this?

**Comment by szekerest** [comment]
@ahocevar Signed

**Pull request merged**
