### PR TITLE
Constrain the center in zoomByDelta

### LINKED ISSUE #5824: Using zoom interactions should constrain center
Create a view with `extent: [0, 0, 0, 0]`.

Use the zoom interaction (mouse wheel or double click). 

The center is now outside the extent.

### PR DESCRIPTION
**Pull request by tchandelle**
Fix #5824

### CODE REVIEW

**Comment by ahocevar** [comment]
I'm not sure this fixes the problem. Here is what I tried
* Modified the `wms-tiled` example by setting the layer's extent also as view extent
* Zoomed out so I could see Central Europe
* Wheel-zoomed in
* Observed the center to be outside the view extent, like it is in master

**Comment by tchandelle** [comment]
@ahocevar are you using a trackpad?

**Comment by ahocevar** [comment]
Yes I am.

**Comment by tchandelle** [comment]
Can you test with this last commit? I can't test it myself.

**Comment by ahocevar** [comment]
Thanks @tchandelle, it works now. Great work as always!

**Pull request merged**
