### PR TITLE
Style updates for examples and API docs

### PR DESCRIPTION
**Pull request by tschaub**
Following up on #13908, this updates styles for examples and API docs.  Aside from code syntax highlighting, the one color is `#00AAFF` (the new brand color), and the rest is grayscale.  The included `logo-light.svg` and `logo-dark.svg` can be used over light and dark backgrounds.

New style for [API docs](https://deploy-preview-13917--ol-site.netlify.app/apidoc/):

image

New style for [examples](https://deploy-preview-13917--ol-site.netlify.app/examples/):

image

(The cookie consent form has colors that stray from the theme, but that will be removed in #13916.)

### CODE REVIEW

**Comment by MoonE** [comment]
Here 'HTML 5 Geolocation spec' is actually a link, but there is no visual distinction from normal text:
image
Unfortunately code formatting is also rather hard to make out, here 'change' is `code`:
image

I do like the reduced colors. Maybe a background color for code and and undefline for links would work?

**Comment by tschaub** [comment]
@MoonE - Thanks for the feedback.  I also thought that the links were not obvious enough and that the inline code style was too subtle.  I've updated both (and included screenshots in the descriptions).  The links now use the brand color and are decorated with an underline on focus or hover.  The inline code now has a background that contrasts with the default background.

**Review by ahocevar — APPROVED** [review]
I like the clean look. Thanks!

**Review by MoonE — APPROVED** [review]
Have you considered removing the background color from the big code boxes?
image

image

Either way it looks great, @tschaub

**Comment by jipexu** [comment]
Hi
Nice !!
Just a notice, I dont know why but all the link(internal) in the docs menu are not found ??
ie :   https://deploy-preview-13917--ol-site.netlify.app/doc/quickstart.html
== page not found
???

**Comment by tschaub** [comment]
> I dont know why but all the link(internal) in the Docs menu are not found ??

@jipexu - The branch preview builds don’t include all the docs currently - just the examples and API docs.

**Comment by MoonE** [comment]
I'm getting a 404 response for https://deploy-preview-13917--ol-site.netlify.app/examples/css/map-background.jpg
https://deploy-preview-13917--ol-site.netlify.app/examples/min-zoom.html

**Pull request merged**
