### PR TITLE
Add spatial reference inside geometry in EsriFormat

### PR DESCRIPTION
**Pull request by Sol1du2**
As mentioned on issue 6992, EsriFormat was adding the spatial reference
outside the geometry, failing to insert data via the Arcgis rest API.
The spatial reference should be inside the geometry.

### CODE REVIEW

**Comment by bartvde** [comment]
Oh sorry forgot to ask you about the CLA, have you already submmited one? If not, can you please do that?

**Comment by Sol1du2** [comment]
I have not. This is the first time I contribute to open source so I am still learning the "drill". :) 
Could you tell me how I can submit it? Thanks.

**Comment by bartvde** [comment]
@Sol1du2 see the details here: https://github.com/openlayers/cla TIA

**Comment by Sol1du2** [comment]
Thanks @bartvde !

Just a last question. I made this on company time, so I will be submitting a company CLA. Is the signature at the end suppose to be the CEO or myself, who did the work? Also, do I need to submit a CLA per pull request?

Thanks!

**Comment by bartvde** [comment]
No just one CLA is sufficient. It's also fine to do an ICLA, I do that and my contributons are also on company time

**Comment by bartvde** [comment]
If your company is fine with you doing an ICLA, that should be fine with us

**Comment by Sol1du2** [comment]
Thank you!
I talked with them and they asked me to do a corporate CLA but I could sign it myself since I did the work. I have submitted it to the e-mail listed in the document.

**Comment by bartvde** [comment]
thank you

**Comment by marcjansen** [comment]
I am late to the party, but agree with @bartvde: very nice first PR!

@Sol1du2, any chance you might make this 100% by providing a small unit test in a follow up PR?
 That'd be so nice.

**Comment by Sol1du2** [comment]
@marcjansen Yes, I'll add a unit test, when I have some free time. :) Should I make a new pull request for it?

**Pull request merged**
