### PR TITLE
Utilize `deviceorientationabsolute` event.

### PR DESCRIPTION
**Pull request by nagytech**
See #6974.

I have further changes to address the gamma offset, but will commit them tomorrow, possibly under separate pull request to facilitate easier testing.

### CODE REVIEW

**Comment by fredj** [comment]
I'm not in favor of adding a non-standard feature in the API. Can you listen to this event in you application code ?

Side note: I don't think that `ol.DeviceOrientation` (as well as `ol.control.FullScreen`) has it's place in OpenLayers: it's only some glue around DOM APIs and is not related to maps

**Comment by bartvde** [comment]
@fredj do you think we should consider removing those before we do OL5 ?

**Comment by ahocevar** [comment]
> Side note: I don't think that ol.DeviceOrientation (as well as ol.control.FullScreen) has it's place in OpenLayers: it's only some glue around DOM APIs and is not related to maps

Agreed. I'd be in favor of removing it.

**Comment by fredj** [comment]
@bartvde yes, I'm willing to remove it but keep the example and use the DOM API

**Comment by fredj** [comment]
See #7189

**Pull request closed without merging**
