### PR TITLE
fix: Image layer load big svg with width and height will not be see a…

### PR DESCRIPTION
**Pull request by fushengyao**
…nd imageSize property is invalid

### CODE REVIEW

**Comment by mike-000** [comment]
If you have an SVG without width and height attributes this approach will not work with Firefox.  See https://github.com/openlayers/openlayers/issues/14788#issuecomment-1575561642  There is a similar issue with unsized SVGs in Icon styles.  The `imageSize` option was originally intended for Internet Explorer which could not detect the size of an SVG.

**Comment by fushengyao** [comment]
> If you have an SVG without width and height attributes this approach will not work with Firefox. See [#14788 (comment)](https://github.com/openlayers/openlayers/issues/14788#issuecomment-1575561642) There is a similar issue with unsized SVGs in Icon styles. The `imageSize` option was originally intended for Internet Explorer which could not detect the size of an SVG.

Thank you for your suggestion, but my scenario may not be described clearly. My SVG file has attribute widths and heights, but the values are very large. width=52354, height=33614, and I do not want to change this size, which will cause the displayed SVG to be blurry. Before submitting the pull request, I printed the width and height of the canvas in the getImage method of the ol/image.js file, which are 52354 and 33614, This will result in not being able to see the specific content of the SVG file, so I added a check to see if imageSize has been set, so that after fixing it, it can meet my usage scenarios

**Review by ahocevar — CHANGES_REQUESTED** [review]
Thanks for your contribution, @fushengyao. I like the way you are enhanding the `imageSize` property. Would you be able to add a test, and update the documentation to reflect the new enhanced behavior?

**Comment by mike-000** [comment]
Yes, this will help prevent exceeding canvas limits in your situation

The change will also make the current handling of `imageSize` in ol/source/ImageStatic `handleImageChange` obsolete so

      let imageWidth, imageHeight;
      if (this.imageSize_) {
        imageWidth = this.imageSize_[0];
        imageHeight = this.imageSize_[1];
      } else {
        imageWidth = image.width;
        imageHeight = image.height;
      }

could be simplified to

      const imageWidth = image.width;
      const imageHeight = image.height;

**Comment by fushengyao** [comment]
I have added new test cases and updated the comments on the imageSize attribute in ol/images.js. In the test cases, due to the inconvenience of publishing SVG, I have removed many paths, which appear vague and do not affect the actual effect. If you need to download it, please download it in a timely manner as SVG may be deleted in the future

**Comment by mike-000** [comment]
For testing purposes you could take a copy of one of the existing test files `cross.svg` or `me0.svg` and edit the width and height attributes.  I think you need to test with an `imageSize` which matches the extent aspect ratio such as `[900, 600]` as well as one which does not such as `[800, 600]`.  Apart from some differences in blurring I would expect these to look similar when rendered, but I get very different results using your code.

**Comment by fushengyao** [comment]
Firstly, I modified the test case and added a new test. svg. When the width and height were adjusted significantly, the content of the svg would shift to the upper left corner. However, after testing, expected. png did not capture the entire rendered area, so I adjusted the center point of the view so that I could only see the content of the svg after rerunning the test case. However, when I switched to the large svg I used for local debugging, I obtained the same result, Based on this test result, if imageSize is not set, no content will be captured

Secondly, I created a new image static. html locally to test the modified test. If you do not set imageSize, you will not see any content in the viewport area, and the same result will be obtained for both SVG and SVG that already have a large width and height

**Comment by fushengyao** [comment]
Ok,thanks

**Pull request closed without merging**
