### PR TITLE
Avoid unexpected behavior with Icon width and height

### LINKED ISSUE #14575: Wrong scale value in cloned icons
**Description**
When an Icons' scale is set as a number and you clone it, the scale of the clone got an array with different values as his scale.
This happens because by calling setScale() an Icon receives an height and width. So by calling the constructor within clone() the scale is set to an array though it was set a number before. This results always in a wrong value for the scale value.
Even the documentation states that height and width can't be used with scale. This seems to be a conflict.

**Steps To Reproduce**
1. Create an Feature with an Icon without height and width
2. Scale the icon with a number Value
3. Clone the icon
4. You will see there is an array as scale value in the cloned style

**Expected behavior**
The cloned icon keeps the same scale as its original especially the same datatype.

### PR DESCRIPTION
**Pull request by ahocevar**
Fixes #14575 
Supersedes #14601

Only calculate the scale from the provided `width` and `height` when the image size is known.

### CODE REVIEW

**Comment by mike-000** [comment]
What happens if scale is set after loading, e.g.

```
      original.getImage(1).addEventListener('load', () => {
        const clone1 = original.clone();
        expect(original.getScale()).to.eql(clone1.getScale());
        original.setScale(3);
        expect(original.getScale()).to.be(3);
        const clone2 = original.clone();
        expect(original.getScale()).to.eql(clone2.getScale());
        done();
      });
```

Won't `3` be changed to `[3, 3]` ?

**Comment by ahocevar** [comment]
@mike-000 Yes it will, but that won't affect the visual representation of the icon.

**Comment by ahocevar** [comment]
@mike-000 Yes it will, but does it matter? It does not make a difference in the visual representation of the icon.

**Comment by mike-000** [comment]
> @mike-000 Yes it will, but does it matter? It does not make a difference in the visual representation of the icon.

In that case a potential future update might be to always store and return all image and text scales only as arrays regardless of how they is set, avoiding the need for a separate `getScaleArray` for rendering.

**Comment by mike-000** [comment]
> but does it matter?

It would if someone is using `getScale()` in an arithmetic expression

**Comment by ahocevar** [comment]
Well, if they are using type checking they would get a type checking error because the returned value can also be an array.

**Comment by mike-000** [comment]
That is a big if.  Someone might be doing `image.setScale(image.getScale() * 2)` to highlight something.

**Comment by ahocevar** [comment]
It's standard when using an IDE like VS Code.

**Comment by mike-000** [comment]
> Someone might be doing `image.setScale(image.getScale() * 2)`

OpenLayers code does use `.getScaleArray()[0]` when doing something like that https://github.com/openlayers/openlayers/blob/main/src/ol/format/KML.js#L1358

The same should apply with text scale.  https://github.com/openlayers/openlayers/blob/main/src/ol/format/KML.js#L2701 is clearly expecting a numeric value, but in theory it could be an array (which would be invalid in the output) and using `.getScaleArray()[0]` would be safer (and would be needed if an array was always returned).

**Comment by ahocevar** [comment]
I really wish #14346 had never been merged the way it was merged. It really made the API of `ol/style/Icon` worse than it was already, and I feel sorry now that I had motivated @KaiVolland to work on that.

To prevent unexpected behavior, I added a commit that prevents `setScale()` from being called when `width` or `height` were set.

The underlying problem is that `ol/style/Icon` serves both the uses case where the icon's image is used for the icon as a whole, and where the image is a sprite sheet that multiple icons can be referenced from using `size` and `offset`. Now when `width` or `height` are specified, will the scale be calculated from their ratio to the image, or the icon? In fact, it is the image, although the scale is applied to the icon. I tried to add this fact to the description of the `width` and `height` properties.

@marcjansen @KaiVolland Maybe you guys want to review this. I hope this pull request does not break your applications.

**Comment by ahocevar** [comment]
I had to add yet another commit, to avoid unexpected behavior related to `size` (and `offset`).

**Comment by ahocevar** [comment]
A possible better alternative to this pull request would be to change the behavior to calculate the `scale` from `width`, `height` and `size`. This means that `size` would have to be set when `width` and `height` are provided. @KaiVolland Do you think you could live with that?

**Comment by mike-000** [comment]
If the size was known in advance the change would not have been needed as it would have been possible to set the necessary scale.  The problem was similar to setting the correct scale for KML icons https://github.com/openlayers/openlayers/blob/main/src/ol/format/KML.js#L311-L313 where a KML scale of 1 is based on showing a minimum width or height of 32, but you do not know the dimensions to scale to that size until the image is loaded.

**Comment by ahocevar** [comment]
Yes, we all agree that the API is awkward, and we'll need to rework this whole thing, making breaking changes. Closing this in favor of #14619, so the new `width` and `height` settings calculate the scale in relation to the icon size, instead of the image size.

**Pull request closed without merging**
