### PR TITLE
Issue/6991/WFS Write Dimension

### PR DESCRIPTION
**Pull request by Sol1du2**
Adds srsDimension to the pos and posList nodes when writing a WFS transaction
    
The WFS transaction failed if the srsDimension was not present on the geometries.
Unit tests have been changed to accomodate the srsDimension attribute.

Make sure these boxes are checked before submitting your pull request. Thank you!

- [x] This pull request addresses an issue that has been marked with the 'Pull request accepted' label.
- [x] It contains one or more small, incremental, logically separate commits, with no merge commits.
- [x] I have used clear commit messages.

### CODE REVIEW

**Comment by Sol1du2** [comment]
I just realized that I mistakenly left two commits that should've been squashed. 
I apologize for this. Please let me know if you want me to re-submit the pull request.

**Comment by bartvde** [comment]
@Sol1du2 you can still squash them and force push, no need for a new PR
TIA

**Comment by Sol1du2** [comment]
Ah, perfect. Living and learning :)

**Comment by Sol1du2** [comment]
Hm. How do you derive the srsDimension from the srsName? Isn't that independent from the projection?

**Comment by bartvde** [comment]
Some projections are 3D for instance: http://spatialreference.org/ref/epsg/4327/

But I think we can safely ignore this for now.

**Comment by Sol1du2** [comment]
Oh I see. I thought the projection could always contain an Z coord, that could be defined in another projection.

**Pull request merged**
