### PR TITLE
Abort loading when tile is disposed

### LINKED ISSUE #5532: Not stopping pending tile requests
I'm using ol.layer.Tile with ol.source.XYZ to load tiles from a specific tile server. 
Panning and zooming the map I noticed that the old pending tile requests (for example, the ones made to load a previous zoom level) are not automatically aborted, they keep going until they get a response.

### PR DESCRIPTION
**Pull request by ahocevar**
This is a follow-up on #5816.

Fixes #5532.

### CODE REVIEW

**Comment by fredj** [comment]
Note: `'image/gif'` is not supported on (at least) Chrome but the browser fallback to `'image/png'`

**Comment by ahocevar** [comment]
Updated to use `image/png`.

**Comment by thomasmoelhave** [comment]
Interesting stuff! Does it increase perceived performance when panning/zooming around on the map?

**Comment by ahocevar** [comment]
@thomasmoelhave It does when you configure your tile source with a small or zero `cacheSize`.

**Comment by thomasmoelhave** [comment]
Interesting, I guess it could have a big impact of the performance of the tile transition use-case as well (i.e. this stuff https://openlayers.org/en/latest/examples/wmts-dimensions.html )

**Pull request merged**
