### PR TITLE
Support for newer IGC format versions

### LINKED ISSUE #15689: IGC: new file format
**Actual flight recorders use the new format of IGC files**
The reference is at https://www.fai.org/sites/default/files/igc_fr_specification_with_al8_2023-2-1_0.pdf
Among the changes, the date (day) of flight is now stored in a new header (HFDTEDATE).
Another header (the I), which describes adds to the fixes is not computed.

**Modifying ol/format/IGC to parse more data from files .igc**
In the context of OpenLayers, not all data of the new format is usable
but some are mandatory (time of fix, exact position ...)

### PR DESCRIPTION
**Pull request by llarquere**
- compute new header HFDTEDATE
- compute new header I (only adds LAD and LOD)

Fixes #15689

### CODE REVIEW

**Comment by ahocevar** [comment]
Thanks @llarquere ! Could you please run `npm run lint -- --fix` to remove the linter errors?

**Comment by llarquere** [comment]
> Thanks @llarquere ! Could you please run `npm run lint -- --fix` to remove the linter errors?

that's done

**Comment by ahocevar** [comment]
Thanks @llarquere! Do you think you'd also be able to add a test, similar to the existing one in `test/browser/spec/ol/format/igc.test.js`?

**Comment by llarquere** [comment]
> Thanks @llarquere! Do you think you'd also be able to add a test, similar to the existing one in `test/browser/spec/ol/format/igc.test.js`?

Do you mean :
modifying the actual hard-coded "const igc = ..." in this file
or
copy/modify this igc.test.js with a new content
?

**Comment by ahocevar** [comment]
Leave the existing test untouched, and add another one with a `const igc= ...` with the contents of a new IGC file.

**Comment by ahocevar** [comment]
Sorry for closing this, @llarquere. I wanted to push a commit to move your new test into the existing test file, but I messed it up because you're using `main` as the name of your feature branch. I created #15696 as replacement, with your commits.

For your next contribution, please remember to give the feature branch a different name than `main`.

**Pull request closed without merging**
