### PR TITLE
Update geotiff to v2.0.6

### LINKED ISSUE #13924: Importing GeoTIFF source causes compilation errors in Angular
**Describe the bug**
I am using OpenLayers 6.15.1 in an Angular 14 application and when I import the source GeoTIFF I get the following compilation errors:

```
Error: node_modules/geotiff/dist-node/geotiffimage.d.ts:67:118 - error TS2304: Cannot find name 'Source'.
67     constructor(fileDirectory: any, geoKeys: any, dataView: DataView, littleEndian: boolean, cache: boolean, source: Source);

Error: node_modules/geotiff/dist-node/geotiffimage.d.ts:75:13 - error TS2304: Cannot find name 'Source'.
75     source: Source;

Error: node_modules/geotiff/dist-node/geotiffimage.d.ts:134:100 - error TS2304: Cannot find name 'AbstractDecoder'.
134     getTileOrStrip(x: number, y: number, sample: number, poolOrDecoder: import("./geotiff").Pool | AbstractDecoder, signal?: AbortSignal | undefined): Promise<ArrayBuffer>;
```

**To Reproduce**
1. `ng new test-app`
2. `cd test-app`
3. `npm install ol`
4. Add `import GeoTIFFSource from 'ol/source/GeoTIFF';` to app.component.ts
5. `ng build`

**Expected behavior**
No compilation errors.
Please confirm if this should be reported on the _geotiff_ repository instead.

### PR DESCRIPTION
**Pull request by ahocevar**
Fixes #13924

### CODE REVIEW

**Comment by ahocevar** [comment]
As reported in #13655 already, this upgrade breaks https://deploy-preview-14257--ol-site.netlify.app/en/latest/examples/cog-math-multisource.html.

**Comment by ahocevar** [comment]
Fixed now with geotiff@2.0.7.

**Comment by tschaub** [comment]
Thanks for your work on geotiffjs/geotiff.js#336, @ahocevar.

> [ahocevar](https://github.com/ahocevar) changed the title ~Update geotiff to v2.0.7~ Update geotiff to v2.0.6 [1 hour ago](https://github.com/openlayers/openlayers/pull/14257#event-7753329559)

Minor, but shouldn't the title say v2.0.7 instead of v2.0.6?

**Comment by ahocevar** [comment]
@tschaub Initially I thought so too, but then this https://github.com/openlayers/openlayers/pull/14257#issuecomment-1303474533 would have been out of context.

**Pull request merged**
