### PR TITLE
Select event now report each selected feature with associated layer

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by sweco-sebhar** [comment]
@elemoine this is ready for review. I think tests made in #3453 covers the code added in this PR so this should be rebased as soon as that is merged.

**Comment by probins** [comment]
+1 from me for including layer in the SelectEvent. Amongst other things, it greatly simplifies multi-layer select for deletion.

**Comment by probins** [comment]
this one will need rebasing/reworking

**Comment by sweco-sebhar** [comment]
Rebased and resolved conflicts.

**Comment by bjornharrtell** [comment]
Rebased and resolved conflicts.

**Comment by probins** [comment]
needs rebasing again :-)

**Comment by bartvde** [comment]
Let's add a milestone so it ends up in the search for the next release manager (v3.8.0)

**Comment by tschaub** [comment]
> Let's add a milestone so it ends up in the search for the next release manager (v3.8.0)

I'm not sure I agree with this approach.  I don't think we want to put the onus on the release manager to review a bunch of outstanding pull requests - particularly ones with conflicts or ones that depend on other unfinished work.

I know that is sucks to have patches just sit around rotting, but I think we need to come up with a better way to get the work done rather than assuming the release manager will do it all.

This change in particular makes me a bit uneasy.  It sounds like it solves a pain point, but it looks like it would break any applications listening for select events.  So at a very minimum, it needs upgrade notes.  I'd also feel a lot more comfortable about it if I could read some tests related to the changes.  Without this, I didn't feel comfortable taking it on as an additional release task (in particular because it may very well break applications I'm responsible for elsewhere).

So @bjornharrtell, I appreciate your continued work to improve the situation with multi-layer selection.  I hope this can be resolved in a way that others feel good about.

(Also, very minor nit that I have a bias against tickets with *No description provided.*)

**Comment by bartvde** [comment]
yeah I didn't mean only the release manager (I know I wrote it like that ;-) ), but anybody searching for tickets to review in advance for a release

**Comment by bjornharrtell** [comment]
Agreed on all points. I hope to be able to revisit this in the near future to improve and fix the merge conflicts. 

As mentioned I'd like #3453 reviewed and hopefully merged before that because it resolves a long standing selection bug and adds tests that can be useful when working on this PR.

**Comment by ahocevar** [comment]
Closing due to lack of activity. @bjornharrtell please reopen if you continue working on it.

**Pull request closed without merging**
