### PR TITLE
#11402 add CSS class name support for control buttons

### LINKED ISSUE #11402: add CSS class name support control buttons
In order to use custom icons(like [Font Awesome](https://fontawesome.com/)) for control buttons we have to deal with the button's class name and this functionality is missing. 

It would be nice to have supported this syntax:
```
new ol.control.Zoom({
  zoomInLabel: '',
  zoomInClassName: 'fa fa-plus',
  zoomOutLabel: '',
  zoomOutClassName: 'fa fa-minus'
});

new ol.control.Attribution({
  label: '',
  expandClassName: 'fa fa-info',
  collapseLabel: '',
  collapseClassName: 'fa fa-angle-double-right'
});

new ol.control.Rotate({
  label: '',
  compassClassName: 'fa fa-long-arrow-up'
});

new ol.control.FullScreen({
  label: '',
  inactiveClassName: 'fa fa-expand',
  labelActive: '',
  activeClassName: 'fa fa-compress'
});
```

Thank you!

### PR DESCRIPTION
**Pull request by cazacugmihai**
This PR fixes #11402.

### CODE REVIEW

**Comment by cazacugmihai** [comment]
Can someone look over this PR, please?

**Review by ahocevar — APPROVED** [review]
Looks good. Thanks, @cazacugmihai.

**Comment by ahocevar** [comment]
c53ff622f2c92a655b8e455a01cababf09a34099 introduced a regression: the Rotate button's arrow does not indicate the map rotation any more - it is always upright.

**Comment by ahocevar** [comment]
Actually just a typo, but a fatal one. I created #11754 to fix this regression.

**Pull request merged**
