### PR TITLE
Addition of updateSketchCondition on Ol.interaction.draw as a way to fix #3907

### LINKED ISSUE #3907: Polygon draw interaction buggy on mobile devices
There seems to be a problem with ol.interaction.Draw when using it on mobile devices (primary on iOS).
The problem occurs when drawing a polygon and (as far as we've noticed) slightly move your finger when touching a point - the point will be drawn but when you add another point the previous one simply disappears!

We use Openlayers with default interactions (dragging, zooming etc) and dynamically add the draw interaction. I thought the problem would occur only in combination of these but it was also reproducable after removing any other interactions. And the problem also occurs on the demo page: http://openlayers.org/en/v3.5.0/examples/draw-features.html

It seems like there is some problem in the "event-detection" - meaning whether it's a simple touch event or drag on the user side. The point gets drawn on the map, but is never added to the polygon coordinates(?), and therefore disappears on the next click.
I could reproduce this problem on Android as well, but it's "harder" to do and unlikely because I have to actively move my finger on touching down (I think this is because Android and iOS handle touch/drag detection differently). The problem never appeared on desktop devices.

I've also uploaded a video where you can see the problem in action:
https://dl.dropboxusercontent.com/u/23708747/ShareX/2015-07/VIDEO0122.mp4

I hope this is enough information. I couldn't find anything likely on the web. And I would dig through the code myself but I'm not exactly a Javascript pro :)

### PR DESCRIPTION
**Pull request by daanoz**
By adding a updateSketchCondition we can fix issue #3907.

``` javascript
        var draw = new ol.interaction.Draw({
          features: featureCollection,
          type: 'Polygon',
          updateSketchCondition: function(event) {
            return event.originalEvent.type !== 'touchmove';
          }
        });
```

The concept of limiting the modifyDrawing_ function might also be used by other use cases like creating a boundingbox available to draw the features.

### CODE REVIEW

**Comment by bjornharrtell** [comment]
Got hit by this issue today. Tried this fix and it seems to do the trick. In my case I needed and tested this with the measure example code.

@daanoz, thanks for the patch. Usually they need branch squashed and CLA from you to accept contributions.

**Comment by bjornharrtell** [comment]
I've now also verified it helps resolve the general issues with `ol.interaction.Draw` as described in #3907.

**Comment by daanoz** [comment]
Thanks @bjornharrtell, I'll see what I can to get the CLA approved.

**Comment by bjornharrtell** [comment]
Great. I took the liberty of creating #4668 that squashed and fixes a minor documentation issue in case you where not available. You decide if you want to fix up this PR or close it in favor of mine (you are still be the main commit author in my PR).

**Comment by tschaub** [comment]
If the remaining work and conflict resolution can be completed before the upcoming 4.6 release, please reopen this pull request.  After 4.6, we will be transforming the sources to ES modules, and if we want to pick up this effort, it may be easier to create the changes from scratch.

**Pull request closed without merging**
