### PR TITLE
Make ol/interaction/Select#handleEvent return always true.

### LINKED ISSUE #9945: why multiple select interaction does not work?
I have multiple layers in my openlayers application. So I need layer based specific select interaction. Each layer will have its own select interaction. This is my problem. I do not want to add layers in one select interaction, because it is not my solution.

[Working application is here.](https://jsfiddle.net/veung7hc/)

### PR DESCRIPTION
**Pull request by TieSKey**
Fix #9945 https://github.com/openlayers/openlayers/issues/9945 

Make ol/interaction/Select#handleEvent return always true regardless 
of event type.
Previously it was returning true only if the event was a pointerMove
which prevented any but the last Select objects with other event types 
from working.

### CODE REVIEW

**Comment by TieSKey** [comment]
About the pointerMove, automated tools/test complaint it becoming an unused variable. I'm not familiar with the toolchain, is there a way to avoid this check?

**Comment by ahocevar** [comment]
@TieSKey You probably misunderstood the warning. It was only about the import of `pointerMove` in `ol/interaction/Select`, not about the export.

**Comment by ahocevar** [comment]
Thanks!

**Comment by TieSKey** [comment]
Thank you for your time reviewing and helping me with this minuscule (but necessary) change.

**Pull request merged**
