### PR TITLE
Allow unprefixed WMTS tileMatrix identifiers

### LINKED ISSUE #6699: ol.tilegrid.WMTS.createFromCapabilitiesMatrixSet
I'm not sure how WMTS is working correctly. WMTS document says tile coordinates (row, column) are positive, but after parsing a capabilities document, the tile sizes have negative values.

In ol-debug.js, line 76628, it says: "top-left origin, so height is negative"... nowhere in the WMTS spec is this true.

Bottom line, I'm getting negative tile coordinates from the WMTS layer which should not be possible...

### PR DESCRIPTION
**Pull request by fredj**
replace #7167
fixes #6699

Original code by @filipheymans

### CODE REVIEW

**Comment by fredj** [comment]
@bartvde can you please take look?

**Comment by jbelien** [comment]
Thanks @fredj !
Looking forward to see this merged and published 👍

**Comment by fredj** [comment]
@bartvde test case added

**Comment by bartvde** [comment]
thanks @fredj please merge when Travis agrees

**Comment by fredj** [comment]
Thanks for the review @bartvde

**Pull request merged**
