### PR TITLE
enterfullscreen and leavefullscreen map events, should address #4125.

### PR DESCRIPTION
**Pull request by devel0**

### CODE REVIEW

**Comment by ahocevar** [comment]
@fredj would you agree to such a change? In https://github.com/openlayers/openlayers/issues/4125#issuecomment-408875849 you suggested that users should listen for the browser's fullscreen* events instead.

**Comment by devel0** [comment]
I did such patch because using browser fullscreen event didn't worked for specific configuration I used, in other words but I didn't remember now what's exactly was, there was a timing problem using fullscreen browser event so that I cannot set some component ( toolbar, etc in the map ) because browser fullscreen fired before effective openlayer map availability.
Instead using proposed events from the map everthing worked in sync as expecting.

**Comment by fredj** [comment]
Hi, sorry for the late response.

I'm not against it but the event should originated from the fullscreen control, not the map.
@devel0 will #10683 work for you?

**Comment by devel0** [comment]
It should work because it will sync to the map state even originating from the fullscreen control and for sure it's a step forward to add requested feature, we could see further if it will fullfill certain usage scenario but I suppose it will work as expected. So definitively I happy if such addition will available.

**Comment by fredj** [comment]
see #10683

**Pull request closed without merging**
