### PR TITLE
Replace discontinued ArcGIS sample Feature Service with open data service

### PR DESCRIPTION
**Pull request by mike-000**
Replaces the discontinued sampleserver1 service used in the ArcGIS REST Feature Service example with an open data service.

https://deploy-preview-14253--ol-site.netlify.app/en/latest/examples/vector-esri.html

### CODE REVIEW

**Comment by mike-000** [comment]
As with the original example the styles are copied from the Arcgis layer Drawing Info.  It might be better to fetch the layer definition json and create the styles dynamically.

**Comment by mike-000** [comment]
Was there a historical reason for using a loader function and jquery?  It would work with just a url function and format.

**Comment by ahocevar** [comment]
> Was there a historical reason for using a loader function and jquery? It would work with just a url function and format.

Yes, that example was there before the url function. Please update to use a url function.

**Comment by ahocevar** [comment]
Replaced by #14296.

**Pull request closed without merging**
