### PR TITLE
Use local font "Ubuntu Regular" for rendering tests

### PR DESCRIPTION
**Pull request by KaiVolland**
Set local font for all rendering tests including TextStyles to enhance comparability on different systems.

### CODE REVIEW

**Comment by ahocevar** [comment]
I could think of two reasons for the differences:

1. The fonts are not yet loaded when the image is taken. To make sure the font is loaded, you could listen to the `'clear'` event on `ol/render/canvas.labelCache`.
2. The font is not defined for 12px, so browsers scale them differently. Maybe 16px works better? Also make sure to not define a fallback font, i.e. `'16px "Ubuntu Regular"'` instead of `'12px "Ubuntu Regular", sans-serif'`.

**Comment by KaiVolland** [comment]
> 2. The font is not defined for 12px, so browsers scale them differently. Maybe 16px works better? Also make sure to not define a fallback font, i.e. '16px "Ubuntu Regular"' instead of '12px "Ubuntu Regular", sans-serif'.
I tried to fix it as propsed. 

But i think the font is loaded correctly as the shape of the letters is identical.
What differs is weight, height and maybe spacing.

**Comment by ahocevar** [comment]
> But i think the font is loaded correctly as the shape of the letters is identical.
What differs is weight, height and maybe spacing.

Right. It will be necessary to find the exact size and weight that the Ubuntu Regular fonts you added are defined for. So maybe `16px Ubuntu` and `italic bold 16px Ubuntu` would work as `font` property for better cross-platform results.

**Comment by ahocevar** [comment]
I also noticed that the `pixelRatio` configuration on the map is missing in some of the tests. This is important when running tests on devices that have a different pixel ratio.

**Comment by KaiVolland** [comment]
I finally satisfied the CI by decreasing the font sizes which leads to comparing more white pixels. Not sure if  I'm satisfied with theses results, too. But at least the test are green now.

**Comment by ahocevar** [comment]
Thanks for your continued effort on this @KaiVolland. Most of the changes are good, but the 2px fonts are too small. The risk of breaking renderer changes to fall through the tolerance is too high here. Maybe going back to a larger font size for those works, in combination with also setting a line height. Something like `'normal 400 12px/1 Ubuntu'`

**Comment by marcjansen** [comment]
Thanks @KaiVolland & @ahocevar for the collaborative effort! :clinking_glasses:

**Pull request merged**
