### PR TITLE
Abort image loading for image layers

### LINKED ISSUE #8425: Cancel old image source requests
Hello,
I noticed that in the recent ol versions wms requests are managed differently. In the 2.10 version, if i zoom in and out, the previous wms requests are canceled.

image

Nowadays, every single request is processed.

image

This leads to a very low performance.

Is it possible to cancel a wms request when we already ask for another one?

Many Thanks!

### PR DESCRIPTION
**Pull request by ahocevar**
This is an alternative solution to #8430.

Fixes #8425.

### CODE REVIEW

**Comment by josepgomes** [comment]
It seems is not working as expected. Did it worked in your tests?

**Comment by ahocevar** [comment]
@josepgomes Can you provide a test case that you expect to pass?

**Comment by josepgomes** [comment]
Hi,
I can't, but i can explain the problem and my current solution (for the product that i'm working for).
The problem is simple, when zooming, using images not tiles, the browser makes a wms request for each new zoom, because the image.SRC was updated.

The problem is that when we zoom multiple times, SRC is updated multiple times, and the browser will process every single request, even when we just need the last one.

My current solution is set a custom imageLoadFunction:

```typescript
private previousImageElement: HTMLImageElement;

const source = this.getSource() as ol.source.ImageWMS;
source.setImageLoadFunction(this.imageLoadFunction.bind(this));

private imageLoadFunction(image, src) {
    this.previousImageElement.src = src;
    this.previousImageElement.onload = () => {
        image.getImage().src = this.previousImageElement.src;
    };
}
```

With this solution loading times are fine. Hope you can understand and implement this ideia.

**Comment by ahocevar** [comment]
Tell me if I'm missing something. To me it looks like your solution debounces image loading, but in a weird way (i.e. by loading the new url in the previous image element, and then when loaded loading it again in the current image element). In the end, your solution also sets an image src for every zoom level, but it does so on the previous image element.

**Comment by josepgomes** [comment]
I don't fully understand why this works, but i tested your changes and they don't abort any request. I will try to figure this out.

**Comment by ahocevar** [comment]
I don't think the extra code justifies the outcome. Closing.

**Pull request closed without merging**
