### PR TITLE
Snap Interaction can snap to Point on line segment

### LINKED ISSUE #13440: Snap Interaction cannot snap to Point which lies on line segment
**Describe the bug**
When different Point lies on or near to line segment, interaction cannot snap to this point.

**To Reproduce**
Steps to reproduce the behavior ([video](https://user-images.githubusercontent.com/142462/156726272-b950481f-28f6-4465-8f61-79e48f9c1d46.mp4)):
1. Go to [Snap Interaction](https://openlayers.org/en/latest/examples/snap.html)
2. Draw LineString with 2 segments
3. Draw Point snapped on one of segments
4. Try to snap to created Point

**Expected behavior**

Like the vertex on LineString attracts snapping, the Point should attract too.

### PR DESCRIPTION
**Pull request by langpavel**
Fixes #13440

### CODE REVIEW

**Comment by langpavel** [comment]
@tschaub, @ahocevar Ready to review

**Review by MoonE — APPROVED** [review]
I'd like to include this 
https://github.com/openlayers/openlayers/compare/0c23e17e138b091daab06d07230b46527c9c9076...MoonE:interaction-snap-bug-13440
Would you be able to give maintainers write access to this pull request or reset your branch to this?

**Comment by langpavel** [comment]
@MoonE rebased

**Review by ahocevar — APPROVED** [review]
A great improvement, also in terms of code readability. Thanks @langpavel and @MoonE!

**Comment by MoonE** [comment]
Thanks, @langpavel.

**Comment by langpavel** [comment]
Thanks!

**Pull request merged**
