### PR TITLE
Add button to edit examples in CodePen

### PR DESCRIPTION
**Pull request by tchandelle**
It's more of a personal preference, I prefer CodePen over JSFiddle. And I think it would be a nice addition to the examples to be able to choose between both, similar to the examples in the MDN API.

This is what it looks like. Fortunately, the icon was already there in the css.
image

And this is what our examples looks like in CodePen : [Simple Map](https://codepen.io/anon/pen/mRjQWP?&editors=1010), [Advanced View Positioning](https://codepen.io/anon/pen/apjQWM?&editors=1110)

### CODE REVIEW

**Comment by tschaub** [comment]
Let's pick one.  I don't think there is justification for having two options for editing examples.  Can anyone list benefits and drawbacks of using CodePen instead of JSFiddle?

**Comment by tchandelle** [comment]
I prefer CodePen because I think it looks better and cleaner. The preview zone is bigger and is the right size for an OL map.
Also, it auto-refresh as you type.
And we can automatically hide the CSS tab if it's empty, which is 75% of the examples.

**Comment by tschaub** [comment]
I'd be in favor of switching to CodePen.

**Comment by tchandelle** [comment]
I've added a commit about the removal of JSFiddle. Let me know if we include it in this PR or not

**Comment by bartvde** [comment]
I have no strong preference, so I won't block a switch to codepen if others think this is better

**Comment by fredj** [comment]
No preference

**Comment by ahocevar** [comment]
I like CodePen, because it allows to upload assets in pro mode. Might make sense for users who want to try more advanced features that require additional resources.

I'd like to include this pull request in the next release. Objections?

**Pull request merged**
