### PR TITLE
Upgrade eslint to v4.0.0

### PR DESCRIPTION
**Pull request by marcjansen**
Our linter [eslint](https://www.npmjs.com/package/eslint) has just [released v4.0.0](http://eslint.org/blog/2017/06/eslint-v4.0.0-released), with some changes e.g. to already existing rules.

OpenLayers is especially affected by the [stricter checking of the indentation](http://eslint.org/docs/user-guide/migrating-to-4.0.0#indent-rewrite), when linting without source code changes we get:

>  ✖ 5505 problems (5505 errors, 0 warnings)

(all coming from indentation)

Since the upgrade guide suggests to fix the indentation (instead of reenabling a legacy option to reestablish the old behaviour), I used the `--fix` option to fix linting errors.

> We recommend upgrading without changing your indent configuration,  #...

Please review.

### CODE REVIEW

**Comment by marcjansen** [comment]
Anyone up for a quick look over this @openlayers/ol3?

**Comment by ahocevar** [comment]
I really liked the previous indentation style with 4 spaces for wrapped lines better.

**Comment by marcjansen** [comment]
ok, i'll see if i can configure this accordingly.

**Comment by marcjansen** [comment]
I have pushed some new commits with a modified `eslint` configuration (wrt the [indent-rule](http://eslint.org/docs/rules/indent)).

In package.json we now have:

```json
      "indent": [2, 2, {
        "VariableDeclarator": 2,
        "SwitchCase": 1,
        "MemberExpression": 2,
        "FunctionDeclaration": {
          "parameters": 2,
          "body": 1
        },
        "FunctionExpression": {
          "parameters": 2,
          "body": 1
        },
        "CallExpression": {
          "arguments": 2
        }
      }]
```

This results in far less changes by the `--fix` option.

I hav manually adjusted some changes (mostly JSDoc-comments on anonymous functions).

Many changes herein are now from our use / formatting of ternary expressions; we tend to indent twice if we add a line break, whereas the linter expects only one indentation. I failed to configure eslint accordingly.

What does everyone think @openlayers/ol3?

**Comment by tschaub** [comment]
I appreciate the effort to stay up to date with ESLint and have no strong opinions one way or the other with respect to the changes this brings.

I've enjoyed moving other projects to a Prettier based ESLint config (see [`eslint-config-planet`](https://github.com/planetlabs/eslint-config-planet/blob/master/index.js) for an example config) and have been thinking about proposing the same for OpenLayers.  It is surprisingly liberating to outsource all decisions about whitespace - especially when the tooling around enforcing those decisions is so nice.  So +1 for these changes, but before we get too custom with our `eslint-config-openlayers`, I think we should just go with a Prettier based ESLint config.

**Comment by marcjansen** [comment]
>
> I appreciate the effort to stay up to date with ESLint and have no strong opinions one way or the other with respect to the changes this brings.
>

Cool.

>
> I've enjoyed moving other projects to a Prettier based ESLint config (see eslint-config-planet for an example config) and have been thinking about proposing the same for OpenLayers. It is surprisingly liberating to outsource all decisions about whitespace - especially when the tooling around enforcing those decisions is so nice.
>

I feel the same, and would not at all be against moving to a more commonly shared configuration.


>
> So +1 for these changes, but before we get too custom with our eslint-config-openlayers, I think we should just go with a Prettier based ESLint config.
>

Is this an official approval of this PR? If so, I need a `+1`-review. If not I can close this and move forward with a PR that implements what you suggests: let `eslint-config-openlayers` extend the `Prettier` one, and only make tiny adjustments

**Comment by tschaub** [comment]
See #6945 for a PR that brings in a Prettier based configuration (with a link to a blocking issue).

**Comment by marcjansen** [comment]
Thanks for the review and your work in #6945, much appreciated.

**Pull request merged**
