### PR TITLE
Add Gml2 serializers to support WFS-T 1.0.0

### PR DESCRIPTION
**Pull request by Jenselme**
This PR adds `writeFeatureElement` and related serializers to `ol.format.GML2`. This will allow support for WFS-T version 1.0.0 (currently only 1.1.0 is supported witch GML3) I tested the serializers against a WFS 1.0.0 server (GeoServer) for these geometries:
- Lines
- Polygons
- Points
- MultiLines
- MultiPoints
- MultiPolygons

For these tests, in addition to these patches, I also applied a patch to use `ol.format.GML2.prototype.writeFeatureElement` in `ol.format.WFS.prototype.writeTransaction`. For those interested, the patch is [here](https://github.com/Jenselme/ol3/commit/857c6994043110c99392dc3258d1b45665c0dd22). I intend to open a PR for this as soon as this one is merged.

### CODE REVIEW

**Comment by Jenselme** [comment]
Any interest in this?

**Comment by bartvde** [comment]
Can you explain the rationale? Are there WFS-s out there that don't support WFS 1.1?

**Comment by Jenselme** [comment]
> Are there WFS-s out there that don't support WFS 1.1?

Sadly yes.
- [TinyOWS](http://mapserver.org/tinyows/index.html) : only supports getting the features and creating new ones in WFS-1.1.0. Creation and update are currently 1.0.0 only.
- [QGIS Server](http://qgis.org/en/site/) : only supports update in WFS-T 1.1.0. See [this issue](https://hub.qgis.org/issues/16088) where a user asks for WFS-T 1.1.0 and 2.0.0

Since we don't want to use GeoServer in our infrastructure (huge Java service), we have to rely on TinyOWS or QGIS to support WFS-T in our solutions. Hence this feature proposal to add GML2 serializers and then use them to get full WFS-T 1.0.0 support in OpenLayers.

**Comment by bartvde** [comment]
ok thanks for explaining, then it makes sense IMHO. Your code looks good at first glance, I hope to find some time for a proper review soon. Thanks for your patience.

**Comment by Jenselme** [comment]
>  I hope to find some time for a proper review soon

Looking forward to that.

> Thanks for your patience.

No problem.

**Comment by bartvde** [comment]
thank you for this solid contribution @Jenselme

**Pull request merged**
