### PR TITLE
Fixed modify feature test

### PR DESCRIPTION
**Pull request by simonseyock**
The example was not working.
See: http://openlayers.org/en/master/examples/modify-test.html
and: https://codepen.io/anon/pen/MoGWNj

### CODE REVIEW

**Comment by fredj** [comment]
What was not working is the modification of the inner triangle right ?

**Comment by simonseyock** [comment]
Yes, this was caused by the use of the undefined property features_ of the interaction inside of insertVertexCondition.
After changing this to select.getFeatures() the example is working again ...

But now I am asking myself: why was insertVertexCondition called in the first place?

**Comment by simonseyock** [comment]
The call is caused by the if-clause in line https://github.com/openlayers/openlayers/blob/master/src/ol/interaction/modify.js#L610

If i would rearrange the conditions so insertVertexCondition comes last it would only be called if the other conditions for inserting a vertex are met. 
This is probably not very important. Should I do that?

**Comment by fredj** [comment]
@simonseyock thanks for this fix, and sorry for the long delay

**Pull request merged**
