### PR TITLE
Avoid obtaining infinity with Math.tan function

### PR DESCRIPTION
**Pull request by rmourembles**
Check if coordinate value is in WORLD_EXTENT.
If yes, replace coordinate value to avoid obtaining the inifinite with Math.tan function.

### CODE REVIEW

**Comment by ahocevar** [comment]
This is not a behaviour we want as default in the library, because it changes coordinates without notice. It is the responsibility of the app developer to avoid coordinate conversions outside the projection's validity extent.

If you want to help improve the behaviour of the library, you could add an assertion that warns the app developer when a coordinate conversion leads to Infinity results.

**Comment by rmourembles** [comment]
Ok, thanks for your answer

**Comment by marcjansen** [comment]
Plus 1 for the assertion. Will come in handy, I know.

**Comment by tschaub** [comment]
I think it would be worth discussing this a bit more.  I think it would be pretty nice behavior to have `ol.proj.transform()` return finite coordinates where possible.  We could add documentation saying that transforms outside the validity extent cannot be considered reliable.

**Comment by tschaub** [comment]
If the remaining work can be completed before the upcoming 4.6 release, please reopen this pull request.  After 4.6, we will be transforming the sources to ES modules, and if we want to pick up this effort, it may be easier to create the changes from scratch.

**Pull request closed without merging**
