### PR TITLE
Use TypeScript for .d.ts genertion

### PR DESCRIPTION
**Pull request by ahocevar**
This is a work-in-progress experiment to get .d.ts generation working with TypeScript >= 3.7.

### CODE REVIEW

**Comment by KaiVolland** [comment]
Any progress on this one? Really looking forward to it. :)

**Comment by ahocevar** [comment]
I’m currently too busy with other work, so I haven’t had a chance to look into it further. But feel free to continue where I left.

**Comment by KaiVolland** [comment]
If i find some time. I'll give it a try.

**Comment by boeckMt** [comment]
it is working with [typescript@3.7.0-beta](https://www.npmjs.com/package/typescript/v/3.7.0-beta) 
after 3.7.0-beta there is an [error ](https://github.com/microsoft/TypeScript/issues/34869)

```
TypeError: Cannot read property 'valueDeclaration' of undefined
```

**Comment by ahocevar** [comment]
TypeScript issues that are blocking us here:

* Fix available: microsoft/TypeScript#34869
* Not yet fixed: microsoft/TypeScript#33575

**Pull request closed without merging**
