### PR TITLE
Fixes issue openlayers#8863

### PR DESCRIPTION
**Pull request by timkeane**
replace ol/geom/Geometry#containsXY with an implementation suitable for all point and linear geometry types

### CODE REVIEW

**Comment by fredj** [comment]
@timkeane can you please rebase your work onto origin/master?
We're now using CircleCI instead of travis and your branch doesn't contains the config file.

And `package-lock.json` must not be commited.

Thanks for the pull request !

**Comment by timkeane** [comment]
rebased and package-lock removed

**Comment by fredj** [comment]
I should have mention the instructions for doing a rebase: https://github.com/openlayers/openlayers/blob/master/CONTRIBUTING.md#contain-a-clean-history-of-small-incremental-logically-separate-commits-with-no-merge-commits

What we want is only your commit on top of the master branch.

To fix it, run the following commands:
```shell
# create a clean branch from origin/master
# assuming that origin is https://github.com/openlayers/openlayers/
git checkout -b tmp origin/master
rm -f package-lock.json
# apply all your commits
git cherry-pick 3a1a37b 2f348c0 83d6daa a60800e e088096 b0fb28b
# push the result to your fork
# assuming that timkeane is https://github.com/timkeane/openlayers/
git push --force timkeane tmp:master
```

Ask me if you need help with it

**Comment by fredj** [comment]
@timkeane I've cleaned the code and opened a new pull request, see #8910

**Pull request closed without merging**
