### PR TITLE
style: status badge for `Test` in `README.md`

### PR DESCRIPTION
**Pull request by hamirmahal**

### CODE REVIEW

**Comment by hamirmahal** [comment]
# Without this change

image

**Comment by hamirmahal** [comment]
# With this change

image

**Comment by tschaub** [comment]
This badge is included at the bottom of this same file

https://github.com/openlayers/openlayers/blob/c6c60446a49e1c87533fcdb85a5692f8a8ff2051/README.md?plain=1#L118

**Comment by hamirmahal** [comment]
Ah, I didn't even notice that.

**Comment by hamirmahal** [comment]
Maybe we should move it to the top, to make it more prominent?

**Review by hamirmahal — COMMENTED** [review]
.

**Review by hamirmahal — COMMENTED** [review]
Maybe we should move it to the top, to make it more prominent?

**Comment by ahocevar** [comment]
@hamirmahal We put it at the bottom on purpose, as that information is usually not the first information a user is looking for. I'd be interested to hear why you think that badge should occupy space at the top of the README.

**Comment by hamirmahal** [comment]
@ahocevar I've found badges for status checks at the top to be useful because they let viewers immediately see the status of what maintainers consider the most important CI checks, without having to manually click on the mark next to the latest commit to see details.

**Comment by hamirmahal** [comment]
Most major repositories place that information at the top, so viewers likely expect it to be there, if it's present at all.

https://github.com/ohmyzsh/ohmyzsh/
https://github.com/vinta/awesome-python
https://github.com/twbs/bootstrap?tab=readme-ov-file#table-of-contents
https://github.com/tensorflow/tensorflow

and

https://github.com/facebook/react all follow the convention of putting badges at or near the top.

**Comment by hamirmahal** [comment]
https://github.com/encode/django-rest-framework
https://github.com/pandas-dev/pandas
https://github.com/flask-admin/flask-admin
https://github.com/sehmaschine/django-grappelli
https://github.com/flask-restful/flask-restful

and

https://github.com/sharkdp/bat are some more popular repositories that follow this convention.

**Comment by hamirmahal** [comment]
https://github.com/apache/zookeeper and https://github.com/graphhopper/graphhopper are a couple more examples.

**Comment by hamirmahal** [comment]
@ahocevar It's for the reason I [mentioned previously](https://github.com/openlayers/openlayers/pull/15618#issuecomment-1985273587); it's easier for readers to see the status of important checks.

**Comment by tschaub** [comment]
Thanks for the proposed changes.  I think we'll leave things as they are.

**Comment by hamirmahal** [comment]
You’re welcome.

**Pull request closed without merging**
