### PR TITLE
Fix for #15296 bug

### PR DESCRIPTION
**Pull request by piotrintes**
Fix for #15296 - the canvas opacity change changes the opacity for all WebGL rendered layers instead only the current one. Removing the 4 lines that do that doesn't seem to break anything and it fixes the issue.

### CODE REVIEW

**Comment by mike-000** [comment]
This also fixes a previously unnoticed bug.  With just one layer the opacity was applied twice, so when specified opacity was 0.5 the result was 0.25.  Additional rendering tests based on https://github.com/openlayers/openlayers/tree/main/test/rendering/cases/webgl-vector would be useful.

**Comment by piotrintes** [comment]
Ok, I've updated the test to use the VectorLayer. One thing to note here: I don't see a dedicated WebGL VectorLayer (there's WebGLPoints and WebGLTile, but no WebGLVector) . The only way to get WebGL rendered VectorLayer I know of, is to extend the VectorLayer and override createRenderer to create and return WebGLVectorLayerRenderer instance (or a class extending it) - is in webgl-vector test for example.

**Comment by mike-000** [comment]
#16394 recently added WebGLVectorLayer, so the test can be updated if you rebase.

**Comment by piotrintes** [comment]
Ah, ok. I didn't see it then. That explains it.

**Comment by jahow** [comment]
Looks like the lint step is failing, could you please try and fix it? thanks

**Review by jahow — APPROVED** [review]
Thank you for the fix!

**Pull request merged**
