### PR TITLE
Add ol.format.filter.during

### PR DESCRIPTION
**Pull request by fredj**
WFS During temporal operator.
Tested with mapserver

### CODE REVIEW

**Comment by bartvde** [comment]
@fredj is this from Filter 2.0?

**Comment by fredj** [comment]
from http://docs.opengeospatial.org/is/09-026r2/09-026r2.html

**Comment by bartvde** [comment]
but we only support WFS 1.0 and 1.1 right now which are tied to Filter 1.0 and Filter 1.1?

**Comment by bartvde** [comment]
has MapServer backported this filter to WFS 1.0 or 1.1 or are you using WFS 2.0 somehow?

**Comment by fredj** [comment]
I guess WFS 2.0 because the during filter comes from this PR: https://github.com/mapserver/mapserver/pull/4815

**Comment by fredj** [comment]
Thanks for the review Bart

**Pull request merged**
