### PR TITLE
Add constrainResolution to MouseWheelZoomOptions

### PR DESCRIPTION
**Pull request by ahocevar**
Follow-up on #6671.

### CODE REVIEW

**Comment by fredj** [comment]
```
ERR! compile /home/travis/build/openlayers/openlayers/src/ol/interaction/dragbox.js:85: WARNING - dangerous use of the global this object
ERR! compile   return width * width + height * height >= this.minArea_;
ERR! compile                                             ^^^^
```
is related to #6680, new PR to come

**Comment by ahocevar** [comment]
> src/ol/vectortilecache.js must be removed from bea6eb0

Done.

**Comment by fredj** [comment]
Don't you want to include your doc and example commit?
1e32f3d9588cd6482e6ef583d98e24ce25f73300
5dee1946fbd081c51064627c2592042515bdf33f

**Comment by ahocevar** [comment]
Ah of course. Thanks for the reminder @fredj.

**Pull request merged**
