### PR TITLE
Better vectortile experience

### PR DESCRIPTION
**Pull request by ahocevar**
This change brings interim tiles to vector image tiles. So when e.g. zooming in or panning, vector tile data from lower resolutions can be used and rendered. Users no langer have to stare at blurry lines and polygons while waiting for the tiles to load. The upscaled images are now only used when the frame time budget is exceed, so they are either not shown at all, or only for a very short time.

Overall performance also improves with this change, because the frame time budget is exceeded less often, so animations are more likely to finish within the scheduled time.

**Before**
may-24-2018 17-04-28

**After**
may-24-2018 17-04-17

### CODE REVIEW

**Comment by ahocevar** [comment]
Something appears to be broken in Sauce Labs. Tests pass locally.

**Comment by ahocevar** [comment]
Something is strange with the tests. At test 2804, there is a disconnect. I need to look into that.

**Comment by fredj** [comment]
I also get an error when running the tests locally (`npm run karma`):
```
25 05 2018 15:14:22.699:INFO [karma]: Karma v2.0.0 server started at http://0.0.0.0:9876/
25 05 2018 15:14:22.699:INFO [launcher]: Launching browser Chrome with unlimited concurrency
25 05 2018 15:14:22.720:INFO [launcher]: Starting browser Chrome
25 05 2018 15:14:23.210:INFO [Chrome 65.0.3325 (Linux 0.0.0)]: Connected on socket 19boUtf5nQTIkwUTAAAA with id 41687744
Chrome 65.0.3325 (Linux 0.0.0): Executed 1544 of 2973 (skipped 29) SUCCESS (0 secs / 5.206 secs)
Chrome 65.0.3325 (Linux 0.0.0): Executed 1545 of 2973 (skipped 29) SUCCESS (0 secs / 5.214 secs)
Chrome 65.0.3325 (Linux 0.0.0): Executed 2327 of 2973 (skipped 29) SUCCESS (0 secs / 17.811 secs)
Chrome 65.0.3325 (Linux 0.0.0): Executed 2337 of 2973 (skipped 29) SUCCESS (0 secs / 17.828 secs)
Chrome 65.0.3325 (Linux 0.0.0): Executed 2804 of 2973 (skipped 29) SUCCESS (0 secs / 18.357 secs)
Chrome 65.0.3325 (Linux 0.0.0) ERROR
  Disconnected, because no message in 10000 ms.
Chrome 65.0.3325 (Linux 0.0.0): Executed 2804 of 2973 (skipped 29) DISCONNECTED (31.896 secs / 18.357 secs)
```

**Comment by ahocevar** [comment]
Issue fixed. It was the missing new `zoom` argument for `VectorImageTile` in the test.

This is now ready for review.

**Pull request merged**
