### PR TITLE
Make Overlay.panIntoView an API method

### PR DESCRIPTION
**Pull request by ejn**
* Add parameters for custom animation parameters and margin

 * Add protected wrapper method for previous autoPan functionality

See #10741

### CODE REVIEW

**Comment by tschaub** [comment]
It could be nice to have the function take a single `options` object.  This would have `animation` and `margin` properties and would allow more options to be added in the future without an awkwardly long signature.

To do this, you would create a new type as is done with the existing constructor options.

**Comment by ejn** [comment]
I agree. It would also then make sense to alter the autoPan options to use the new type rather than being two separate parameters to the constructor (and two internal properties).

**Comment by ejn** [comment]
so autoPanOptions in the constructor options instead of autoPanAnimation and autoPanMargin, and then carry the change through the whole class? autoPanAnimation and autoPanMargin could be left in as deprecated options for backward compatibility to avoid breaking the API.

**Comment by ejn** [comment]
@tschaub the test failures (rendering test) appear to be unrelated to this change: Could you force the build to run again?

**Comment by ejn** [comment]
@ahocevar Nice and obvious idea - should have thought of that myself!

**Pull request merged**
