### PR TITLE
Update ol-mapbox-style and use MapboxVectorLayer in test

### PR DESCRIPTION
**Pull request by ahocevar**
Maybe this fixes the issue that should have been fixed with #15032.

### CODE REVIEW

**Comment by ahocevar** [comment]
I have re-run the tests several times now, and could not make any rendering test fail.

**Review by tschaub — APPROVED** [review]

**Comment by tschaub** [comment]
This one is finicky https://github.com/openlayers/openlayers/actions/runs/5952338648/job/16144112944

**Comment by ahocevar** [comment]
Still the font loading issue. I'll try to improve the rendering test once again.

**Comment by ahocevar** [comment]
See #15046.

**Pull request merged**
