### PR TITLE
Make mousewheel zoom behave like trackpad zoom.

### PR DESCRIPTION
**Pull request by dbrnz**
This resolves issue #9564.

### CODE REVIEW

**Comment by jahow** [comment]
Hi,

Could you please rebase this PR & make it so that tests pass? This way we'll be able to see on the examples the proposed behaviour (the CI publishes the examples as artifact). Thanks!

**Comment by dbrnz** [comment]
@jahow the tests now pass, so over to you!

**Comment by jahow** [comment]
Okay, I get it now, thanks! From a user point of view the objective would be to reduce (and make snappier) the zoom "gap" on each mousewheel click.

I personally agree that it would be great to get rid of this distinction between mousewheel and trackpad. Although with this PR the zoom lacks smoothing (esp. in firefox) since in trackpad mode the zoom change is not animated. Do you think this could be addressed?

Thanks for your contribution!

For reference, an example with the updated code: https://1470-4723248-gh.circle-artifacts.com/0/examples/simple.html

**Comment by icholy** [comment]
@dbrnz are you still planning to work on this?

**Comment by dbrnz** [comment]
@icholy I've stopped work on this -- the PR is there if anyone else wants to polish it. As it stands it significantly improved zooming behaviour in our application. We have also since moved to mapbox-gl, generating and serving vector-tiled maps ourselves.

**Comment by icholy** [comment]
@dbrnz alright, thanks for the work you've put in. If I have time I'll try to take it over the finish line.

**Comment by oeway** [comment]
Hi, is there a chance that this can be merged? I am having the same issue with mouse wheels, but it behaves nicely on my trackpad.

**Comment by ahocevar** [comment]
I have rebased the pull request now and resolved the conflicts. Looking into the code and the result now.

**Comment by oeway** [comment]
@ahocevar Thank you very much for working on this!

**Comment by jahow** [comment]
I've tried it again and it honestly feels nice. The zoom in/out animation in firefox is pretty much gone but the whole interaction feels snappier and more responsive. So +1 on my side :) thanks

**Pull request merged**
