### PR TITLE
Remove font sizing from the attribution control

### PR DESCRIPTION
**Pull request by fredj**
replaces #10103

examples:
https://2335-4723248-gh.circle-artifacts.com/0/examples/attributions.html
https://2335-4723248-gh.circle-artifacts.com/0/examples/bing-maps.html

### CODE REVIEW

**Comment by fredj** [comment]
New versions:
https://2340-4723248-gh.circle-artifacts.com/0/examples/attributions.html
https://2340-4723248-gh.circle-artifacts.com/0/examples/bing-maps.html

**Comment by tonio** [comment]
Changes to `ol.css` looks good.
The max-width in`layout.css` was to avoid extra lines like:

Screenshot from 2019-10-10 09-13-25

**Comment by fredj** [comment]
@tonio I've added back the `max-width` in `layout.css`

**Comment by fredj** [comment]
Thanks for the review

**Pull request merged**
