### PR TITLE
Use an url template for ol.source.Zoomify

### LINKED ISSUE #3805: Zoomify: allow file extension as a property
A lot of projects use Zoomify layers for pixel-based views of large images. Normally Zoomify tiles are JPEGs, but using PNGs would enable transparency. Right now, the .jpg extension is hard-coded into the tileUrlFunction. It would be great if this could be set as a property for ol.Source.Zoomify.

https://github.com/openlayers/ol3/blob/v3.6.0/src/ol/source/zoomifysource.js

### PR DESCRIPTION
**Pull request by fredj**
replace #5567 
fix #3805

### CODE REVIEW

**Comment by fredj** [comment]
This change breaks the v3 api, it would be nice to include this in the v4 release

**Comment by ahocevar** [comment]
Do we really need to make this a breaking change? I think we could keep this backwards compatible with something like this in the constructor:
```js
var url = options.url;
if (options.url.indexOf('{tileGroup}') == -1) {
  url += '{TileGroup}/{z}-{x}-{y}.jpg';
}
var urls = ol.TileUrlFunction.expandUrl(options.url)

**Comment by ahocevar** [comment]
@fredj, if you agree with 25fd857830267f8b052e4a3971e7f953524b993a, please cherry-pick it and merge.

**Comment by fredj** [comment]
@ahocevar thanks !

**Pull request merged**
