### PR TITLE
typo

### PR DESCRIPTION
**Pull request by jipexu**
one u ...

### CODE REVIEW

**Comment by mike-000** [comment]
The same method is copied in some other examples, with the same typo 
https://openlayers.org/en/main/examples/export-map.html
https://openlayers.org/en/main/examples/drag-and-drop-custom-kmz.html

**Comment by jipexu** [comment]
thank @mike-000

**Comment by mike-000** [comment]
Also https://openlayers.org/en/main/examples/drag-and-drop-custom-mvt.html

**Comment by jipexu** [comment]
done too

**Review by tschaub — APPROVED** [review]

**Comment by tschaub** [comment]
Thanks, @jipexu

**Pull request merged**
