### PR TITLE
Move the nullFunction to ol/functions

### PR DESCRIPTION
**Pull request by fredj**
And rename it to `UNDEFINED`.

### CODE REVIEW

**Comment by fredj** [comment]
Thanks for the review

**Comment by marcjansen** [comment]
I find the new name as confusing as the old one. Can we call it `NO_OP`... or is this not better?

**Comment by fredj** [comment]
@gberaudo suggested the same to me 10 minutes ago :-)
Why not call it `NOOP` ? (jQuery, angular and lodash all have a `noop` function)

**Comment by marcjansen** [comment]
noop works as well.

**Comment by ahocevar** [comment]
VOID?

**Pull request merged**
