### PR TITLE
Respect pixel ratio with immediate render

### LINKED ISSUE #12192: pixelRatio not applied to lineDash in Canvas Immediate
When setting pixelRatio in ol/render.toContext() to give a sharp image on high device pixel ratio displays when rendering to Canvas Immediate, although pixel coordinates are correctly scaled, lineDash is not scaled as it is when rendering to a map. Thus it renders very differently depending on the device pixel ratio, typically blurring dashed lines into continuous lines (especially if the default "round" lineCap is used).

To demonstrate, the full code at the bottom of this post renders a dashed line on a map canvas and also (with exactly the same style) using canvas immediate rendering:
```
     var vectorContext = ol.render.toContext(ctx, {
        size: [500, 250],
        pixelRatio: ol.has.DEVICE_PIXEL_RATIO
      });
```
If viewed on a device with pixelratio > 1.0, the dashes and gaps in the canvas immediate line become much shorter in proportion to the line width. If the values in the lineDash array are scaled by pixelRatio, the problem is solved for CanvasImmediate, though this would require making a copy of the style if it is to also be used in a map.

Full code:
```
<!doctype html>
<html lang="en">
  <head>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/gh/openlayers/openlayers.github.io@master/en/v6.5.0/css/ol.css" type="text/css">
    <style>
      #immediate canvas {
        border: solid 1px grey;
      }
      .map {
        border: solid 1px grey;
        height: 400px;
        width: 100%;
      }
    </style>
    <script src="https://cdn.jsdelivr.net/gh/openlayers/openlayers.github.io@master/en/v6.5.0/build/ol.js"></script>
  </head>
  <body>
    <h4>Map rendering:</h4>
    <div id="map" class="map"></div>
    <h4>CanvasImmediate rendering:</h4>
    <div id="immediate">
      <canvas id="testCanvas">
    </div>
    <script type="text/javascript">

      // Common line style
      var lineStyle = new ol.style.Style({
        stroke: new ol.style.Stroke({
          color: 'red',
          width: 40,
          lineCap: "butt",
          lineDash: [50, 50]
        }),
      });

      // Map rendering
      var wkt = 'LINESTRING(10.689 -25.092, 38.814 -35.639)';
      var format = new ol.format.WKT();
      var feature = format.readFeature(wkt, {
        dataProjection: 'EPSG:4326',
        featureProjection: 'EPSG:3857',
      });
      var vector = new ol.layer.Vector({
        source: new ol.source.Vector({
          features: [feature],
        }),
        style: lineStyle
      });
      var raster = new ol.layer.Tile({
        source: new ol.source.OSM(),
      });
      var map = new ol.Map({
        layers: [raster, vector],
        target: 'map',
        view: new ol.View({
          center: [2952104.0199, -3277504.823],
          zoom: 4,
        }),
      });

      // CanvasImmediate rendering
      var testCanvas = document.getElementById('testCanvas');
      var ctx = testCanvas.getContext('2d');
      var lineGeom = new ol.geom.LineString([[120, 80], [450,200]]);
      var vectorContext = ol.render.toContext(ctx, {
        size: [500, 250],
        pixelRatio: ol.has.DEVICE_PIXEL_RATIO
      });
      vectorContext.setStyle(lineStyle);
      vectorContext.drawGeometry(lineGeom);

    </script>
  </body>
</html>
```

### PR DESCRIPTION
**Pull request by MoonE**
Fixes #12192 

Also fixes rendering of icons when the stride is not 2.

### CODE REVIEW

**Comment by richard-thomas** [comment]
Hi @MoonE , thanks for your patch. I'm assuming you don't need anything more from (and wouldn't be sure how to download/package your branch to test it with my code). However, let me know if you do! Is the branch waiting on a some future release gate to be merged with the trunk along with other patches?

**Comment by MoonE** [comment]
I meant to add some test, but am unsure what makes sense here.

**Comment by ahocevar** [comment]
A rendering test with a map configured with `pixelRatio: 2` might make sense.

**Review by ahocevar — APPROVED** [review]
Thanks, @MoonE!

**Pull request merged**
