### PR TITLE
Do not use stitchContext for ReprojImage

### LINKED ISSUE #15144: Raster reprojection assumes that projected pixels are square
**Describe the bug**

It seems that raster reprojection always tries to display square target pixels, which can lead to mis-alignments in some cases.

In the screenshot below I project a 5×5 pixels image where my intent is that each pixel of the source image covers an area of 3km by 2km. The blue circles show the expected centers of each pixels. The source projection is Lambert Conformal Conic and the target projection is Web Mercator.

image

We see that vertically the pixels are correctly aligned with their expected centers. However, horizontally we observe a mis-alignment. This is because OpenLayers tries to draw perfect squares only. On the left of the screenshot, we see that the first column of pixels of the  source image is repeated twice. The resulting projected column extends too far to the east. Ultimately, the 5×5 source image looks like a 7×5 image in the result.

**Expected behavior**

Instead, I would expect the pixels of the destination to be stretched so that the total number of “projected pixels” is exactly the same as the number of pixels of the source image.

Note that in my real use case, my “pixels” are actually square … in their source projection. They cover a 2km by 2km area, but when they are projected, the result may not be perfectly square, leading to similar mis-alignments.

It seems #4124 can not help for this use case, unless I missed something?

Is there a way to preserve the amount of source pixels in the projection result? Would the situation be different if I was using GeoTiff files instead of projecting PNG images?

### PR DESCRIPTION
**Pull request by mike-000**
Fixes #15144

Also fixes SVG image reprojection issues in https://github.com/openlayers/openlayers/pull/14945#issuecomment-1669616399 but as noted in https://github.com/openlayers/openlayers/pull/14933#issuecomment-1702626905 drawing an SVG to a context which has rotation or skew can cause significant performance issues in Firefox.

### CODE REVIEW

**Review by ahocevar — COMMENTED** [review]
@mike-000 Did the performance issues in Firefox exist already before this pull request? Do you have an example that shows the performance issue?

**Comment by mike-000** [comment]
> @mike-000 Did the performance issues in Firefox exist already before this pull request? Do you have an example that shows the performance issue?

Not in reprojection as the SVG would have been drawn to the stitchContext.  If the default `decode` loader is used there will be no performance problem, but for SVG images the quality will be reduced.  For an example of the performance problem when using SVGs and `load` compare https://cw3tpv.csb.app/ in Chrome and Firefox.

Unrelated to reprojection I would expect https://codesandbox.io/s/yfhh32?file=/main.js (which is slow in Chrome) to be unusable in Firefox.

**Comment by ahocevar** [comment]
Let me ask differently: does this pull request introduce a performance regression in Firefox? If not, is there a performance regression in Firefox between v7.5.2 and v8.1.0? If any, when does the performance regression occur?

**Comment by mike-000** [comment]
If reprojecting an SVG using

```
  source: new ImageSource({
    loader: createLoader({
      url,
      imageExtent,
      load,
    }),
  }),
```

there will be a performance regression.  However it is unlikely anyone would be doing that as previously the output quality  would have been no better than when using the the default loader.  To avoid that continue to use the default (at least for Firefox)

```
  source: new ImageSource({
    loader: createLoader({
      url,
      imageExtent,
      load: FIREFOX ? decode : load,
    }),
  }),
```

or better still use an SVG targeted loader as in #15013

**Comment by ahocevar** [comment]
Thanks @mike-000 for the clarification and the work on this!

**Review by ahocevar — APPROVED** [review]

**Comment by julienrf** [comment]
Hello, do you have an estimate of the next release date? I would love to have that fix available! Please let me know if there is anything I could do to help.

**Pull request merged**
