### PR TITLE
Add rendering test for the full build

### PR DESCRIPTION
**Pull request by ahocevar**
To avoid future regressions with the full build.

### CODE REVIEW

**Comment by ahocevar** [comment]
I'm changing this to use a tile we have locally available, to avoid network traffic.

**Comment by ahocevar** [comment]
Done.

**Comment by marcjansen** [comment]
How about also having https://github.com/openlayers/openlayers/pull/14407 What do you think?

**Review by marcjansen — APPROVED** [review]
This is great, thanks.

**Pull request merged**
