### PR TITLE
Limit the ZoomSlider's range to the view's constrained resolution.

### PR DESCRIPTION
**Pull request by MoonE**
Implements #10412

### CODE REVIEW

**Comment by ahocevar** [comment]
Looking at the changes in `ol/View`, I think this is something for @jahow to review.

**Comment by MoonE** [comment]
The ZoomSlider should update when max / min resolution changes, but this is not handled atm.
The needed events are missing, see  #10435.

**Comment by jahow** [comment]
I'll review this ASAP.

**Comment by MoonE** [comment]
The *getResolutionForValueFunction* function is only used by the *ZoomSlider* and not part of the api. I removed the the new *opt_constrained* parameter again and have it always constrain the resolution. The *ZoomSlider* is now using the new behavior without an option to configure it.

**Pull request merged**
